Repository commercetools/ui-kit, pull requests merged in 2018-09, with the labels that each got.

#12 fix: avoid machine-based paths in generated files
  scripts/generate-base-colors.js
  scripts/generate-base-shadows.js
  scripts/generate-colors-for-story.js
  src/materials/colors/base-colors.mod.css
  src/materials/shadows/base-shadows.mod.css
Labels: 🔮Type: Chore, 🙏Status: Code Review

#15 Clean up dependencies
  package.json
  src/components/time-range-picker/time-range-picker.story.js
  yarn.lock
Labels: 🔮Type: Chore, 🙏Status: Code Review

#22 chore: move dependancies to peer and dev deps
  package.json
Labels: 🙏Status: Code Review

#10 chore: update issue templates
  .github/ISSUE_TEMPLATE/add-new-component.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🔮Type: Chore, 🙏Status: Code Review

#26 Add `isItalic` to `Text.Detail` and `Text.Body`
  src/components/typography/text/README.md
  src/components/typography/text/text.js
  src/components/typography/text/text.mod.css
  src/components/typography/text/text.spec.js
  src/components/typography/typography.story.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Code Review

#32 Migrate PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/add-new-component.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
  lint-staged.config.js
  package.json
Labels: ✍️Type: Documentation, 🔮Type: Chore

#33 chore: export spacings and constraints
  src/index.js
Labels: 🙏Status: Code Review

#31 Setup changelog using conventional changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: 🔮Type: Chore, 🙏Status: Code Review

#48 chore: new approach for publishing docs
  scripts/publish-docs.js
Labels: ⛑Type: Refactoring, 🐛Type: Bug, 🔮Type: Chore

#50 chore(netlify): assign yarn env vars
  netlify.toml
Labels: 🔮Type: Chore

#51 chore(package.json): add keywords
  package.json
Labels: 🔮Type: Chore

#52 chore(package.json): add homepage
  package.json
Labels: 🔮Type: Chore

#55 chore(package.json): add bugs and repo urls
  package.json
Labels: 🔮Type: Chore

#58 Re-export `HorizontalConstraint` component
  src/index.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Code Review

#53 chore: disable docs publish script
  .travis.yml
  README.md
Labels: 🔮Type: Chore

#59 chore: bump version to 2.0.0-rc5, update changelog
  CHANGELOG.md
  package.json
Labels: 🙏Status: Code Review

#66 chore: update deps
  package.json
  yarn.lock
Labels: 🔮Type: Chore

#67 fix: use correct token for selected input background
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.mod.css
  src/components/inputs/localized-text-input/localized-text-input.mod.css
  src/components/inputs/money-input/money-input.mod.css
  src/components/inputs/number-input/number-input.mod.css
  src/components/inputs/password-input/password-input.mod.css
  src/components/inputs/text-input/text-input.mod.css
Labels: 🙏Status: Code Review

#68 fix: fix i18n exports
  i18n/index.js
Labels: 🙏Status: Code Review

#75 Readd forms example
  .storybook/config.js
Labels: 🔮Type: Chore, 🙏Status: Code Review

#76 Improve form examples, add errors to FieldErrors, fix TextField
  examples/form-fields.md
  examples/form-fields.story.js
  examples/form-inputs.md
  examples/form-inputs.story.js
  i18n/core.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  src/components/field-errors/field-errors.js
  src/components/field-errors/messages.js
  src/components/fields/text-field/text-field.js
Labels: ✍️Type: Documentation, 🙏Status: Code Review

#79 add react testing library
  .eslintrc.yaml
  jest.test.config.js
  package.json
  scripts/setup-test-framework.js
  src/components/inputs/text-input/text-input.spec.js
  src/test-utils.js
  yarn.lock
Labels: ⛑Type: Refactoring, 🙏Status: Code Review

#80 convert more tests
  src/components/inputs/number-input/number-input.spec.js
  src/components/inputs/password-input/password-input.spec.js
Labels: 👨‍⚕️ Type: Tests, 🙏Status: Code Review

#89 docs: fix travis link
  CONTRIBUTING.md
  README.md
Labels: ✍️Type: Documentation

#92 Fix id generation in NumberField and TextField
  src/components/fields/number-field/number-field.js
  src/components/fields/number-field/number-field.spec.js
  src/components/fields/text-field/README.md
  src/components/fields/text-field/text-field.form.story.js
  src/components/fields/text-field/text-field.js
  src/components/fields/text-field/text-field.spec.js
Labels: 🐛Type: Bug, 🙏Status: Dev Review

#95 feat: export WarningMessage
  src/index.js
Labels: :gift: Type: New Component

#96 docs: fix import paths in usage examples
  src/components/buttons/flat-button/README.md
  src/components/buttons/ghost-button/README.md
  src/components/buttons/icon-button/README.md
  src/components/buttons/link-button/README.md
  src/components/buttons/primary-button/README.md
  src/components/buttons/secondary-button/README.md
  src/components/buttons/secondary-icon-button/README.md
  src/components/constraints/horizontal/README.md
  src/components/dropdowns/primary-action-dropdown/README.md
  src/components/field-label/README.md
  src/components/fields/number-field/README.md
  src/components/fields/text-field/README.md
  src/components/icons/README.md
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-select-input/README.md
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/date-input/README.md
  src/components/inputs/date-time-input/README.md
  src/components/inputs/localized-multiline-text-input/README.md
  src/components/inputs/localized-text-input/README.md
  src/components/inputs/money-input/README.md
  src/components/inputs/multiline-text-input/README.md
  src/components/inputs/number-input/README.md
  src/components/inputs/password-input/README.md
  src/components/inputs/select-input/README.md
  src/components/inputs/text-input/README.md
  src/components/inputs/time-input/README.md
  src/components/label/README.md
  src/components/loading-spinner/README.md
  src/components/messages/error-message/README.md
  src/components/messages/warning-message/README.md
  src/components/panels/collapsible-panel/README.md
  src/components/spacings/inline/README.md
  src/components/spacings/inset-squish/README.md
  src/components/spacings/inset/README.md
  src/components/spacings/stack/README.md
  src/components/stamp/README.md
  src/components/switches/README.md
  src/components/switches/checkbox/README.md
  src/components/switches/radio/README.md
  src/components/switches/toggle/README.md
  src/components/table/README.md
  src/components/tag/README.md
  src/components/time-range-picker/README.md
  src/components/typography/text/README.md
  src/hocs/with-mouse-down-state/README.md
  src/hocs/with-mouse-over-state/README.md
Labels: ✍️Type: Documentation

#97 break: use touched instead of isTouched for all fields
  examples/form-fields.story.js
  src/components/fields/number-field/README.md
  src/components/fields/number-field/number-field.form.story.js
  src/components/fields/number-field/number-field.js
  src/components/fields/number-field/number-field.spec.js
  src/components/fields/number-field/number-field.story.js
  src/components/fields/text-field/README.md
  src/components/fields/text-field/text-field.form.story.js
  src/components/fields/text-field/text-field.js
  src/components/fields/text-field/text-field.spec.js
  src/components/fields/text-field/text-field.story.js
Labels: 💇‍♂️Type: Enhancement

#102 fix(money-input): add formatting workaround
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.story.js
Labels: 🐛Type: Bug

#105 docs: add translation flow to README
  README.md
Labels: ✍️Type: Documentation

#103 feat(money-field): add high-precision price badge
  i18n/core.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  src/components/fields/money-field/messages.js
  src/components/fields/money-field/money-field.form.story.js
  src/components/fields/money-field/money-field.js
  src/components/fields/money-field/money-field.spec.js
  src/components/fields/money-field/money-field.story.js
Labels: 👨‍🎨 Status: UI/UX Review, 💇‍♂️Type: Enhancement

#106 Add MultilineTextField
  examples/form-fields.story.js
  src/components/fields/multiline-text-field/README.md
  src/components/fields/multiline-text-field/index.js
  src/components/fields/multiline-text-field/multiline-text-field.form.story.js
  src/components/fields/multiline-text-field/multiline-text-field.js
  src/components/fields/multiline-text-field/multiline-text-field.spec.js
  src/components/fields/multiline-text-field/multiline-text-field.story.js
  src/index.js
Labels: :gift: Type: New Component, 👨‍🎨 Status: UI/UX Review, 🙏Status: Dev Review

#108 Fix lost updates of MoneyInput for Formik validation
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
Labels: 🐛Type: Bug, 🙏Status: Dev Review
