Repository commercetools/ui-kit, pull requests merged in 2018-10, with the labels that each got.

#69 Feature/primary action button
  materials/shadows/base-shadows.mod.css
  materials/shadows/decisions/base-shadows.json
  materials/tokens/backgrounds.mod.css
  materials/tokens/borders.mod.css
  materials/tokens/fonts.mod.css
  materials/tokens/shadows.mod.css
  materials/tokens/sizes.mod.css
  src/components/buttons/primary-action-button/README.md
  src/components/buttons/primary-action-button/index.js
  src/components/buttons/primary-action-button/primary-action-button.js
  src/components/buttons/primary-action-button/primary-action-button.mod.css
  src/components/buttons/primary-action-button/primary-action-button.spec.js
  src/components/buttons/primary-action-button/primary-action-button.story.js
  src/utils/filter-aria-attributes.js
  src/utils/filter-aria-attributes.spec.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#118 chore: kill mc-scripts dependency
  package.json
  scripts/extract-intl.js
  yarn.lock
Labels: 🔮Type: Chore, 🙏Status: Dev Review

#112 UI-KIT-37: Tags styling issue when dropdown isMulti
  materials/tokens/sizes.mod.css
  src/components/internals/select.css
  src/components/tag/tag.mod.css
Labels: ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review, 🙏Status: Dev Review

#123 renames all `Tag` tokens from plural to singular
  materials/tokens/backgrounds.mod.css
  materials/tokens/borders.mod.css
  materials/tokens/shadows.mod.css
  materials/tokens/sizes.mod.css
  src/components/internals/select.css
  src/components/tag/tag.mod.css
Labels: ⛑ Type: Refactoring, 🙏Status: Dev Review

#119 SelectInput: explicitly declare props
  src/components/inputs/select-input/README.md
  src/components/inputs/select-input/select-input.js
  src/components/inputs/select-input/select-input.story.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#120 AsyncSelectInput: explicitly declare props
  src/components/inputs/async-select-input/README.md
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/async-select-input/async-select-input.story.js
  src/components/inputs/select-input/select-input.story.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#121 CreatableSelectInput: explicitly declare props
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.story.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#122 AsyncCreatableSelectInput: explicitly declare props
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#114 Add SelectField
  examples/form-fields.story.js
  src/components/fields/select-field/README.md
  src/components/fields/select-field/index.js
  src/components/fields/select-field/select-field.form.story.js
  src/components/fields/select-field/select-field.js
  src/components/fields/select-field/select-field.spec.js
  src/components/fields/select-field/select-field.story.js
  src/components/inputs/select-input/select-input.js
  src/index.js
Labels: :gift: Type: New Component, 👨‍🎨 Status: UI/UX Review, 🙏Status: Dev Review

#124 adds `filterAriaAttributes` util
  src/utils/filter-aria-attributes.js
  src/utils/filter-aria-attributes.spec.js
Labels: 💇‍♂️Type: Enhancement, 🙏Status: Dev Review

#130 fix: avoid circular dependency
  src/components/fields/money-field/money-field.js
Labels: 🔮Type: Chore

#127 Add AsyncSelectField
  src/components/fields/async-select-field/README.md
  src/components/fields/async-select-field/async-select-field.form.story.js
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/async-select-field/async-select-field.spec.js
  src/components/fields/async-select-field/async-select-field.story.js
  src/components/fields/async-select-field/index.js
  src/components/inputs/async-select-input/README.md
  src/index.js
Labels: :gift: Type: New Component, 🙏Status: Dev Review

#129 Add AsyncCreatableSelectField
  src/components/fields/async-creatable-select-field/README.md
  src/components/fields/async-creatable-select-field/async-creatable-select-field.form.story.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.spec.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.story.js
  src/components/fields/async-creatable-select-field/index.js
  src/index.js
Labels: :gift: Type: New Component, 🙏Status: Dev Review

#131 fix: rename CreatableSelectField story
  src/components/fields/creatable-select-field/creatable-select-field.story.js
Labels: 💇‍♂️Type: Enhancement

#134 fix(bundling): add svg config for icons
  .storybook/webpack.config.js
  rollup.config.js
Labels: 🐛Type: Bug

#135 chore: update version, update changelog
  CHANGELOG.md
  package.json
Labels: 🔮Type: Chore

#137 Upgrade deps (drop reselect, drop MoneyInput workaround)
  package.json
  src/components/icons/icon.story.js
  src/components/inputs/money-input/money-input.js
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/panels/collapsible-panel/collapsible-panel.spec.js
  yarn.lock
Labels: 🔮Type: Chore, 🙏Status: Dev Review

#148 chore(deps): update husky, enzyme, svgr, browserslist, commitlint
  package.json
  yarn.lock
Labels: 🔮Type: Chore

#150 Release version 2.0.0-rc.10
  CHANGELOG.md
  package.json
Labels: 🔮Type: Chore

#154 fix: fix inline text
  src/components/typography/text/text.js
  src/components/typography/text/text.mod.css
  src/components/typography/text/text.spec.js
  src/components/typography/typography.story.js
Labels: 🐛 Type: Bug

#152 refactor: replace invariant with tiny-invariant
  package.json
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/icons/with-theme-prop.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/number-input/number-input.js
  src/components/panels/collapsible-panel/collapsible-panel.spec.js
  src/components/switches/checkbox/checkbox.spec.js
  src/components/switches/radio/radio-group.js
  src/components/switches/radio/radio-group.spec.js
  src/components/switches/radio/radio-option.spec.js
  src/utils/localized.js
  yarn.lock
Labels: 💅 Type: Enhancement

#155 chore: bump version to 2.0.0-rc.11, update changelog
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#141 Add badges
  README.md
Labels: ✍️ Type: Documentation, 👶 good first contribution

#156 feat: bundle small deps, explicitly peer dep others.
  package.json
  rollup.config.js
Labels: 💡 Type: Idea

#167 docs: add global locale knob
  .storybook/decorators/intl/intl.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.form.story.js
  src/components/fields/async-select-field/async-select-field.form.story.js
  src/components/fields/creatable-select-field/creatable-select-field.form.story.js
  src/components/fields/money-field/money-field.form.story.js
  src/components/fields/multiline-text-field/multiline-text-field.form.story.js
  src/components/fields/number-field/number-field.form.story.js
  src/components/fields/select-field/select-field.form.story.js
  src/components/fields/text-field/text-field.form.story.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.form.story.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js
  src/components/inputs/async-select-input/async-select-input.form.story.js
  src/components/inputs/async-select-input/async-select-input.story.js
  src/components/inputs/creatable-select-input/creatable-select-input.form.story.js
  src/components/inputs/creatable-select-input/creatable-select-input.story.js
  src/components/inputs/date-input/date-input.story.js
  src/components/inputs/date-time-input/date-time-input.story.js
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/number-input/number-input.form.story.js
  src/components/inputs/select-input/select-input.form.story.js
  src/components/inputs/select-input/select-input.story.js
  src/components/inputs/time-input/time-input.story.js
Labels: ✍️ Type: Documentation, 🙏 Status: Dev Review

#168 Use custom configuration (remove presets)
  .eslintrc.yaml
  .gitignore
  .storybook/webpack.config.js
  .travis.yml
  jest.test.config.js
  package.json
  rollup.config.js
  scripts/extract-intl.js
  scripts/get-babel-preset.js
  test/setup-tests.js
  test/transform-babel-jest.js
  test/transform-file.js
  yarn.lock
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#169 chore: specify React version for eslint-plugin-react
  .eslintrc.yaml
Labels: 🔮 Type: Chore

#173 feat(bundling): lower bundle size by discarding comments
  package.json
  rollup.config.js
  yarn.lock
Labels: 🏕 Technical Exploration

#174 Fix MoneyInput caret alignment & clickable area
  src/components/inputs/money-input/currency-dropdown.js
  src/components/inputs/money-input/dropdown-chevron.js
  src/components/inputs/money-input/money-input.mod.css
Labels: 🐛 Type: Bug

#176 Use postcss-custom-properties to import postcss variables
  .storybook/webpack.config.js
  rollup.config.js
  src/components/buttons/flat-button/flat-button.mod.css
  src/components/buttons/ghost-button/ghost-button.mod.css
  src/components/buttons/icon-button/icon-button.mod.css
  src/components/buttons/link-button/link-button.mod.css
  src/components/buttons/primary-button/primary-button.mod.css
  src/components/buttons/secondary-button/secondary-button.mod.css
  src/components/buttons/shared.mod.css
  src/components/constraints/horizontal/horizontal.mod.css
  src/components/dropdowns/primary-action-dropdown/primary-actions-dropdown.mod.css
  src/components/field-label/field-label.mod.css
  src/components/icons/icons.mod.css
  src/components/inputs/date-input/date-input.mod.css
  src/components/inputs/date-input/date-picker-body.mod.css
  src/components/inputs/date-input/date-picker-ct-theme.mod.css
  src/components/inputs/date-time-input/date-picker-body.mod.css
  src/components/inputs/date-time-input/date-picker-ct-theme.mod.css
  src/components/inputs/date-time-input/date-time-input.mod.css
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.mod.css
  src/components/inputs/localized-text-input/localized-text-input.mod.css
  src/components/inputs/money-input/money-input.mod.css
  src/components/inputs/multiline-text-input/multiline-text-input.mod.css
  src/components/inputs/number-input/number-input.mod.css
  src/components/inputs/password-input/password-input.mod.css
  src/components/inputs/text-input/text-input.mod.css
  src/components/inputs/time-input/date-picker-body.mod.css
  src/components/inputs/time-input/date-picker-ct-theme.mod.css
  src/components/inputs/time-input/time-input.mod.css
  src/components/internals/select.css
  src/components/label/required-indicator.mod.css
  src/components/loading-spinner/loading-spinner.mod.css
  src/components/panels/collapsible-panel/collapsible-panel.mod.css
  src/components/spacings/inline/inline.mod.css
  src/components/spacings/inset-squish/inset-squish.mod.css
  src/components/spacings/inset/inset.mod.css
  src/components/spacings/stack/stack.mod.css
  src/components/stamp/stamp.mod.css
  src/components/switches/checkbox/checkbox.mod.css
  src/components/switches/radio/radio-option.mod.css
  src/components/switches/toggle/toggle-bar.mod.css
  src/components/switches/toggle/toggle-button.mod.css
  src/components/switches/toggle/toggle.mod.css
  src/components/table/base-table/base-table.mod.css
  src/components/table/cell/cell.mod.css
  src/components/table/sortable-header/sortable-header.mod.css
  src/components/table/table.mod.css
  src/components/tag/tag.mod.css
  src/components/typography/text/text.mod.css
  yarn.lock
Labels: 🙏 Status: Dev Review

#175 Redo MoneyInput (better UX, less error cases)
  examples/form-fields.story.js
  examples/form-inputs.story.js
  src/components/fields/money-field/money-field.form.story.js
  src/components/fields/money-field/money-field.js
  src/components/fields/money-field/money-field.spec.js
  src/components/inputs/money-input/README.md
  src/components/inputs/money-input/currency-dropdown.js
  src/components/inputs/money-input/currency.spec.js
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
  src/components/inputs/money-input/money-input.story.js
Labels: Semver: BREAKING, 👨‍🎨 Status: UI/UX Review, 🙏 Status: Dev Review

#178 Add optional MoneyField example
  src/components/fields/money-field/money-field.form.story.js
Labels: Semver: UNRELATED, ✍️ Type: Documentation

#179 Drop styled-components peerDep (Redo CollapsibleMotion)
  package.json
  scripts/get-babel-preset.js
  src/components/collapsible-motion/README.md
  src/components/collapsible-motion/collapsible-motion.js
  src/components/collapsible-motion/collapsible-motion.spec.js
  src/components/collapsible-motion/collapsible-motion.story.js
  yarn.lock
Labels: 💅 Type: Enhancement, 🔮 Type: Chore, 🙏 Status: Dev Review

#181 feat: extract css variables to js and css files
  .storybook/config.js
  .storybook/webpack.config.js
  README.md
  materials/custom-properties.css
  materials/custom-properties.json
  materials/internals/borders.mod.css
  materials/internals/colors/base-colors.mod.css
  materials/internals/colors/colors-for-story.mod.css
  materials/internals/colors/colors.story.js
  materials/internals/colors/decisions/base-colors.json
  materials/internals/grid.mod.css
  materials/internals/index.css
  materials/internals/reset.mod.css
  materials/internals/shadows/base-shadows.mod.css
  materials/internals/shadows/decisions/base-shadows.json
  materials/internals/shadows/shadows.story.js
  materials/internals/sizes.mod.css
  materials/internals/spacings.mod.css
  materials/internals/tokens/README.md
  materials/internals/tokens/backgrounds.mod.css
  materials/internals/tokens/borders.mod.css
  materials/internals/tokens/fonts.mod.css
  materials/internals/tokens/shadows.mod.css
  materials/internals/tokens/sizes.mod.css
  materials/internals/tokens/tokens.mod.css
  materials/internals/transitions.mod.css
  package.json
  rollup.config.js
  scripts/extract-materials.js
  scripts/generate-base-colors.js
  scripts/generate-base-shadows.js
  scripts/generate-colors-for-story.js
  src/index.js
  yarn.lock
Labels: Semver: BREAKING, 🔮 Type: Chore

#172 chore: improve linters config
  .prettierignore
  jest.eslint.config.js
  jest.stylelint.config.js
  lint-staged.config.js
  package.json
  src/components/internals/select.css
  src/components/tag/tag.mod.css
  yarn.lock
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#182 refactor(*-select-input): use JS-based design tokens
  .storybook/webpack.config.js
  rollup.config.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/create-select-styles.js
  src/components/internals/select.css
  src/index.js
Labels: Semver: BREAKING, ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review

#183 Rebuild MoneyInput on top of react-select
  package.json
  src/components/inputs/money-input/currency-dropdown.js
  src/components/inputs/money-input/currency.js
  src/components/inputs/money-input/currency.spec.js
  src/components/inputs/money-input/dropdown-chevron.js
  src/components/inputs/money-input/dropdown-chevron.spec.js
  src/components/inputs/money-input/messages.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.mod.css
  src/components/inputs/money-input/money-input.spec.js
  src/components/inputs/money-input/option.js
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review, 💅 Type: Enhancement

#186 chore: self contain styles intermediate solution
  .storybook/config.js
  src/index.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#188 fix: import vars correctly
  src/components/inputs/money-input/money-input.js
  src/components/internals/create-select-styles.js
Labels: Semver: FIX

#189 fix: allow scrolling in icon story
  materials/internals/reset.mod.css
Labels: Semver: FIX, 🐛 Type: Bug

#190 fix(*-select-input): align indicator icons of clearable select-inputs
  src/components/internals/clear-indicator/clear-indicator.js
  src/components/internals/create-select-styles.js
  src/components/internals/dropdown-indicator/dropdown-indicator.js
Labels: 👹 Type: Design Issue

#193 Add build:watch script
  package.json
Labels: 🔮 Type: Chore

#192 Add playground
  package.json
  playground/.babelrc
  playground/.eslintrc.yaml
  playground/README.md
  playground/src/index.js
  playground/src/playground.js
  playground/webpack.config.js
  yarn.lock
Labels: Semver: UNRELATED, 💡 Type: Idea, 🔮 Type: Chore

#194 Add bundle tests setup
  .eslintrc.yaml
  .travis.yml
  jest.bundle.config.js
  package.json
  src/index.bundlespec.js
  test/replace-module-paths.js
  test/transform-babel-jest.js
  yarn.lock
Labels: Semver: UNRELATED, 👨‍⚕️ Type: Tests, 👨‍👩‍👦‍👦 Status: Dev Review

#191 feat(typography): add `title` prop to all typography components
  src/components/typography/text/README.md
  src/components/typography/text/text.js
  src/components/typography/text/text.spec.js
  src/components/typography/typography.story.js
Labels: Semver: FEATURE, 👨‍🎨 Status: UI/UX Review, 💅 Type: Enhancement

#203 Add prop to trigger hovered state of `Radio.Option` and `Checkbox`
  src/components/switches/checkbox/README.md
  src/components/switches/checkbox/checkbox.js
  src/components/switches/checkbox/checkbox.mod.css
  src/components/switches/checkbox/checkbox.spec.js
  src/components/switches/checkbox/checkbox.story.js
  src/components/switches/radio/README.md
  src/components/switches/radio/radio-option.js
  src/components/switches/radio/radio-option.mod.css
  src/components/switches/radio/radio-option.spec.js
  src/components/switches/radio/radio.story.js
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement
