Repository commercetools/ui-kit, pull requests merged in 2018-11, with the labels that each got.

#206 Money Input Fixes
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.mod.css
  src/components/inputs/money-input/money-input.spec.js
Labels: 🐛 Type: Bug

#218 fix: remove root from media queries
  materials/media-queries.mod.css
Labels: 🔮 Type: Chore

#219 chore: fixup docs
  README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore

#228 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#221 feat: add MoneyInput value formatting
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
  src/test-utils.js
Labels: Semver: BREAKING, 💅 Type: Enhancement

#229 fix(money-input): avoid rounding errors
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
Labels: Semver: FIX, 💅 Type: Enhancement

#230 Remove images
  README.md
  images/chevron-down.png
  images/ct-logo.svg
  images/ct_logo_bw.svg
  images/ct_logo_bw_white.svg
  images/discounts/cart-discount.svg
  images/discounts/cart-predicate-info.svg
  images/discounts/discount-code.svg
  images/discounts/product-discount.svg
  images/logo.svg
  images/maintenance/failed-authentication.svg
  images/maintenance/failed-authorization.svg
  images/maintenance/page-not-found.svg
  images/maintenance/project-expired.svg
  images/maintenance/project-suspended.svg
  images/maintenance/unexpected-error.svg
  images/order_images/fly.svg
  images/product_images/image__broken.svg
  images/product_images/image__missing_image.svg
  images/product_images/image__no-image.svg
  images/product_images/link-external__broken.svg
  images/product_images/link-external__working.svg
  images/radio-check-icons.png
Labels: Semver: BREAKING

#236 chore: stop excluding src/index.js from prettier
  .prettierignore
  src/index.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#232 feat(notifications/static): add ContentNotification component
  src/components/notifications/content-notification/README.md
  src/components/notifications/content-notification/content-notification.js
  src/components/notifications/content-notification/content-notification.mod.css
  src/components/notifications/content-notification/content-notification.spec.js
  src/components/notifications/content-notification/content-notification.story.js
  src/components/notifications/content-notification/index.js
  src/index.js
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review

#241 chore: upgrade dependencies
  examples/form-inputs.story.js
  package.json
  scripts/extract-intl.js
  scripts/generate-base-colors.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.form.story.js
  src/components/inputs/async-select-input/async-select-input.form.story.js
  src/components/inputs/creatable-select-input/creatable-select-input.form.story.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/select-input/select-input.form.story.js
  src/components/inputs/select-input/select-input.js
  yarn.lock
Labels: 🔮 Type: Chore

#243 feat: add <ConnectorIcon>
  src/components/icons/index.js
  src/components/icons/svg/connector.react.svg
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review

#242 Adds <Avatar> component
  src/components/avatar/README.md
  src/components/avatar/avatar.js
  src/components/avatar/avatar.mod.css
  src/components/avatar/avatar.spec.js
  src/components/avatar/avatar.story.js
  src/components/avatar/index.js
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review

#261 chore(storybook): fix page title and favicon
  .storybook/config.js
  .storybook/manager-head.html
  docs/assets/favicon.ico
  package.json
Labels: Semver: UNRELATED, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#262 refactor(icons): invalid names
  package.json
  src/components/icons/index.js
  src/components/icons/svg/angle-thin-left.react.svg
  src/components/icons/svg/angle-thin-right.react.svg
  src/components/icons/svg/arrow-down.react.svg
  src/components/icons/svg/arrow-graph-left.react.svg
  src/components/icons/svg/arrow-graph-right.react.svg
  src/components/icons/svg/arrow-left.react.svg
  src/components/icons/svg/arrow-right.react.svg
  src/components/icons/svg/arrow-up.react.svg
  src/components/icons/svg/bidirectional-arrow.react.svg
  src/components/icons/svg/box-product.react.svg
  src/components/icons/svg/box.react.svg
  src/components/icons/svg/connected-square.react.svg
  src/components/icons/svg/connected-triangle.react.svg
  src/components/icons/svg/cube.react.svg
  src/components/icons/svg/dot.react.svg
  src/components/icons/svg/gear.react.svg
  src/components/icons/svg/heart.react.svg
  src/components/icons/svg/paper-bill-inverted.react.svg
  src/components/icons/svg/paperclip.react.svg
  src/components/icons/svg/review.react.svg
  src/components/icons/svg/rocket.react.svg
  src/components/icons/svg/screen-gear.react.svg
  src/components/icons/svg/screen-user.react.svg
  src/components/icons/svg/star.react.svg
  src/components/icons/svg/tag-stacked.react.svg
  src/components/icons/svg/tree-structure.react.svg
  src/components/icons/svg/truck.react.svg
  src/components/icons/svg/user-filled.react.svg
  src/components/icons/svg/user-linear.react.svg
Labels: Semver: FIX, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#258 chore: upgrade dependencies
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#265 fix(storybook): set title (remove semi colon error)
  .storybook/manager-head.html
Labels: 👨‍👩‍👦‍👦 Status: Dev Review

#266 fix: media queries
  materials/media-queries.mod.css
Labels: Semver: FIX, 🐛 Type: Bug

#267 Add percy
  .eslintrc.yaml
  .gitignore
  .travis.yml
  package.json
  percy.config.js
  src/components/buttons/flat-button/flat-button.percy.js
  src/components/inputs/text-input/text-input.percy.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#268 chore: add avatar export
  src/index.js
Labels: Semver: FIX

#270 Remove `Icons.AX` export
  src/index.js
Labels: Semver: BREAKING, 👨‍👩‍👦‍👦 Status: Dev Review
