Repository commercetools/ui-kit, pull requests merged in 2019-01, with the labels that each got.

#380 chore: fix storybook
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🐛 Type: Bug

#381 chore: improve vrt app and add table vrt test
  scripts/run-percy.sh
  src/components/table/table.visualroute.js
  src/components/table/table.visualspec.js
  visual-testing-app/index.html
  visual-testing-app/server.js
  visual-testing-app/webpack.config.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#389 Reorganise props of multiline and localized inputs and fields
  src/components/fields/localized-multiline-text-field/README.md
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.spec.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.story.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.visualroute.js
  src/components/fields/localized-text-field/README.md
  src/components/fields/localized-text-field/localized-text-field.js
  src/components/fields/localized-text-field/localized-text-field.spec.js
  src/components/fields/localized-text-field/localized-text-field.story.js
  src/components/fields/localized-text-field/localized-text-field.visualroute.js
  src/components/fields/multiline-text-field/README.md
  src/components/fields/multiline-text-field/multiline-text-field.js
  src/components/fields/multiline-text-field/multiline-text-field.story.js
  src/components/fields/multiline-text-field/multiline-text-field.visualroute.js
  src/components/inputs/localized-multiline-text-input/README.md
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.spec.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.story.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js
  src/components/inputs/localized-text-input/README.md
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.spec.js
  src/components/inputs/localized-text-input/localized-text-input.story.js
  src/components/inputs/localized-text-input/localized-text-input.visualroute.js
  src/components/inputs/multiline-text-input/README.md
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/components/inputs/multiline-text-input/multiline-text-input.story.js
  src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js
Labels: Semver: BREAKING, 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement

#388 Add inputs and fields philosophy
  philosophy/FIELDS.md
  philosophy/INPUTS.md
  philosophy/guide.story.js
Labels: Semver: UNRELATED, ✍️ Type: Documentation

#339 Add LocalizedMoneyInput Component
  i18n/core.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  src/components/inputs/localized-money-input/README.md
  src/components/inputs/localized-money-input/currency-control.js
  src/components/inputs/localized-money-input/index.js
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.mod.css
  src/components/inputs/localized-money-input/localized-money-input.percy.visualroute.js
  src/components/inputs/localized-money-input/localized-money-input.percy.visualspec.js
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  src/components/inputs/localized-money-input/localized-money-input.story.js
  src/components/inputs/localized-money-input/messages.js
  src/components/inputs/money-input/money-input.mod.css
  src/index.js
Labels: 👨‍🎨 Status: UI/UX Review, 👨‍👩‍👦‍👦 Status: Dev Review

#401 chore(collapsible-panel): move onClick in header
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/panels/collapsible-panel/collapsible-panel.spec.js
Labels: Semver: FIX, 🔮 Type: Chore

#403 docs(storybook): fix PrimaryActionDropdown story
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.story.js
Labels: Semver: UNRELATED

#406 fix(date-inputs): make date-input have large z-index
  src/components/internals/calendar-menu/calendar-menu.mod.css
Labels: Semver: FIX, 🔮 Type: Chore

#390 docs(changelog): for release v6.0.0
  CHANGELOG.md
Labels: ✍️ Type: Documentation

#409 feat(icons): add eye-crossed icon 👁
  src/components/icons/index.js
  src/components/icons/svg/eye-crossed.react.svg
Labels: Semver: FEATURE, ✨ Type: New Component, 👨‍👩‍👦‍👦 Status: Dev Review

#408 fix(primary-action-dropdown): use secondary tone when disabled
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/dropdowns/primary-action-dropdown/primary-actions-dropdown.mod.css
Labels: Semver: FIX, 💅 Type: Enhancement

#410 Change caret size in select inputs and MoneyInput
  src/components/inputs/money-input/money-input.js
  src/components/internals/clear-indicator/clear-indicator.js
  src/components/internals/create-select-styles.js
  src/components/internals/dropdown-indicator/dropdown-indicator.js
Labels: Semver: FIX

#411 fix(money-input): use narrow styling when no currencies are passed
  src/components/inputs/money-input/money-input.mod.css
Labels: Semver: FIX, 💅 Type: Enhancement

#414 fix(text): add missing inverted prop to prop-types of text-detail
  src/components/typography/text/text.js
Labels: Semver: FIX

#415 chore: update changelog and bump package.json
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore

#412 chore(storybook): render ui-kit readme as getting started page
  .storybook/config.js
  .storybook/welcome.story.js
Labels: Semver: UNRELATED, ✍️ Type: Documentation, 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement

#413 chore: rename localized-money-input specs and use pptr
  src/components/inputs/localized-money-input/localized-money-input.visualroute.js
  src/components/inputs/localized-money-input/localized-money-input.visualspec.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#416 chore: update proptype of Radio
  src/components/switches/radio/radio-group.js
  src/components/switches/radio/radio-option.js
Labels: Semver: FIX

#418 chore: bump package.json and update changelog
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#421 feat(CollapsiblePanel): add `hideExpansionControls` (not hidden by default)
  src/components/panels/collapsible-panel/README.md
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/panels/collapsible-panel/collapsible-panel.mod.css
  src/components/panels/collapsible-panel/collapsible-panel.story.js
  src/components/panels/collapsible-panel/collapsible-panel.visualroute.js
  src/components/panels/collapsible-panel/header-icon.js
Labels: Semver: FEATURE, 👨‍🎨 Status: UI/UX Review

#422 fix(money-field): remove required `currencies` prop from
  src/components/fields/localized-text-field/localized-text-field.js
  src/components/fields/money-field/money-field.js
Labels: Semver: FIX

#423 fix(radio-option, checkbox, switch): move data-attributes to input
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.spec.js
  src/components/inputs/async-select-input/async-select-input.spec.js
  src/components/inputs/creatable-select-input/creatable-select-input.spec.js
  src/components/inputs/date-range-input/date-range-input.js
  src/components/inputs/date-time-input/date-time-input.js
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  src/components/inputs/select-input/select-input.spec.js
  src/components/inputs/time-input/time-input-body.js
  src/components/internals/calendar-body/calendar-body.js
  src/components/internals/calendar-menu/calendar-menu.js
  src/components/switches/checkbox/checkbox.js
  src/components/switches/radio/radio-option.js
  src/components/switches/toggle/toggle.js
Labels: Semver: FIX

#424 fix(error-message): support data-attributes
  src/components/messages/error-message/error-message.js
  src/components/messages/error-message/error-message.spec.js
Labels: Semver: FIX

#426 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#427 fix(time-input): call onChange with generated ID if none passed
  src/components/inputs/time-input/time-input.js
  src/components/inputs/time-input/time-input.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#419 fix(localizedmoneyinput): remove 'amount/currencyCode' from event name
  src/components/inputs/localized-money-input/README.md
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  src/components/inputs/localized-money-input/localized-money-input.story.js
  src/components/inputs/localized-money-input/localized-money-input.visualroute.js
Labels: Semver: BREAKING, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#431 Fix proptypes
  src/components/avatar/README.md
  src/components/buttons/accessible-button/README.md
  src/components/buttons/flat-button/README.md
  src/components/buttons/icon-button/README.md
  src/components/buttons/link-button/README.md
  src/components/buttons/primary-button/README.md
  src/components/buttons/secondary-button/README.md
  src/components/buttons/secondary-icon-button/README.md
  src/components/constraints/horizontal/README.md
  src/components/dropdowns/primary-action-dropdown/README.md
  src/components/field-label/README.md
  src/components/fields/async-creatable-select-field/README.md
  src/components/fields/async-select-field/README.md
  src/components/fields/creatable-select-field/README.md
  src/components/fields/date-field/README.md
  src/components/fields/date-range-field/README.md
  src/components/fields/date-time-field/README.md
  src/components/fields/localized-multiline-text-field/README.md
  src/components/fields/localized-text-field/README.md
  src/components/fields/money-field/README.md
  src/components/fields/multiline-text-field/README.md
  src/components/fields/number-field/README.md
  src/components/fields/password-field/README.md
  src/components/fields/select-field/README.md
  src/components/fields/text-field/README.md
  src/components/fields/time-field/README.md
  src/components/inputs/date-input/README.md
  src/components/inputs/date-range-input/README.md
  src/components/inputs/date-time-input/README.md
  src/components/inputs/localized-money-input/README.md
  src/components/inputs/localized-multiline-text-input/README.md
  src/components/inputs/localized-text-input/README.md
  src/components/inputs/money-input/README.md
  src/components/inputs/multiline-text-input/README.md
  src/components/inputs/number-input/README.md
  src/components/inputs/password-input/README.md
  src/components/inputs/text-input/README.md
  src/components/label/README.md
  src/components/loading-spinner/README.md
  src/components/notifications/content-notification/README.md
  src/components/panels/collapsible-panel/README.md
  src/components/tag/README.md
Labels: ✍️ Type: Documentation

#432 Update dependencies
  package.json
  src/components/icons/icon.story.js
  yarn.lock
Labels: 🔮 Type: Chore

#404 chore: adds a few interaction based VRT tests
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualroute.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualspec.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.visualroute.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.visualspec.js
  src/components/fields/async-select-field/async-select-field.visualroute.js
  src/components/fields/async-select-field/async-select-field.visualspec.js
Labels: 👨‍⚕️ Type: Tests, 👨‍👩‍👦‍👦 Status: Dev Review

#434 chore: have ci run lint
  .eslintrc.yaml
  .travis.yml
Labels: Semver: UNRELATED, 🔮 Type: Chore

#438 chore: update vrt tests for icons
  src/components/icons/icons.visualroute.js
  src/components/icons/icons.visualspec.js
Labels: Semver: UNRELATED, 👨‍⚕️ Type: Tests, 🔮 Type: Chore

#435 chore(icons): renames icons
  src/components/buttons/flat-button/__snapshots__/flat-button.spec.js.snap
  src/components/buttons/flat-button/flat-button.spec.js
  src/components/buttons/link-button/__snapshots__/link-button.spec.js.snap
  src/components/buttons/link-button/link-button.spec.js
  src/components/buttons/primary-button/primary-button.spec.js
  src/components/dropdowns/primary-action-dropdown/README.md
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualroute.js
  src/components/icons/index.js
  src/components/icons/svg/bin-filled.react.svg
  src/components/icons/svg/bin-linear.react.svg
  src/components/icons/svg/check-bold.react.svg
  src/components/icons/svg/check-thin.react.svg
  src/components/icons/svg/flag-filled.react.svg
  src/components/icons/svg/flag-linear.react.svg
  src/components/icons/svg/pin-filled.react.svg
  src/components/icons/svg/pin-linear.react.svg
  src/components/icons/svg/plus-bold.react.svg
  src/components/icons/svg/plus-thin.react.svg
  src/components/notifications/content-notification/content-notification.js
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#441 Removes playground
  package.json
  playground/.babelrc
  playground/.eslintrc.yaml
  playground/README.md
  playground/index.template.html
  playground/src/index.js
  playground/src/playground.css
  playground/src/playground.js
  playground/webpack.config.js
  visual-testing-app/webpack.config.js
Labels: Semver: UNRELATED

#439 Add VRTs to SelectInputs
  src/components/inputs/async-creatable-select-input/async-creatable-select-input-open.visualroute.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.visualspec.js
  src/components/inputs/async-select-input/async-select-input-open.visualroute.js
  src/components/inputs/async-select-input/async-select-input.visualspec.js
  src/components/inputs/creatable-select-input/creatable-select-input-open.visualroute.js
  src/components/inputs/creatable-select-input/creatable-select-input.visualspec.js
  src/components/inputs/select-input/select-input-open.visualroute.js
  src/components/inputs/select-input/select-input.visualspec.js
Labels: 👨‍⚕️ Type: Tests

#444 chore: remove unused stuff
  .storybook/webpack.config.js
  package.json
  rollup.config.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#442 feat: add Grid component
  .storybook/config.js
  .storybook/decorators/section/section.js
  examples/form-fields.example.story.js
  examples/form-inputs.example.story.js
  src/components/grid/README.md
  src/components/grid/grid.example.story.js
  src/components/grid/grid.js
  src/components/grid/grid.spec.js
  src/components/grid/grid.story.js
  src/components/grid/grid.visualroute.js
  src/components/grid/grid.visualspec.js
  src/components/grid/index.js
  src/components/inputs/radio-input/radio-group.js
  src/index.js
Labels: Semver: UNRELATED, 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#446 fix(money-input): avoid messing with floating point numbers
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#448 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#451 chore: update changelog for version 7.0.0
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore

#453 Remove some experimental babel features
  .eslintrc.yaml
  examples/form-inputs.example.story.js
  package.json
  scripts/get-babel-preset.js
  src/components/avatar/avatar.js
  src/components/collapsible-motion/collapsible-motion.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/date-field/date-field.js
  src/components/fields/date-range-field/date-range-field.js
  src/components/fields/date-time-field/date-time-field.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js
  src/components/fields/localized-text-field/localized-text-field.js
  src/components/fields/money-field/money-field.js
  src/components/fields/multiline-text-field/multiline-text-field.js
  src/components/fields/number-field/number-field.js
  src/components/fields/password-field/password-field.js
  src/components/fields/select-field/select-field.js
  src/components/fields/text-field/text-field.js
  src/components/fields/time-field/time-field.js
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/date-input/date-input.js
  src/components/inputs/date-range-input/date-range-input.js
  src/components/inputs/date-time-input/date-time-input.js
  src/components/inputs/localized-money-input/README.md
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/time-input/time-input.js
  src/components/internals/calendar-day/calendar-day.js
  src/components/internals/create-select-styles.js
  src/components/notifications/content-notification/content-notification.js
  src/components/panels/collapsible-panel/header-icon.js
  src/utils/get-field-id.js
  src/utils/parse-time.js
  yarn.lock
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#445 refactor: use `emotion` to style typographical components 💅
  .babelrc
  package.json
  scripts/get-babel-preset.js
  src/components/buttons/flat-button/__snapshots__/flat-button.spec.js.snap
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/link-button/__snapshots__/link-button.spec.js.snap
  src/components/buttons/link-button/link-button.js
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/radio-input/radio-option.js
  src/components/internals/calendar-header/calendar-header.js
  src/components/spacings/inline/inline.js
  src/components/spacings/inline/inline.mod.css
  src/components/spacings/inline/inline.styles.js
  src/components/spacings/inset-squish/inset-squish.js
  src/components/spacings/inset-squish/inset-squish.mod.css
  src/components/spacings/inset/inset.js
  src/components/spacings/inset/inset.mod.css
  src/components/spacings/stack/stack.js
  src/components/spacings/stack/stack.mod.css
  src/components/spacings/stack/stack.styles.js
  src/components/typography/text/text.js
  src/components/typography/text/text.mod.css
  src/components/typography/text/text.styles.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#455 refactor(avatar): to use emotion styles
  src/components/avatar/avatar.js
  src/components/avatar/avatar.mod.css
Labels: ⛑ Type: Refactoring, 👨‍👩‍👦‍👦 Status: Dev Review

#458 Refactor `Stamp` to use emotion
  .prettierrc
  src/components/stamp/stamp.js
  src/components/stamp/stamp.mod.css
Labels: Semver: UNRELATED, ⛑ Type: Refactoring

#460 chore(scripts/custom-properties): generate js version
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  package.json
  scripts/generate-custom-properties.js
  src/components/avatar/avatar.js
  src/components/spacings/inline/inline.styles.js
  src/components/spacings/inset-squish/inset-squish.js
  src/components/spacings/inset/inset.js
  src/components/spacings/stack/stack.styles.js
  src/components/stamp/stamp.js
  src/components/typography/text/text.styles.js
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement

#463 refactor: to import custom props as js object
  README.md
  materials/internals/definition.yaml
  package.json
  src/components/grid/grid.example.story.js
  src/components/inputs/money-input/money-input.js
  src/components/internals/create-select-styles.js
  src/index.js
  test/percy/spec.js
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#462 refactor(content-notification): use emotion
  src/components/notifications/content-notification/content-notification.js
  src/components/notifications/content-notification/content-notification.mod.css
Labels: Semver: UNRELATED, ⛑ Type: Refactoring

#459 refactor(buttons): to use emotion styles
  package.json
  src/components/buttons/accessible-button/README.md
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/accessible-button/accessible-button.mod.css
  src/components/buttons/accessible-button/accessible-button.spec.js
  src/components/buttons/flat-button/__snapshots__/flat-button.spec.js.snap
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.mod.css
  src/components/buttons/flat-button/flat-button.spec.js
  src/components/buttons/icon-button/__snapshots__/icon-button.spec.js.snap
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.mod.css
  src/components/buttons/icon-button/icon-button.spec.js
  src/components/buttons/icon-button/icon-button.styles.js
  src/components/buttons/link-button/__snapshots__/link-button.spec.js.snap
  src/components/buttons/link-button/link-button.js
  src/components/buttons/link-button/link-button.mod.css
  src/components/buttons/link-button/link-button.spec.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/primary-button/primary-button.mod.css
  src/components/buttons/primary-button/primary-button.spec.js
  src/components/buttons/primary-button/primary-button.story.js
  src/components/buttons/primary-button/primary-button.styles.js
  src/components/buttons/primary-button/primary-button.visualroute.js
  src/components/buttons/secondary-button/__snapshots__/secondary-button.spec.js.snap
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-button/secondary-button.mod.css
  src/components/buttons/secondary-button/secondary-button.spec.js
  src/components/buttons/secondary-button/secondary-button.styles.js
  src/components/buttons/secondary-icon-button/__snapshots__/secondary-icon-button.spec.js.snap
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.mod.css
  src/components/buttons/secondary-icon-button/secondary-icon-button.spec.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.story.js
  src/components/buttons/shared.mod.css
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.story.js
  src/components/dropdowns/primary-action-dropdown/primary-actions-dropdown.mod.css
  src/components/tag/tag.js
  src/components/tag/tag.mod.css
  src/components/tag/tag.visualroute.js
Labels: ⛑ Type: Refactoring, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#465 refactor(constraints): to use emotion styles
  src/components/constraints/horizontal/horizontal.js
  src/components/constraints/horizontal/horizontal.mod.css
Labels: ⛑ Type: Refactoring

#468 refactor(icons): to use emotion styles
  scripts/generate-icon-exports.js
  src/components/icons/create-styled-icon.js
  src/components/icons/icons.mod.css
  src/components/icons/index.js
  src/components/icons/svg/revert.react.svg
  src/components/icons/with-size-prop.js
  src/components/icons/with-theme-prop.js
  src/components/internals/dropdown-indicator/dropdown-indicator.js
Labels: ⛑ Type: Refactoring

#466 refactor(field-label): to use emotion styles
  src/components/field-label/field-label.js
  src/components/field-label/field-label.mod.css
Labels: ⛑ Type: Refactoring

#472 Migrate `CollapsiblePanel` to use emotion
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/panels/collapsible-panel/collapsible-panel.mod.css
  src/components/panels/collapsible-panel/collapsible-panel.styles.js
  src/components/panels/collapsible-panel/header-icon.js
Labels: ⛑ Type: Refactoring

#475 Refactor to remove `recompose`
  package.json
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/hocs/with-mouse-down-state/with-mouse-down-state.js
  src/hocs/with-mouse-over-state/with-mouse-over-state.js
  src/hocs/wrap-display-name/index.js
  src/hocs/wrap-display-name/wrap-display-name.js
  src/hocs/wrap-display-name/wrap-display-name.spec.js
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 👨‍👩‍👦‍👦 Status: Dev Review

#474 chore: migirate loading spinner to emotion
  src/components/loading-spinner/loading-spinner.js
  src/components/loading-spinner/loading-spinner.mod.css
Labels: ⛑ Type: Refactoring

#470 Migrate `Tag` to emotion
  src/components/tag/tag.js
  src/components/tag/tag.mod.css
Labels: Semver: UNRELATED, ⛑ Type: Refactoring

#476 refactor(label): to use emotion styles
  src/components/label/required-indicator.js
  src/components/label/required-indicator.mod.css
Labels: ⛑ Type: Refactoring

#473 refactor(inputs): to use emotion styles
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox-input.mod.css
  src/components/inputs/checkbox-input/checkbox-input.styles.js
  src/components/inputs/date-input/date-input.js
  src/components/inputs/date-range-input/date-range-input.js
  src/components/inputs/date-time-input/date-time-input.js
  src/components/inputs/date-time-input/time-input.js
  src/components/inputs/date-time-input/time-input.mod.css
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.mod.css
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.mod.css
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-multiline-text-input/translation-input.styles.js
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.mod.css
  src/components/inputs/localized-text-input/localized-text-input.styles.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.mod.css
  src/components/inputs/money-input/money-input.styles.js
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/components/inputs/multiline-text-input/multiline-text-input.mod.css
  src/components/inputs/multiline-text-input/multiline-text-input.styles.js
  src/components/inputs/number-input/number-input.js
  src/components/inputs/number-input/number-input.mod.css
  src/components/inputs/number-input/number-input.spec.js
  src/components/inputs/password-input/password-input.js
  src/components/inputs/password-input/password-input.mod.css
  src/components/inputs/password-input/password-input.spec.js
  src/components/inputs/radio-input/radio-option.js
  src/components/inputs/radio-input/radio-option.mod.css
  src/components/inputs/radio-input/radio-option.styles.js
  src/components/inputs/styles.js
  src/components/inputs/text-input/text-input.js
  src/components/inputs/text-input/text-input.mod.css
  src/components/inputs/text-input/text-input.spec.js
  src/components/inputs/time-input/time-input-body.js
  src/components/inputs/time-input/time-input-body.mod.css
  src/components/inputs/time-input/time-input-body.styles.js
  src/components/inputs/time-input/time-input.spec.js
  src/components/inputs/toggle-input/toggle-bar.mod.css
  src/components/inputs/toggle-input/toggle-button.mod.css
  src/components/inputs/toggle-input/toggle-input.js
  src/components/inputs/toggle-input/toggle-input.mod.css
  src/components/inputs/toggle-input/toggle-input.styles.js
  src/components/inputs/toggle-input/toggle-switch.js
  src/components/internals/calendar-body/calendar-body.js
  src/components/internals/calendar-body/calendar-body.mod.css
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/calendar-calendar/calendar-calendar.js
  src/components/internals/calendar-calendar/calendar-calendar.mod.css
  src/components/internals/calendar-calendar/index.js
  src/components/internals/calendar-content/calendar-content.js
  src/components/internals/calendar-content/index.js
  src/components/internals/calendar-day/calendar-day.js
  src/components/internals/calendar-day/calendar-day.mod.css
  src/components/internals/calendar-header/calendar-header.js
  src/components/internals/calendar-header/calendar-header.mod.css
  src/components/internals/calendar-menu/calendar-menu.js
  src/components/internals/calendar-menu/calendar-menu.mod.css
Labels: ⛑ Type: Refactoring

#478 refactor(table): to use emotion styles
  src/components/table/base-table/base-table.js
  src/components/table/base-table/base-table.mod.css
  src/components/table/base-table/base-table.spec.js
  src/components/table/cell/cell.js
  src/components/table/cell/cell.mod.css
  src/components/table/sortable-header/sortable-header.js
  src/components/table/sortable-header/sortable-header.mod.css
  src/components/table/table.js
  src/components/table/table.mod.css
  src/components/table/table.spec.js
  src/components/table/table.story.js
Labels: ⛑ Type: Refactoring

#480 chore: drop postcss plugins 🎉
  .storybook/config.js
  .storybook/main.mod.css
  .storybook/preview-head.html
  .storybook/webpack.config.js
  .stylelintrc
  .travis.yml
  jest.stylelint.config.js
  package.json
  rollup.config.js
  src/components/table/table.story.js
  visual-testing-app/index.html
  visual-testing-app/src/App.css
  visual-testing-app/src/App.js
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: 🔮 Type: Chore

#481 [BREAKING] remove media queries
  materials/media-queries.mod.css
  package.json
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#490 Update deps
  materials/internals/tokens.story.js
  package.json
  src/components/table/table.story.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#492 refactor(package.json): to simplify semver ranges for peer deps
  package.json
Labels: ⛑ Type: Refactoring

#493 docs(changelog): for release v8.0.0 [skip ci]
  CHANGELOG.md
  package.json
Labels: ✍️ Type: Documentation

#494 Adds `Card` Component
  materials/custom-properties.js
  src/components/card/README.md
  src/components/card/card.js
  src/components/card/card.spec.js
  src/components/card/card.story.js
  src/components/card/card.visualroute.js
  src/components/card/card.visualspec.js
  src/components/card/index.js
  src/index.js
Labels: Semver: FEATURE, ✨ Type: New Component

#496 chore: support aria attributes on buttons
  src/components/buttons/flat-button/README.md
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.spec.js
  src/components/buttons/icon-button/README.md
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.spec.js
  src/components/buttons/link-button/README.md
  src/components/buttons/link-button/link-button.js
  src/components/buttons/link-button/link-button.spec.js
  src/components/buttons/primary-button/README.md
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/primary-button/primary-button.spec.js
  src/components/buttons/secondary-button/README.md
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-button/secondary-button.spec.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.spec.js
Labels: 💡 Type: Idea

#499 fix: sequential field id generation
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/date-field/date-field.js
  src/components/fields/date-range-field/date-range-field.js
  src/components/fields/date-time-field/date-time-field.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js
  src/components/fields/localized-text-field/localized-text-field.js
  src/components/fields/money-field/money-field.js
  src/components/fields/multiline-text-field/multiline-text-field.js
  src/components/fields/number-field/number-field.js
  src/components/fields/password-field/password-field.js
  src/components/fields/select-field/select-field.js
  src/components/fields/text-field/text-field.js
  src/components/fields/time-field/time-field.js
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/time-input/time-input.js
  src/utils/get-field-id.js
Labels: Semver: FIX, 🐛 Type: Bug
