Repository commercetools/ui-kit, pull requests merged in 2019-02, with the labels that each got.

#510 Update Deps (including jest)
  jest.test.config.js
  package.json
  test/transform-babel-jest.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#511 fix(tag): wrong css is applied in case linkTo prop is provided
  src/components/tag/tag.js
  src/components/tag/tag.story.js
Labels: Semver: FIX, 🐛 Type: Bug

#512 chore: readds babel preset jest
  package.json
  test/transform-babel-jest.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#514 feat(card): support data attributes
  src/components/card/card.js
  src/components/card/card.spec.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#513 fix: fix background colour for money input
  src/components/inputs/money-input/money-input.styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#515 chore: update changelog and bump package.json
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED

#516 Speech Bubble Icon: adding new icon for welcome page
  src/components/icons/index.js
  src/components/icons/svg/speech-bubble.react.svg
Labels: ✨ Type: New Component, 🚀 Type: New Feature

#520 chore: also apply to css preset emotion
  scripts/get-babel-preset.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#501 Adds `Tooltip` component
  __mocks__/popper.js
  package.json
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/primary-button/primary-button.spec.js
  src/components/internals/root-ref/index.js
  src/components/internals/root-ref/root-ref.js
  src/components/internals/root-ref/root-ref.spec.js
  src/components/panels/collapsible-panel/collapsible-panel.visualroute.js
  src/components/tooltip/README.md
  src/components/tooltip/index.js
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.story.js
  src/components/tooltip/tooltip.styles.js
  src/components/tooltip/tooltip.visualroute.js
  src/components/tooltip/tooltip.visualspec.js
  src/index.js
  yarn.lock
Labels: Semver: FEATURE, ✨ Type: New Component

#521 chore: fix tooltip story
  src/components/tooltip/tooltip.story.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#522 chore: make tooltip more opaque
  package.json
  src/components/fields/localized-text-field/localized-text-field.spec.js
  src/components/tooltip/tooltip.styles.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#517 UIKIT-55: select inputs line between items
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/select-field/select-field.js
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.form.story.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/README.md
  src/components/inputs/async-select-input/async-select-input.form.story.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/creatable-select-input/creatable-select-input.form.story.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/README.md
  src/components/inputs/select-input/select-input-open.visualroute.js
  src/components/inputs/select-input/select-input.form.story.js
  src/components/inputs/select-input/select-input.js
  src/components/inputs/select-input/select-input.visualroute.js
  src/components/inputs/select-input/select-input.visualspec.js
  src/components/internals/create-select-styles.js
Labels: 👨‍🎨 Status: UI/UX Review, 💅 Type: Enhancement

#529 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#530 Update changelog for version `8.3.0`
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#532 fix(select-input): fix for disabled state with multi values selected
  src/components/inputs/select-input/select-input.visualroute.js
  src/components/internals/create-select-styles.js
  src/components/internals/tag-remove/tag-remove.js
Labels: Semver: FIX, 🐛 Type: Bug

#534 chore: changelog and package.json for v8.3.1
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#535 feat(tooltip): allow passing in custom `BodyComponent`
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
  src/components/tooltip/tooltip.story.js
  src/components/tooltip/tooltip.styles.js
  src/components/tooltip/tooltip.visualroute.js
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#536 chore: bump package.json and update changelog for version 8.4.0
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#539 feat(tooltip): Add `off` prop
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#540 chore: bump version and update changelog
  CHANGELOG.md
  package.json
  src/components/tooltip/README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore

#541 refactor: constraint L to be 496px
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/internals/definition.yaml
Labels: ⛑ Type: Refactoring

#553 PageGearIcon: adding new icon for project settings
  src/components/icons/index.js
  src/components/icons/svg/page-gear.react.svg
Labels: Semver: FEATURE, 🚀 Type: New Feature

#556 fix(card): do not apply padding to outer flex container
  src/components/card/card.js
Labels: 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#557 feat(spacings): support justify-content prop for Inline/Stack components
  src/components/spacings/inline/README.md
  src/components/spacings/inline/inline.js
  src/components/spacings/inline/inline.story.js
  src/components/spacings/inline/inline.styles.js
  src/components/spacings/spacings.visualroute.js
  src/components/spacings/stack/README.md
  src/components/spacings/stack/stack.js
  src/components/spacings/stack/stack.story.js
  src/components/spacings/stack/stack.styles.js
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement

#558 fix(spacings): specificity of margin for children elements
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/link-button/link-button.js
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/radio-input/radio-option.js
  src/components/internals/calendar-header/calendar-header.js
  src/components/spacings/inline/inline.styles.js
  src/components/spacings/stack/stack.styles.js
Labels: 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#555 feat(fields/password): add show/hide button
  i18n/core.json
  i18n/de.json
  i18n/en.json
  i18n/es.json
  src/components/fields/password-field/README.md
  src/components/fields/password-field/messages.js
  src/components/fields/password-field/password-field.js
  src/components/fields/password-field/password-field.spec.js
  src/components/fields/password-field/password-field.story.js
  src/components/icons/index.js
  src/components/icons/svg/eye.react.svg
Labels: 🚀 Type: New Feature

#537 feat: add RadioField component, rework RadioInput
  src/components/fields/radio-field/README.md
  src/components/fields/radio-field/index.js
  src/components/fields/radio-field/radio-field.js
  src/components/fields/radio-field/radio-field.spec.js
  src/components/fields/radio-field/radio-field.visualroute.js
  src/components/fields/radio-field/radio-field.visualspec.js
  src/components/grid/grid.visualroute.js
  src/components/inputs/radio-input/README.md
  src/components/inputs/radio-input/radio-group.js
  src/components/inputs/radio-input/radio-input.story.js
  src/components/inputs/radio-input/radio-input.visualroute.js
  src/components/inputs/radio-input/radio-input.visualspec.js
  src/components/inputs/radio-input/radio-option.js
  src/components/inputs/radio-input/radio-option.styles.js
  src/index.js
Labels: Semver: BREAKING, 👨‍👩‍👦‍👦 Status: Dev Review, 💥 Type: Breaking Change

#560 feat(tooltip): add option for tooltip wrapper
  src/components/table/table.story.js
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#550 Fix money parsing
  examples/form-fields.example.story.js
  examples/form-inputs.example.story.js
  src/components/fields/money-field/money-field.form.story.js
  src/components/fields/money-field/money-field.js
  src/components/fields/money-field/money-field.story.js
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/money-input/README.md
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
  src/components/inputs/money-input/money-input.story.js
  yarn.lock
Labels: Semver: FIX, 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#562 feat: use design tokens for input styling
  src/components/inputs/styles.js
Labels: ⛑ Type: Refactoring

#561 chore: update changelog
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#569 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#571 chore: remove double emotion plugin
  package.json
  rollup.config.js
  scripts/get-babel-preset.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#572 feat: remove unnecessary lodash map values dep
  examples/form-inputs.example.story.js
  package.json
  src/components/avatar/avatar.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.js
  src/components/fields/localized-text-field/localized-text-field.js
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#573 chore: remove lodash without
  package.json
  src/components/inputs/localized-money-input/localized-money-input.js
  src/utils/localized.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#574 chore: remove lodash.omit
  package.json
  src/components/internals/calendar-day/calendar-day.js
  src/components/internals/calendar-menu/calendar-menu.js
  src/components/table/table.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore
