Repository commercetools/ui-kit, pull requests merged in 2019-04, with the labels that each got.

#623 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#563 feat: make text-input `theme-able`
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/design-tokens.js
  materials/internals/definition.yaml
  scripts/generate-custom-properties.js
  src/components/inputs/styles.js
  src/components/inputs/text-input/text-input.js
  src/components/inputs/text-input/text-input.story.js
  src/components/inputs/text-input/text-input.visualroute.js
  yarn.lock
Labels: Semver: FEATURE, 🏕 Technical Exploration, 🚀 Type: New Feature

#627 fix: LinkButton to use inline TextBody
  src/components/buttons/link-button/link-button.js
  src/components/typography/text/README.md
Labels: Semver: FIX, ✍️ Type: Documentation, 🔮 Type: Chore

#628 chore: Spacings.Inline to render a span instead of div
  src/components/spacings/inline/inline.js
Labels: 🔮 Type: Chore

#629 chore: use design tokens in money-input
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.styles.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#630 feat(localized-text-input): support custom theming, use design tokens
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.styles.js
  src/components/inputs/localized-text-input/localized-text-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#632 feat(localized-multiline-text-input): support theming / use design tokens
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-multiline-text-input/translation-input.styles.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#633 feat(multiline-text-input): support custom theming
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/components/inputs/multiline-text-input/multiline-text-input.styles.js
  src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#634 feat(number-input): support custom theming
  src/components/inputs/number-input/number-input.js
  src/components/inputs/number-input/number-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#635 feat(password-input): support theming
  src/components/inputs/password-input/password-input.js
  src/components/inputs/password-input/password-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#626 fix: css fixes for tag
  src/components/tag/tag.js
  src/components/tag/tag.story.js
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#643 feat(i18n): support new locales fr-FR and zh-CN
  .storybook/decorators/intl/intl.js
  .storybook/webpack.config.js
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  i18n/index.js
  package.json
  src/index.bundlespec.js
  src/test-utils.js
  test/percy/suite.js
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#641 feat(tags): use design tokens, add theming
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/design-tokens.js
  materials/internals/definition.yaml
  package.json
  src/components/tag/tag.js
  src/components/tag/tag.visualroute.js
  yarn.lock
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#645 feat: use tshirt sizes for spacings
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/internals/definition.yaml
Labels: Semver: FEATURE, 🚀 Type: New Feature

#648 fix(flat-button): focus fixes
  src/components/buttons/flat-button/flat-button.js
Labels: Semver: FIX, 🐛 Type: Bug

#650 fix: Right border of removable tag
  src/components/tag/tag.js
Labels: Semver: FIX, 🐛 Type: Bug

#651 feat(text): allow to pass intl message instead of children
  src/components/typography/text/README.md
  src/components/typography/text/text.js
  src/components/typography/text/text.spec.js
  src/components/typography/text/text.visualroute.js
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#658 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#647 chore: use design tokens for select-inputs
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/design-tokens.js
  materials/internals/definition.yaml
  src/components/internals/create-select-styles.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#663 chore: internally use non deprecated decisions
  src/components/avatar/avatar.js
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.styles.js
  src/components/buttons/link-button/link-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/primary-button/primary-button.styles.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-button/secondary-button.styles.js
  src/components/card/card.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/grid/grid.example.story.js
  src/components/icons/create-styled-icon.js
  src/components/inputs/date-time-input/time-input.js
  src/components/inputs/localized-multiline-text-input/translation-input.styles.js
  src/components/inputs/localized-text-input/localized-text-input.styles.js
  src/components/inputs/money-input/money-input.styles.js
  src/components/inputs/multiline-text-input/multiline-text-input.styles.js
  src/components/inputs/styles.js
  src/components/inputs/time-input/time-input-body.styles.js
  src/components/inputs/toggle-input/toggle-input.styles.js
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/calendar-day/calendar-day.js
  src/components/internals/calendar-header/calendar-header.js
  src/components/internals/calendar-menu/calendar-menu.js
  src/components/internals/create-select-styles.js
  src/components/loading-spinner/loading-spinner.js
  src/components/notifications/content-notification/content-notification.js
  src/components/panels/collapsible-panel/collapsible-panel.styles.js
  src/components/panels/collapsible-panel/header-icon.js
  src/components/spacings/inline/inline.styles.js
  src/components/spacings/inset-squish/inset-squish.js
  src/components/spacings/inset/inset.js
  src/components/spacings/stack/stack.styles.js
  src/components/stamp/stamp.js
  src/components/table/base-table/base-table.js
  src/components/table/cell/cell.js
  src/components/table/sortable-header/sortable-header.js
  src/components/table/table.story.js
  src/components/tag/tag.js
  src/components/tooltip/tooltip.styles.js
  src/components/typography/text/text.styles.js
  test/percy/spec.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#661 fix: change high precision money display
  src/components/fields/money-field/money-field.js
  src/components/fields/money-field/money-field.spec.js
  src/components/icons/index.js
  src/components/icons/svg/fraction-digits.react.svg
  src/components/inputs/money-input/README.md
  src/components/inputs/money-input/messages.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.story.js
  src/components/inputs/money-input/money-input.styles.js
  src/components/inputs/money-input/money-input.visualroute.js
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.styles.js
Labels: 👨‍🎨 Status: UI/UX Review, 👨‍👩‍👦‍👦 Status: Dev Review, 💅 Type: Enhancement, 🚀 Type: New Feature

#664 refactor: use tag in select input
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/create-select-styles.js
  src/components/internals/multivalue/index.js
  src/components/internals/multivalue/multivalue.js
  src/components/internals/tag-remove/index.js
  src/components/internals/tag-remove/tag-remove.js
  src/components/tag/README.md
  src/components/tag/tag.js
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🔮 Type: Chore

#667 fix: storybook build times
  .storybook/webpack.config.js
  package.json
Labels: 🐛 Type: Bug

#668 chore: prepare changelog for 9.2.0
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#670 chore(circleci): use manual env variable checks for releae
  .circleci/config.yml
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 👹 Type: Design Issue

#669 fix: hint icon in field-label
  package.json
  src/components/field-label/field-label.js
  src/components/field-label/field-label.visualroute.js
Labels: 🐛 Type: Bug

#671 feat: allow theming for text
  src/components/label/label.visualroute.js
  src/components/typography/text/text.js
  src/components/typography/text/text.styles.js
  src/components/typography/text/text.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#678 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#679 feat: add translations for Simplified Chinese and French 🇨🇳 🇫🇷🇨🇳 🇫🇷🇨🇳 🇫🇷
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  src/index.bundlespec.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#680 chore: revert changes in field label pr
  package.json
  src/components/field-label/README.md
  src/components/field-label/field-label.js
  src/components/field-label/field-label.spec.js
  src/components/field-label/field-label.visualroute.js
Labels: Semver: FIX, 🐛 Type: Bug

#681 fix(storybook): fix for choosing french and chinese locales
  .storybook/decorators/intl/intl.js
Labels: 🐛 Type: Bug

#683 chore: update french translations
  i18n/data/fr-FR.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#682 feat: support `menuPortalTarget` prop for select-inputs and fields
  src/components/fields/async-creatable-select-field/README.md
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/README.md
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/README.md
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/select-field/README.md
  src/components/fields/select-field/select-field.js
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/README.md
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/README.md
  src/components/inputs/select-input/select-input.js
  src/components/internals/create-select-styles.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#686 feat(select-inputs and fields): support menuShouldBlockScroll prop
  src/components/fields/async-creatable-select-field/README.md
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/README.md
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/README.md
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/select-field/README.md
  src/components/fields/select-field/select-field.js
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/README.md
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/README.md
  src/components/inputs/select-input/select-input.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#684 feat(money-input): support menu portaling
  src/components/fields/money-field/README.md
  src/components/fields/money-field/money-field.js
  src/components/inputs/money-input/README.md
  src/components/inputs/money-input/money-input.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#687 chore: update changelog for version `9.3.0`
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#688 chore: re-add tag filter for circleci to run publish job on tag pushes
  .circleci/config.yml
  .nvmrc
Labels: Semver: UNRELATED, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#685 fix: replace deprecated and broken package jest-plugin-filename
  jest.bundle.config.js
  jest.eslint.config.js
  jest.test.config.js
  package.json
  yarn.lock
Labels: Semver: FIX, 🐛 Type: Bug

#689 fix: releasing from master and release/*
  .circleci/config.yml
Labels: Semver: UNRELATED, 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#690 chore: chinese translations update
  i18n/data/zh-CN.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#692 fix(select-input): fix for prop type
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/money-field/money-field.js
  src/components/fields/select-field/select-field.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/select-input/select-input.js
  src/utils/helpers/exenv.js
  src/utils/helpers/safeHTMLElement.js
Labels: Semver: UNRELATED, 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#704 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#705 chore: update changelog for 9.4.0
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#707 chore(spacings/inline): add justify content select
  src/components/spacings/inline/inline.story.js
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚢 Ship It 🚀

#716 chore: update deps
  package.json
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#718 refactor(checkbox-input): accessibility concerns
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox-input.styles.js
  src/components/inputs/checkbox-input/checkbox.js
Labels: ⛑ Type: Refactoring

#719 refactoring(css): move `accessible-input-styles` to internals
  src/components/inputs/checkbox-input/checkbox.js
  src/components/internals/accessible-hidden-input.styles.js
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🔮 Type: Chore

#720 fix(text): allow theming font family
  src/components/typography/text/text.styles.js
Labels: Semver: FIX, 🐛 Type: Bug
