Repository commercetools/ui-kit, pull requests merged in 2019-11, with the labels that each got.

#1150 fix(rich-text-input): fix for safari
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.spec.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/inputs/rich-text-input/rich-text-input.visualspec.js
  src/components/internals/rich-text-body/hidden-input.js
  src/utils/localized.js
Labels: 🐛 Type: Bug

#1151 refactor(rich-text-input): remove focusability from buttons
  src/components/internals/rich-text-body/rich-text-body-button.js
Labels: 🐛 Type: Bug

#1152 chore: update cl
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1149 chore(vrts): define new spec `listPropsOfChild` prop
  src/components/label/label.visualroute.js
  src/components/tooltip/tooltip.visualroute.js
  test/percy/README.md
  test/percy/spec.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1156 chore: rebuild yarn lock
  yarn.lock
Labels: 🚀 Status: ship it

#1155 chore: update deps
  package.json
  yarn.lock
Labels: 🚀 Status: ship it

#1157 feat(checkbox-input): support isReadOnly prop
  src/components/field-label/README.md
  src/components/inputs/checkbox-input/README.md
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox-input.spec.js
  src/components/inputs/checkbox-input/checkbox-input.story.js
  src/components/inputs/checkbox-input/checkbox-input.styles.js
  src/components/inputs/checkbox-input/checkbox-input.visualroute.js
  src/components/inputs/checkbox-input/checkbox.js
Labels: Semver: FEATURE, 🚀 Status: ship it, 🚀 Type: New Feature

#1158 feat(localized-money-input): support `isReadOnly` prop
  src/components/inputs/localized-money-input/README.md
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.story.js
  src/components/inputs/localized-money-input/localized-money-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Status: ship it, 🚀 Type: New Feature

#1160 fix(date-inputs): header focus problem fix
  src/components/inputs/date-input/date-input-open.visualroute.js
  src/components/inputs/date-input/date-input.story.js
  src/components/inputs/date-input/date-input.visualspec.js
  src/components/inputs/date-time-input/date-time-input.story.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/internals/calendar-header/calendar-header.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-body/rich-text-body.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1163 refactor(secondary-button): use as
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-button/secondary-button.spec.js
  src/components/buttons/secondary-button/secondary-button.story.js
Labels: ⛑ Type: Refactoring

#1164 feat(icon-button): support `as`
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/icon-button/README.md
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.spec.js
  src/components/buttons/icon-button/icon-button.story.js
  src/components/buttons/secondary-button/README.md
  src/components/buttons/secondary-button/secondary-button.js
  src/utils/filter-invalid-attributes.js
  src/utils/filter-invalid-attributes.spec.js
Labels: 🚀 Type: New Feature

#1161 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1166 chore(tag): add missing vrts
  src/components/tag/tag.visualroute.js
Labels: 👨‍⚕️ Type: Tests, 🔮 Type: Chore, 🚀 Status: ship it

#1168 feat(secondary-icon-button): add as prop
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/secondary-icon-button/README.md
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.spec.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1165 refactor(tag): simplify code by using `as` internally
  src/components/tag/tag.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1169 refactor(flat-button): add as, deprecate linkbutton
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/flat-button/README.md
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.spec.js
  src/components/buttons/link-button/link-button.js
  src/components/buttons/link-button/link-button.spec.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-rich-text-input/editor.js
  src/utils/warn-deprecated-component.js
Labels: Semver: FEATURE, ⛑ Type: Refactoring, 🚀 Type: New Feature

#1170 feat(primary-button): support as
  src/components/buttons/primary-button/README.md
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/primary-button/primary-button.spec.js
  src/components/buttons/primary-button/primary-button.styles.js
  src/components/buttons/primary-button/primary-button.visualroute.js
Labels: Semver: FEATURE, 🚀 Status: ship it, 🚀 Type: New Feature

#1174 fix: primary button active and toggle state
  src/components/buttons/primary-button/primary-button.styles.js
Labels: Semver: FIX, 🐛 Type: Bug, 🚀 Status: ship it

#1175 feat(flat-button): add `inverted` tone
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/custom-properties.ts
  materials/design-tokens.js
  materials/internals/definition.yaml
  philosophy/FORMS.md
  src/components/buttons/flat-button/README.md
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.story.js
  src/components/buttons/flat-button/flat-button.visualroute.js
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-select-input/README.md
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/select-input/README.md
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1176 chore: bump version to 10.9.0; update changelog
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1178 chore: change lodash imports
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/collapsible-motion/collapsible-motion.js
  src/components/collapsible/collapsible.js
  src/components/fields/money-field/money-field.js
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-plugins/plugins/mark.js
  src/components/internals/rich-text-plugins/plugins/redo.js
  src/components/internals/rich-text-plugins/plugins/undo.js
  src/components/internals/rich-text-utils/html/html.js
  src/components/internals/rich-text-utils/localized/localized.js
  src/components/internals/tag-remove/tag-remove.js
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/table/table.story.js
  src/components/tooltip/tooltip.js
  src/components/typography/text/text.js
  src/hooks/use-previous/use-previous.spec.js
  src/utils/localized.js
  test/percy/spec.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1179 fix: Localized Rich Text Input containment
  src/components/inputs/localized-rich-text-input/editor.js
Labels: Semver: FIX, 🚀 Status: ship it

#1186 chore: rollup config fix
  bundlesize.config.json
  package.json
  rollup.config.js
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/collapsible-motion/collapsible-motion.js
  src/components/collapsible/collapsible.js
  src/components/fields/money-field/money-field.js
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-plugins/plugins/mark.js
  src/components/internals/rich-text-plugins/plugins/redo.js
  src/components/internals/rich-text-plugins/plugins/undo.js
  src/components/internals/rich-text-utils/html/html.js
  src/components/internals/rich-text-utils/localized/localized.js
  src/components/internals/tag-remove/tag-remove.js
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/table/table.story.js
  src/components/tooltip/tooltip.js
  src/components/typography/text/text.js
  src/hooks/use-previous/use-previous.spec.js
  src/utils/localized.js
  test/percy/spec.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1185 fix(toggle-input): allow to pass value prop
  src/components/inputs/toggle-input/toggle-input.js
Labels: 🐛 Type: Bug

#1187 chore: update cl for release
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1188 fix(text): fix for when text is null
  src/components/typography/text/text.js
  src/components/typography/text/text.spec.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1189 fix(buttons): make onClick not required if as is passed
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1190 chore: update cl for release
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1191 feat(translations): add Japanese 'ja' support for UI-kit
  .storybook/configs/intl-context.js
  .storybook/webpack.config.js
  i18n/data/ja.json
  i18n/index.js
  scripts/extract-intl.js
  src/index.bundlespec.js
  src/test-utils.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1196 fix(tooltip): do not use native title when tooltip is off
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: 🐛 Type: Bug

#1197 fix(localized-rich-text-input): dropdown fix
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/editor.styles.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1192 feat(select): add isReadOnly prop to select inputs and fields
  src/components/fields/async-creatable-select-field/README.md
  src/components/fields/async-creatable-select-field/async-creatable-select-field.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.story.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.visualroute.js
  src/components/fields/async-select-field/README.md
  src/components/fields/async-select-field/async-select-field.js
  src/components/fields/async-select-field/async-select-field.story.js
  src/components/fields/async-select-field/async-select-field.visualroute.js
  src/components/fields/creatable-select-field/README.md
  src/components/fields/creatable-select-field/creatable-select-field.js
  src/components/fields/creatable-select-field/creatable-select-field.story.js
  src/components/fields/creatable-select-field/creatable-select-field.visualroute.js
  src/components/fields/select-field/README.md
  src/components/fields/select-field/select-field.js
  src/components/fields/select-field/select-field.story.js
  src/components/fields/select-field/select-field.visualroute.js
  src/components/inputs/async-creatable-select-input/README.md
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.story.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.visualroute.js
  src/components/inputs/async-select-input/README.md
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/async-select-input/async-select-input.story.js
  src/components/inputs/async-select-input/async-select-input.visualroute.js
  src/components/inputs/creatable-select-input/README.md
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.story.js
  src/components/inputs/creatable-select-input/creatable-select-input.visualroute.js
  src/components/inputs/select-input/README.md
  src/components/inputs/select-input/select-input.js
  src/components/inputs/select-input/select-input.spec.js
  src/components/inputs/select-input/select-input.story.js
  src/components/inputs/select-input/select-input.visualroute.js
  src/components/internals/create-select-styles.js
Labels: Semver: FEATURE, 🚀 Status: ship it, 🚀 Type: New Feature

#1193 fix(radio-input): radio option background color
  src/components/inputs/radio-input/radio-option.styles.js
Labels: Semver: FIX, 🐛 Type: Bug, 🚀 Status: ship it

#1199 chore: bump version to 10.12.0, update changelog
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1200 feat(date-input): add isReadOnly prop to date inputs and fields
  src/components/fields/date-field/README.md
  src/components/fields/date-field/date-field.js
  src/components/fields/date-field/date-field.story.js
  src/components/fields/date-field/date-field.visualroute.js
  src/components/fields/date-range-field/README.md
  src/components/fields/date-range-field/date-range-field.js
  src/components/fields/date-range-field/date-range-field.story.js
  src/components/fields/date-range-field/date-range-field.visualroute.js
  src/components/fields/date-time-field/README.md
  src/components/fields/date-time-field/date-time-field.js
  src/components/fields/date-time-field/date-time-field.story.js
  src/components/fields/date-time-field/date-time-field.visualroute.js
  src/components/inputs/date-input/README.md
  src/components/inputs/date-input/date-input.js
  src/components/inputs/date-input/date-input.story.js
  src/components/inputs/date-input/date-input.visualroute.js
  src/components/inputs/date-range-input/README.md
  src/components/inputs/date-range-input/date-range-input.js
  src/components/inputs/date-range-input/date-range-input.story.js
  src/components/inputs/date-time-input/README.md
  src/components/inputs/date-time-input/date-time-input.js
  src/components/inputs/date-time-input/date-time-input.story.js
  src/components/inputs/date-time-input/date-time-input.visualroute.js
  src/components/internals/calendar-body/calendar-body.js
  src/components/internals/calendar-body/calendar-body.styles.js
Labels: Semver: FEATURE, 🚀 Status: ship it, 🚀 Type: New Feature

#1201 chore: add logo
  README.md
  logo.png
Labels: Semver: UNRELATED
