Repository commercetools/ui-kit, pull requests merged in 2019-09, with the labels that each got.

#1041 chore: update deps
  package.json
  src/components/table/base-table/base-table.js
  src/components/table/base-table/base-table.spec.js
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1034 chore: make stories more consistent
  src/components/fields/date-field/date-field.story.js
  src/components/fields/multiline-text-field/multiline-text-field.story.js
  src/components/fields/text-field/text-field.story.js
  src/components/fields/time-field/time-field.story.js
  src/components/inputs/checkbox-input/checkbox-input.story.js
  src/components/inputs/password-input/password-input.story.js
  src/components/inputs/text-input/text-input.story.js
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1042 feat(collapsible-motion): add minHeight prop
  src/components/collapsible-motion/README.md
  src/components/collapsible-motion/collapsible-motion.js
  src/components/collapsible-motion/collapsible-motion.spec.js
  src/components/collapsible-motion/collapsible-motion.story.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1043 fix(collapsible-motion): do not set to null on rerender
  src/components/collapsible-motion/collapsible-motion.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1044 fix(tooltip): prioritise off
  src/components/tooltip/tooltip.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1045 fix(tooltip): fix for off
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.story.js
Labels: 🐛 Type: Bug

#1052 chore: update deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1053 chore(renovate): combine into weekly three prs
  .renovaterc.json
Labels: Semver: UNRELATED, dependencies, 🏕 Technical Exploration, 🚀 Status: ship it

#1054 feat(tooltip): expose Popper.js modifiers
  src/components/tooltip/README.md
  src/components/tooltip/tooltip.js
  vendors/package-lock.json
Labels: 🚀 Status: ship it

#1055 chore: update cl
  CHANGELOG.md
  package.json
  vendors/package-lock.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1056 fix(flat-button): fully support theming
  src/components/buttons/flat-button/flat-button.js
Labels: 🐛 Type: Bug

#1060 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1061 fix: use correct font family
  src/components/internals/create-select-styles.js
  src/components/tooltip/tooltip.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1062 chore: update changelog for release `10.2.1`
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1063 docs: position to placement
  src/components/tooltip/README.md
Labels: 🚀 Status: ship it

#1067 chore: update deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#952 new component: Rich Text Input
  bundlesize.config.json
  package.json
  src/components/buttons/accessible-button/accessible-button.js
  src/components/inputs/rich-text-input/README.md
  src/components/inputs/rich-text-input/divider.js
  src/components/inputs/rich-text-input/dropdown.js
  src/components/inputs/rich-text-input/dropdown.styles.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/icons/index.js
  src/components/inputs/rich-text-input/icons/svg/bold.react.svg
  src/components/inputs/rich-text-input/icons/svg/expand.react.svg
  src/components/inputs/rich-text-input/icons/svg/italic.react.svg
  src/components/inputs/rich-text-input/icons/svg/more-styles.react.svg
  src/components/inputs/rich-text-input/icons/svg/ordered-list.react.svg
  src/components/inputs/rich-text-input/icons/svg/redo.react.svg
  src/components/inputs/rich-text-input/icons/svg/strikethrough.react.svg
  src/components/inputs/rich-text-input/icons/svg/subscript.react.svg
  src/components/inputs/rich-text-input/icons/svg/superscript.react.svg
  src/components/inputs/rich-text-input/icons/svg/underline.react.svg
  src/components/inputs/rich-text-input/icons/svg/undo.react.svg
  src/components/inputs/rich-text-input/icons/svg/unordered-list.react.svg
  src/components/inputs/rich-text-input/index.js
  src/components/inputs/rich-text-input/messages.js
  src/components/inputs/rich-text-input/multi-dropdown.js
  src/components/inputs/rich-text-input/plugins/index.js
  src/components/inputs/rich-text-input/plugins/list.js
  src/components/inputs/rich-text-input/plugins/mark.js
  src/components/inputs/rich-text-input/plugins/placeholder.js
  src/components/inputs/rich-text-input/plugins/plugins.js
  src/components/inputs/rich-text-input/plugins/redo.js
  src/components/inputs/rich-text-input/plugins/undo.js
  src/components/inputs/rich-text-input/rich-text-editor.spec.js
  src/components/inputs/rich-text-input/rich-text-input-button.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/inputs/rich-text-input/rich-text-input.styles.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/inputs/rich-text-input/rich-text-input.visualspec.js
  src/components/inputs/rich-text-input/test/emptyValue.json
  src/components/inputs/rich-text-input/testValue.json
  src/components/inputs/rich-text-input/utils/index.js
  src/components/inputs/rich-text-input/utils/rules.js
  src/components/inputs/rich-text-input/value.json
  src/components/tooltip/README.md
  src/index.js
  yarn.lock
Labels: ✨ Type: New Component, 🚀 Type: New Feature

#1068 chore: simplify localized text input
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.styles.js
  src/components/inputs/text-input/text-input.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1070 chore(storybook): fix deprecation warning
  .storybook/webpack.config.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1072 refactor(multiline-text-input): move internal
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-multiline-text-input/translation-input.styles.js
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/components/internals/multiline-input/index.js
  src/components/internals/multiline-input/multiline-input.js
  src/components/internals/multiline-input/multiline-input.styles.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1073 refactor(rich-text-input): move components internal
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/messages.js
  src/components/inputs/rich-text-input/rich-text-editor.spec.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/inputs/rich-text-input/testing/json-values/empty-value.json
  src/components/inputs/rich-text-input/testing/json-values/large-value.json
  src/components/inputs/rich-text-input/testing/json-values/minimal-value.json
  src/components/inputs/rich-text-input/utils/index.js
  src/components/internals/rich-text-body/divider.js
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/dropdown.styles.js
  src/components/internals/rich-text-body/icons/index.js
  src/components/internals/rich-text-body/icons/svg/bold.react.svg
  src/components/internals/rich-text-body/icons/svg/expand.react.svg
  src/components/internals/rich-text-body/icons/svg/italic.react.svg
  src/components/internals/rich-text-body/icons/svg/more-styles.react.svg
  src/components/internals/rich-text-body/icons/svg/ordered-list.react.svg
  src/components/internals/rich-text-body/icons/svg/redo.react.svg
  src/components/internals/rich-text-body/icons/svg/strikethrough.react.svg
  src/components/internals/rich-text-body/icons/svg/subscript.react.svg
  src/components/internals/rich-text-body/icons/svg/superscript.react.svg
  src/components/internals/rich-text-body/icons/svg/underline.react.svg
  src/components/internals/rich-text-body/icons/svg/undo.react.svg
  src/components/internals/rich-text-body/icons/svg/unordered-list.react.svg
  src/components/internals/rich-text-body/index.js
  src/components/internals/rich-text-body/messages.js
  src/components/internals/rich-text-body/multi-dropdown.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-body/rich-text-body.js
  src/components/internals/rich-text-body/rich-text-body.styles.js
  src/components/internals/rich-text-plugins/index.js
  src/components/internals/rich-text-plugins/plugins/index.js
  src/components/internals/rich-text-plugins/plugins/list.js
  src/components/internals/rich-text-plugins/plugins/mark.js
  src/components/internals/rich-text-plugins/plugins/placeholder.js
  src/components/internals/rich-text-plugins/plugins/plugins.js
  src/components/internals/rich-text-plugins/plugins/redo.js
  src/components/internals/rich-text-plugins/plugins/undo.js
  src/components/internals/rich-text-plugins/rich-text-plugins.js
  src/components/internals/rich-text-utils/html.js
  src/components/internals/rich-text-utils/is-empty.js
  src/components/internals/rich-text-utils/tags.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1074 fix(rich-text-input): do not fire on blur on dropdown open
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/dropdown.styles.js
  src/components/internals/rich-text-body/multi-dropdown.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1075 fix(rich-text-input): focus hijack prevention
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.form.story.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/internals/rich-text-body/rich-text-body.js
  src/components/internals/rich-text-body/rich-text-body.styles.js
  src/components/internals/rich-text-plugins/plugins/mark.js
  src/components/internals/rich-text-utils/has-block.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1080 chore: enable percy for renovate prs
  scripts/run-percy.sh
Labels: 🔮 Type: Chore

#1081 chore: remove internal link from readme
  src/components/panels/collapsible-panel/README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it
