Repository commercetools/ui-kit, pull requests merged in 2019-03, with the labels that each got.

#577 chore: use lodash-es
  package.json
  rollup.config.js
  scripts/generate-custom-properties.js
  scripts/generate-icon-exports.js
  scripts/get-babel-preset.js
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/collapsible/collapsible.js
  src/components/fields/money-field/money-field.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/select-input/select-input.js
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/table/base-table/base-table.js
  src/components/table/table.story.js
  src/utils/localized.js
  yarn.lock
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#579 docs(readme): update badges [skip ci]
  README.md
Labels: ✍️ Type: Documentation

#586 chore: upgrade deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore

#597 Fix parse money value in MoneyInput
  src/components/inputs/money-input/money-input.form.story.js
  src/components/inputs/money-input/money-input.js
Labels: Semver: FIX, 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review

#598 fix(table): to remove jumpy effect on hover
  src/components/table/sortable-header/sortable-header.js
Labels: 🐛 Type: Bug

#605 chore: changelog for 9.1.1 release
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#612 Update dependencies
  .travis.yml
  package.json
  scripts/get-babel-preset.js
  yarn.lock
Labels: 🔮 Type: Chore

#614 chore: update visual routes, add missing dep
  package.json
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.visualroute.js
  src/components/fields/multiline-text-field/multiline-text-field.visualroute.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.visualroute.js
  src/components/inputs/multiline-text-input/multiline-text-input.visualroute.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#613 chore: update deps
  package.json
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#615 Refactor to use CircleCI instead of TravisCI
  .circleci/config.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  jest-puppeteer.config.js
  package.json
  scripts/publish-docs.js
  scripts/run-percy.sh
Labels: Semver: UNRELATED, 👨‍⚕️ Type: Tests, 🔮 Type: Chore

#616 refactor(collapsible-panel): add `min-height`
  src/components/panels/collapsible-panel/collapsible-panel.js
  src/components/panels/collapsible-panel/collapsible-panel.styles.js
Labels: 👶 good first contribution, 👹 Type: Design Issue, 💅 Type: Enhancement

#618 chore: update changelog, bump version to v9.1.2
  CHANGELOG.md
  package.json
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🔮 Type: Chore

#619 fix(circleci): releasing to next
  .circleci/config.yml
Labels: Semver: UNRELATED, 🐛 Type: Bug
