Repository commercetools/ui-kit, pull requests merged in 2019-10, with the labels that each got.

#1083 chore: update react-select, remove ci silencing
  package.json
  test/setup-tests.js
  vendors/package-lock.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1082 refactor(rich-text-input): focus rework
  src/components/buttons/accessible-button/accessible-button.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/dropdown.styles.js
  src/components/internals/rich-text-body/multi-dropdown.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-body/rich-text-body.js
  src/components/internals/rich-text-plugins/plugins/undo.js
Labels: ⛑ Type: Refactoring

#1084 chore: update deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore

#1085 fix(rich-text-input): use `output` instead of `div` for contenteditable
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.form.story.js
Labels: Semver: FIX, 🐛 Type: Bug

#1088 fix(rich-text-input): performance fix
  src/components/inputs/rich-text-input/rich-text-input.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1091 fix(rich-text-input): fixes undo / redo button problem
  src/components/internals/rich-text-body/rich-text-body-button.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1089 fix(localized-multiline-text-input): margin fix
  src/components/inputs/localized-multiline-text-input/translation-input.js
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#1092 chore: update cl for release
  CHANGELOG.md
  package.json
  src/components/inputs/rich-text-input/README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1093 fix(rich-text-input): fix onBlur and onFocus
  src/components/inputs/rich-text-input/rich-text-input.js
Labels: 🐛 Type: Bug

#1094 chore(rich-text-input): simplify testing
  src/components/inputs/rich-text-input/rich-text-input.form.story.js
  src/components/inputs/rich-text-input/rich-text-input.spec.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/inputs/rich-text-input/testing/json-values/empty-value.json
  src/components/inputs/rich-text-input/testing/json-values/large-value.json
  src/components/inputs/rich-text-input/testing/json-values/minimal-value.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1095 feat(rich-text-input): add expand icon
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/internals/rich-text-body/icons/index.js
  src/components/internals/rich-text-body/messages.js
  src/components/internals/rich-text-body/rich-text-body.js
Labels: 👨‍🎨 Status: UI/UX Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1103 fix(rich-text-input): fix regression
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.visualspec.js
Labels: 🐛 Type: Bug

#1104 chore(percy): add new prop to percy Spec to specify which props to display in snapshots
  test/percy/README.md
  test/percy/spec.js
Labels: Semver: UNRELATED

#1107 chore(rich-text-input): perf improvement
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.story.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.story.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1108 fix(localized-rich-text-input): make behaviour match other localized component
  src/components/inputs/localized-rich-text-input/README.md
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1109 chore(localized-rich-text-input): show expand button
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
Labels: 🔮 Type: Chore

#1114 fix(accessible-button): use not-allowed cursor on disabled
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/accessible-button/accessible-button.spec.js
  src/components/buttons/secondary-button/secondary-button.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1110 feat(rich-text-input): support admin center rich text
  src/components/internals/rich-text-utils/html/html.js
  src/components/internals/rich-text-utils/html/html.spec.js
  src/components/internals/rich-text-utils/html/index.js
  src/components/internals/rich-text-utils/tags.js
Labels: 🚀 Type: New Feature

#1116 chore: update cl
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1118 fix(buttons): fix onClick bug
  src/components/buttons/accessible-button/accessible-button.js
  src/components/buttons/secondary-button/secondary-button.spec.js
Labels: 🐛 Type: Bug

#1119 chore: update cl
  CHANGELOG.md
  package.json
Labels: 🚀 Status: ship it

#1121 feat(select-inputs): support inputValue
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/select-input.js
Labels: 🚀 Type: New Feature

#1122 fix(typography): fix Text.Body to use intlMessage when 'as' prop is present
  src/components/typography/text/text.js
  src/components/typography/text/text.spec.js
Labels: Semver: FIX, 🐛 Type: Bug, 🚀 Status: ship it

#1126 fix: use SafeHTMLElement
  src/components/tooltip/tooltip.js
  vendors/package-lock.json
Labels: 🐛 Type: Bug

#1125 feat(localized-rich-text-input): adds `LocalizedRichTextInput.createLocalizedString`
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.js
  src/components/internals/rich-text-plugins/rich-text-plugins.js
  src/components/internals/rich-text-utils/is-empty.js
  src/components/internals/rich-text-utils/is-empty/index.js
  src/components/internals/rich-text-utils/is-empty/is-empty.js
  src/components/internals/rich-text-utils/is-empty/is-empty.spec.js
  src/components/internals/rich-text-utils/localized/index.js
  src/components/internals/rich-text-utils/localized/localized.js
  src/components/internals/rich-text-utils/localized/localized.spec.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1128 fix(rich-text-input): disabled fix
  src/components/inputs/localized-rich-text-input/rich-text-input.js
  src/components/inputs/rich-text-input/rich-text-input.js
Labels: 🚀 Status: ship it

#1127 chore: build i18n
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/messages.js
  src/components/internals/rich-text-body/multi-dropdown.js
  src/components/internals/rich-text-body/rich-text-body.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1130 chore: combine i18n messages
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  src/components/fields/money-field/messages.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-creatable-select-input/messages.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/async-select-input/messages.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/creatable-select-input/messages.js
  src/components/inputs/localized-multiline-text-input/languages-control.js
  src/components/inputs/localized-multiline-text-input/messages.js
  src/components/inputs/localized-multiline-text-input/required-value-error-message.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/languages-control.js
  src/components/inputs/localized-rich-text-input/messages.js
  src/components/inputs/localized-rich-text-input/required-value-error-message.js
  src/components/inputs/localized-text-input/languages-button.js
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/messages.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/messages/localized-input/index.js
  src/components/internals/messages/localized-input/messages.js
  src/components/internals/messages/multiline-input/index.js
  src/components/internals/messages/multiline-input/messages.js
  src/components/internals/messages/select/index.js
  src/components/internals/messages/select/messages.js
Labels: 🔮 Type: Chore

#1131 chore: add german i18n
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  src/components/inputs/rich-text-input/rich-text-input.visualspec.js
  src/components/internals/rich-text-body/messages.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1132 fix(rich-text-input): visual disabled fixes
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualroute.js
  src/components/inputs/rich-text-input/rich-text-input.visualroute.js
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/dropdown.styles.js
  src/components/internals/rich-text-body/multi-dropdown.js
  src/components/internals/rich-text-body/rich-text-body-button.js
  src/components/internals/rich-text-body/rich-text-body.js
  src/components/internals/rich-text-body/rich-text-body.styles.js
Labels: 🐛 Type: Bug

#1133 chore: update cl
  CHANGELOG.md
  package.json
  vendors/package-lock.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1134 fix(localized-rich-text-input): fix omit empty translations, add readme
  src/components/inputs/localized-multiline-text-input/README.md
  src/components/inputs/localized-rich-text-input/README.md
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.js
  src/components/internals/rich-text-utils/localized/index.js
  src/components/internals/rich-text-utils/localized/localized.js
  src/components/internals/rich-text-utils/localized/localized.spec.js
Labels: 🔮 Type: Chore

#1135 chore: add spanish i18n
  i18n/data/de.json
  i18n/data/es.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1137 chore: update readme
  src/components/inputs/localized-rich-text-input/README.md
  src/components/inputs/multiline-text-input/README.md
  src/components/inputs/rich-text-input/README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1138 chore: use native node13 full icu
  .circleci/config.yml
  .nvmrc
  package.json
  src/components/inputs/money-input/money-input.spec.js
  vendors/README.md
  vendors/package-lock.json
  vendors/package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1144 chore: try reverting puppeteer upgrade
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1143 refactor(rich-text-input): combine dropdowns
  src/components/internals/rich-text-body/dropdown.js
  src/components/internals/rich-text-body/multi-dropdown.js
  src/components/internals/rich-text-body/rich-text-body.js
Labels: ⛑ Type: Refactoring

#1145 fix(rich-text-input): dropdown focus bug
  src/components/inputs/rich-text-input/rich-text-input.visualspec.js
  src/components/internals/rich-text-body/rich-text-body.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1139 [WIP] feat(radio-input): add components prop to radio input option
  src/components/inputs/radio-input/README.md
  src/components/inputs/radio-input/radio-group.js
  src/components/inputs/radio-input/radio-input.spec.js
  src/components/inputs/radio-input/radio-option.js
Labels: 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Status: ship it

#1146 chore: update cl
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it
