Repository commercetools/ui-kit, pull requests merged in 2019-06, with the labels that each got.

#825 chore: update deps
  .circleci/config.yml
  .size-snapshot.json
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#826 chore: use prod in vrt
  visual-testing-app/webpack.config.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#827 fix(base-table): onSortChange being called without being passed
  src/components/table/base-table/base-table.js
  src/components/table/base-table/base-table.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#828 fix(icon-button): centre icon
  .size-snapshot.json
  src/components/buttons/icon-button/icon-button.js
Labels: Semver: FIX, 🐛 Type: Bug

#830 chore: update changelog and package.json for 9.8.2
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED

#832 fix(toggle-input): toggle input disabled styles
  src/components/inputs/toggle-input/toggle-input.js
Labels: Semver: FIX, 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#833 Revert "fix(toggle-input): toggle input disabled styles (#832)"
  src/components/inputs/toggle-input/toggle-input.js
Labels: Semver: UNRELATED

#835 chore: update brand image
  .storybook/config.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#836 chore: update changelog for 9.8.3
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#837 chore: update readme with percy badge
  README.md
Labels: 🔮 Type: Chore

#838 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#840 feat: add version export
  .size-snapshot.json
  rollup.config.js
  src/index.bundlespec.js
  src/index.js
  src/version.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#841 feat(storybook): use contexts for choosing locale
  .storybook/addons.js
  .storybook/config.js
  .storybook/configs/contexts.js
  .storybook/configs/intl-context.js
  .storybook/decorators/index.js
  .storybook/decorators/intl/index.js
  .storybook/decorators/intl/intl.js
  package.json
  yarn.lock
Labels: ✍️ Type: Documentation, 🔮 Type: Chore

#849 chore: update deps
  .prettierignore
  package.json
  scripts/generate-custom-properties.js
  src/components/inputs/money-input/money-input.js
  src/components/internals/create-select-styles.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#850 fix: use first-of-type instead of first-child
  src/components/internals/create-select-styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#852 chore: update cl for release 9.9.0
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#855 fix(select-inputs): multi select disabled bug
  src/components/inputs/select-input/select-input.spec.js
  src/components/internals/create-select-styles.js
  src/components/internals/tag-remove/tag-remove.js
Labels: 🐛 Type: Bug

#856 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🔮 Type: Chore

#858 chore: update readme for horizontal constraint
  src/components/constraints/horizontal/README.md
Labels: 🔮 Type: Chore

#866 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#868 chore: add missing deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#870 fix(number-input): toFormValue should handle both undefined and null
  src/components/inputs/number-input/number-input.js
  src/components/inputs/number-input/number-input.spec.js
Labels: 🐛 Type: Bug

#869 style(flat-button): implement inverted tone
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.visualroute.js
Labels: 💅 Type: Enhancement

#871 fix(icon-button): hover state fix, and remove HOC
  .size-snapshot.json
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.spec.js
  src/components/buttons/icon-button/icon-button.styles.js
  src/components/buttons/icon-button/icon-button.visualroute.js
Labels: 🐛 Type: Bug

#872 refactor(secondary-button): remove usage of HOC
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-button/secondary-button.styles.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#873 refactor(table): remove HOC
  src/components/table/sortable-header/sortable-header.js
Labels: ⛑ Type: Refactoring

#874 chore: update cl for 9.10.0
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#876 feat(storybook): add context add for theme
  .storybook/configs/contexts.js
  .storybook/configs/theme-context.js
  .storybook/decorators/section/section.js
Labels: 💅 Type: Enhancement

#880 refactor: use non deprecated custom properties
  README.md
  src/components/inputs/toggle-input/toggle-input.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#878 fix(field-icon): do not scale icon when long hint
  src/components/field-label/field-label.js
  src/components/field-label/field-label.visualroute.js
Labels: 🐛 Type: Bug

#885 chore: remove classnames
  package.json
  src/components/table/base-table/base-table.js
  src/components/table/base-table/base-table.spec.js
  yarn.lock
Labels: ⛑ Type: Refactoring

#892 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#893 feat: add postcss codemod
  codemods/custom-property-replacer/README.md
  codemods/custom-property-replacer/custom-property-replacer.js
  codemods/custom-property-replacer/custom-property-replacer.spec.js
  codemods/custom-property-replacer/index.js
  codemods/custom-property-replacer/v10/variable-mapping.json
  materials/custom-properties.css
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#896 fix(storybook): downgrade storybook-readme
  .size-snapshot.json
  materials/custom-properties.css
  package.json
  yarn.lock
Labels: 🐛 Type: Bug

#900 [UIKIT-879] feat(buttons): Add color prop to SecondaryIconButton
  .size-snapshot.json
  src/components/buttons/secondary-icon-button/README.md
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.story.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.styles.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.visualroute.js
Labels: Semver: FEATURE, 💅 Type: Enhancement
