Repository commercetools/ui-kit, pull requests merged in 2019-05, with the labels that each got.

#722 refactor(checkbox-input): accessibility fix
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox.js
Labels: Semver: FIX, 🐛 Type: Bug

#721 refactoring(RadioInput): hovered and focus state changes
  src/components/inputs/radio-input/radio-option.js
  src/components/inputs/radio-input/radio-option.styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#708 refactoring(toggle-input): change to new design
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/internals/definition.yaml
  src/components/inputs/toggle-input/icons/index.js
  src/components/inputs/toggle-input/icons/toggle-bar-default.react.svg
  src/components/inputs/toggle-input/icons/toggle-button-default.react.svg
  src/components/inputs/toggle-input/toggle-input.js
  src/components/inputs/toggle-input/toggle-input.styles.js
  src/components/inputs/toggle-input/toggle-switch.js
  src/components/inputs/toggle-input/toggle.story.js
Labels: ⛑ Type: Refactoring, 👨‍👩‍👦‍👦 Status: Dev Review

#726 feat(icons): make icons themeable (breaking change)
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/link-button/link-button.js
  src/components/buttons/primary-button/primary-button.js
  src/components/buttons/secondary-button/secondary-button.js
  src/components/buttons/secondary-icon-button/secondary-icon-button.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/field-label/README.md
  src/components/field-label/field-label.js
  src/components/icons/README.md
  src/components/icons/create-styled-icon.js
  src/components/icons/icon.story.js
  src/components/icons/icons.visualroute.js
  src/components/icons/icons.visualspec.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/time-input/time-input-body.js
  src/components/internals/calendar-body/calendar-body.js
  src/components/internals/clear-indicator/clear-indicator.js
  src/components/internals/dropdown-indicator/dropdown-indicator.js
  src/components/notifications/content-notification/content-notification.js
  src/components/panels/collapsible-panel/header-icon.js
  src/components/table/sortable-header/sortable-header.js
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#724 fix(time-input): readonly fix
  src/components/inputs/time-input/time-input-body.js
  src/components/inputs/time-input/time-input-body.styles.js
  src/components/inputs/time-input/time-input.js
  src/components/inputs/time-input/time-input.story.js
  src/components/inputs/time-input/time-input.visualroute.js
Labels: 🐛 Type: Bug

#728 feat(checkbox-input): use design tokens / add theming
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox-input.styles.js
  src/components/inputs/checkbox-input/checkbox-input.visualroute.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#727 feat(selects): make selects inputs themable
  package.json
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/select-input.js
  src/components/inputs/select-input/select-input.visualroute.js
  src/components/inputs/select-input/select-input.visualspec.js
  src/components/internals/create-select-styles.js
  yarn.lock
Labels: Semver: FEATURE, 🚀 Type: New Feature

#735 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#737 refactor: use non deprecated tokens
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox.js
  src/components/inputs/money-input/money-input.js
  src/components/inputs/radio-input/radio-option.js
  src/components/inputs/radio-input/radio-option.styles.js
  src/components/inputs/time-input/time-input-body.styles.js
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/calendar-menu/calendar-menu.js
Labels: Semver: UNRELATED, ⛑ Type: Refactoring, 🔮 Type: Chore

#738 Add suplink icon
  src/components/icons/index.js
  src/components/icons/svg/subdirectory-arrow.react.svg
Labels: Semver: FEATURE, 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Type: New Feature

#739 refactor: change custom props
  src/components/inputs/radio-input/radio-option.js
  src/components/inputs/radio-input/radio-option.styles.js
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/calendar-day/calendar-day.js
  src/components/label/required-indicator.js
Labels: ⛑ Type: Refactoring

#741 chore: use non deprecated prop
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/calendar-menu/calendar-menu.js
Labels: ⛑ Type: Refactoring

#742 chore: use non deprecated token
  src/components/tag/tag.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#743 refactor: shadow change
  src/components/card/card.js
  src/components/panels/collapsible-panel/collapsible-panel.styles.js
Labels: ⛑ Type: Refactoring

#745 feat(date-range-input): add `isClearable` prop
  src/components/inputs/date-range-input/README.md
  src/components/inputs/date-range-input/date-range-input.js
  src/components/inputs/date-range-input/date-range-input.spec.js
  src/components/inputs/date-range-input/date-range-input.story.js
  src/components/internals/calendar-body/calendar-body.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#746 chore: update changelog for version `9.5.0`
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#740 refactor: remove deprecated custom props
  materials/custom-properties.css
  materials/custom-properties.js
  materials/custom-properties.json
  materials/design-tokens.js
  materials/internals/definition.yaml
Labels: Semver: BREAKING, 💥 Type: Breaking Change

#752 fix(link-button): add hover effect for icon
  src/components/buttons/link-button/link-button.js
Labels: 🐛 Type: Bug

#754 fix(tooltip): margin specificity fix
  src/components/tooltip/tooltip.styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#755 feat: add new `<Link>` component.
  src/components/links/link/README.md
  src/components/links/link/index.js
  src/components/links/link/link.js
  src/components/links/link/link.spec.js
  src/components/links/link/link.story.js
  src/components/links/link/link.visualroute.js
  src/components/links/link/link.visualspec.js
  src/index.js
  src/utils/get-pass-through-props.js
  src/utils/get-pass-through-props.spec.js
Labels: Semver: FEATURE, 🚀 Type: New Feature

#762 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#764 chore: update changelog for version `9.6.0`
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#747 refactor: Text Inputs to spread attributes and remove wrapper
  src/components/constraints/horizontal/horizontal.js
  src/components/constraints/horizontal/index.js
  src/components/fields/text-field/text-field.js
  src/components/inputs/styles.js
  src/components/inputs/text-input/README.md
  src/components/inputs/text-input/text-input.js
  src/components/inputs/text-input/text-input.spec.js
  src/components/inputs/text-input/text-input.story.js
  src/components/inputs/text-input/text-input.visualroute.js
  src/utils/warn-deprecated-prop.js
  transforms/README.md
  transforms/react-component-rename-props.js
Labels: Semver: BREAKING, ⛑ Type: Refactoring, 🏕 Technical Exploration, 💥 Type: Breaking Change

#765 fix: tooltip z-index fix
  src/components/tooltip/tooltip.styles.js
Labels: 🐛 Type: Bug

#766 chore: update changelog for new version 9.6.1
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#768 docs(readme): fix spacings in readme
  README.md
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚢 Ship It 🚀

#769 refactor(flat-button): simplify code, remove mouseover
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.spec.js
Labels: ⛑ Type: Refactoring

#773 fix(time-input): border radius bug
  src/components/inputs/time-input/time-input-body.styles.js
Labels: 🐛 Type: Bug

#775 fix(checkbox): hovered state when disabled
  src/components/inputs/checkbox-input/checkbox-input.js
Labels: 🐛 Type: Bug

#771 refactor: Checkboxes to spread attributes and improve a11y
  src/components/inputs/checkbox-input/README.md
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/checkbox-input/checkbox-input.spec.js
  src/components/inputs/checkbox-input/checkbox-input.story.js
  src/components/inputs/checkbox-input/checkbox-input.styles.js
  src/components/inputs/checkbox-input/checkbox.js
  src/components/internals/accessible-hidden-input.styles.js
Labels: ⛑ Type: Refactoring

#776 refactoring(time-input):`TimeInput` improvements
  src/components/inputs/time-input/time-input-body.js
  src/components/inputs/time-input/time-input-body.styles.js
Labels: ⛑ Type: Refactoring, 👨‍🎨 Status: UI/UX Review

#778 feat: add pin gear icon
  src/components/icons/index.js
  src/components/icons/svg/pin-gear.react.svg
Labels: 🚀 Type: New Feature

#780 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#777 fix(collapsible-panel): disabled state fix
  src/components/panels/collapsible-panel/header-icon.js
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#782 fix(icon-button): add border color
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.styles.js
Labels: 🐛 Type: Bug

#781 chore: update changelog for `9.7.0`
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#783 feat(link-button): support isExternal prop
  src/components/buttons/link-button/README.md
  src/components/buttons/link-button/link-button.js
  src/components/buttons/link-button/link-button.story.js
  src/components/links/link/link.js
Labels: 🚀 Type: New Feature

#784 fix(select-inputs): fix multi value bug
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/select-input/select-input.js
  src/components/internals/create-select-styles.js
  src/components/internals/multivalue/index.js
  src/components/internals/multivalue/multivalue.js
  src/components/internals/tag-remove/index.js
  src/components/internals/tag-remove/tag-remove.js
Labels: 🐛 Type: Bug

#785 chore: update changelog for release 9.8.0
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore

#792 chore: update deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore

#794 fix(icon-button): misaligned icon fix
  src/components/buttons/icon-button/icon-button.js
Labels: 🐛 Type: Bug

#796 docs(tooltip): rename label to title
  src/components/tooltip/README.md
Labels: 🔮 Type: Chore

#795 Fix MoneyInput.parseMoneyValue to respect the fraction digits
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
Labels: 🐛 Type: Bug

#798 refactor: Password input and field to spread attributes
  src/components/fields/password-field/README.md
  src/components/fields/password-field/password-field.js
  src/components/fields/password-field/password-field.spec.js
  src/components/fields/password-field/password-field.story.js
  src/components/fields/password-field/password-field.visualroute.js
  src/components/inputs/password-input/README.md
  src/components/inputs/password-input/password-input.js
  src/components/inputs/password-input/password-input.spec.js
  src/components/inputs/password-input/password-input.story.js
  src/components/inputs/password-input/password-input.visualroute.js
  src/components/inputs/text-input/text-input.js
Labels: ⛑ Type: Refactoring

#800 fix(i18n): build all locales
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  scripts/extract-intl.js
Labels: 🐛 Type: Bug

#802 fix(select-inputs): localize placeholder
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-creatable-select-input/messages.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/async-select-input/messages.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/creatable-select-input/messages.js
  src/components/inputs/select-input/messages.js
  src/components/inputs/select-input/select-input.js
Labels: 🐛 Type: Bug

#803 chore: update changelog
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore

#804 fix(multiline-input): Expand behaviour not working
  src/components/inputs/localized-multiline-text-input/translation-input.styles.js
  src/components/inputs/multiline-text-input/multiline-text-input.styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#805 fix(collapsible-panel): remove z-index
  src/components/panels/collapsible-panel/collapsible-panel.styles.js
Labels: 🐛 Type: Bug

#813 chore: update deps
  .size-snapshot.json
  package.json
  src/components/buttons/secondary-button/secondary-button.visualspec.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.visualspec.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.visualspec.js
  src/components/fields/async-select-field/async-select-field.visualspec.js
  src/components/inputs/localized-money-input/localized-money-input.visualspec.js
  yarn.lock
Labels: 🔮 Type: Chore

#815 feat: add stylelint for css-in-js
  .stylelintrc
  jest.stylelint.config.js
  package.json
  yarn.lock
Labels: 👨‍⚕️ Type: Tests

#816 chore: fix lint errors, add linting to ci
  .circleci/config.yml
  lint-staged.config.js
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/icon-button/icon-button.styles.js
  src/components/grid/grid.js
  src/components/inputs/checkbox-input/checkbox-input.js
  src/components/inputs/time-input/time-input-body.styles.js
  src/components/inputs/toggle-input/toggle-input.js
  src/components/internals/calendar-menu/calendar-menu.js
  src/components/table/base-table/base-table.js
  src/components/tag/tag.js
Labels: 🔮 Type: Chore

#817 fix(radio-input): do not use htmlFor if no id is passed
  src/components/inputs/radio-input/radio-group.js
  src/components/inputs/radio-input/radio-option.js
Labels: 🐛 Type: Bug

#820 chore: update rtl to latest
  .eslintrc.yaml
  .github/PULL_REQUEST_TEMPLATE/add-new-component.md
  CONTRIBUTING.md
  package.json
  scripts/setup-test-framework.js
  src/components/inputs/number-input/number-input.spec.js
  src/components/inputs/password-input/password-input.spec.js
  src/test-utils.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#819 chore: update react-select to version 3
  .size-snapshot.json
  package.json
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.spec.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/async-select-input/async-select-input.spec.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.spec.js
  src/components/inputs/select-input/select-input.js
  src/components/inputs/select-input/select-input.spec.js
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: 🔮 Type: Chore
