Repository commercetools/ui-kit, pull requests merged in 2019-08, with the labels that each got.

#978 chore: generate custom-properties.ts
  materials/custom-properties.ts
  package.json
  scripts/generate-custom-properties.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#979 fix(jest/setup): to show actual error logs on CI when something is logged
  test/setup-tests.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#975 refactor(localized-multiline-text-input): to use hooks
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.spec.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.story.js
  src/components/inputs/localized-multiline-text-input/translation-input.js
Labels: ⛑ Type: Refactoring

#980 refactor(calendar-body): use hooks
  src/components/internals/calendar-body/calendar-body.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#991 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#992 chore: update react-intl to 3.0.0-beta.23
  package.json
  yarn.lock
Labels: 🚀 Status: ship it

#984 refactor: improve `useToggleState` and use it across our components
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/fields/password-field/password-field.js
  src/components/inputs/money-input/money-input.js
  src/components/internals/calendar-body/calendar-body.js
  src/hooks/use-toggle-state/use-toggle-state.js
  src/hooks/use-toggle-state/use-toggle-state.spec.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#993 chore(select-input): add test for when autoFocussed is true
  src/components/inputs/select-input/select-input.spec.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#983 refactor(tooltip): use hooks
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#981 refactor(collapsible-motion): use hooks
  src/components/collapsible-motion/collapsible-motion.js
  src/components/panels/collapsible-panel/collapsible-panel.spec.js
  src/hooks/use-previous/index.js
  src/hooks/use-previous/use-previous.js
  src/hooks/use-previous/use-previous.spec.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#994 refactor(tooltip): replace react-popper with use-popper
  package.json
  src/components/internals/root-ref/index.js
  src/components/internals/root-ref/root-ref.js
  src/components/internals/root-ref/root-ref.spec.js
  src/components/tooltip/tooltip.js
  yarn.lock
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#982 chore: update changelog
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#995 chore: remove unused dep and move to dev
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#996 chore: update deps and use new react-intl
  .storybook/webpack.config.js
  package.json
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: Semver: UNRELATED, 🚀 Status: ship it

#997 fix(tooltip): use defined variable
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip.spec.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#998 chore: update cl and pkg.json for release
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#999 fix(inputs): do not generate new field id on each render
  src/components/fields/password-field/password-field.js
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.story.js
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/time-input/time-input.js
  src/components/tooltip/tooltip.js
  src/hooks/use-field-id/index.js
  src/hooks/use-field-id/use-field-id.js
  src/hooks/use-field-id/use-field-id.spec.js
Labels: Semver: FIX, 🐛 Type: Bug

#1001 chore: update cl for release
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1008 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1015 chore: update (most) deps
  .eslintrc.yaml
  package.json
  src/components/notifications/content-notification/content-notification.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1016 chore: update react and testing-library
  package.json
  scripts/setup-test-framework.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.spec.js
  src/components/fields/multiline-text-field/multiline-text-field.spec.js
  test/setup-tests.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1018 chore: enable clear mocks
  jest.test.config.js
Labels: Semver: UNRELATED, 🔮 Type: Chore, 🚀 Status: ship it

#1020 chore: run tests with full-icu
  .circleci/config.yml
  .eslintignore
  .prettierignore
  package.json
  scripts/setup-test-framework.js
  src/components/inputs/time-input/time-input.spec.js
  vendors/README.md
  vendors/package-lock.json
  vendors/package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#1029 chore: fix money input tooltip
  src/components/inputs/money-input/money-input.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1031 chore: update deps
  package.json
  yarn.lock
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1019 Fix MoneyInput's parsing
  src/components/inputs/money-input/money-input.js
  src/components/inputs/money-input/money-input.spec.js
Labels: 🐛 Type: Bug, 👨‍👩‍👦‍👦 Status: Dev Review, 🚀 Status: ship it

#1032 chore: update cl for latest release
  CHANGELOG.md
  package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1033 chore: update tooltip docs
  src/components/tooltip/README.md
Labels: ✍️ Type: Documentation
