Repository commercetools/ui-kit, pull requests merged in 2019-07, with the labels that each got.

#908 chore: upate deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#910 feat(date-inputs): add tooltip to "today" button
  i18n/data/core.json
  i18n/data/de.json
  i18n/data/en.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
  src/components/internals/calendar-header/calendar-header.js
  src/components/internals/calendar-header/messages.js
Labels: 🐛 Type: Bug, 👨‍🎨 Status: UI/UX Review

#911 fix(link): apply underlined styles
  .size-snapshot.json
  src/components/links/link/README.md
  src/components/links/link/link.js
  src/components/links/link/link.story.js
  src/components/links/link/link.visualroute.js
Labels: 🐛 Type: Bug

#913 chore: remove size snapshot
  .size-snapshot.json
  package.json
  rollup.config.js
  yarn.lock
Labels: 🔮 Type: Chore

#914 feat: setup bundlesize
  .circleci/config.yml
  bundlesize.config.json
  package.json
  yarn.lock
Labels: 🔮 Type: Chore

#918 fix(date-range-input): localize day names
  src/components/inputs/date-range-input/date-range-input.js
Labels: 🐛 Type: Bug

#919 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#925 chore: update deps
  .storybook/config.js
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#883 chore: update changelog for 10.0.0 release
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#926 10.0.0 - Update codemod
  package.json
  transforms/README.md
  transforms/react-component-rename-props.js
  transforms/v10/README.md
  transforms/v10/icon-theme-to-color.js
  transforms/v10/icons/icon-names.js
  transforms/v10/react-component-rename-props.js
  transforms/v10/text-element-type-to-as.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#927 fix(date-time-input): Today button not highlighting today's date
  src/components/inputs/date-time-input/date-time-input.js
Labels: Semver: FIX, 🐛 Type: Bug

#928 chore(date-time-field): fix story
  src/components/fields/date-time-field/date-time-field.story.js
Labels: Semver: UNRELATED, 🔮 Type: Chore

#931 chore: update translations
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#934 chore: add missing german translations
  i18n/data/de.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#941 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#942 fix(buttons): leftovers of theme/color renaming
  src/components/buttons/icon-button/README.md
  src/components/buttons/icon-button/icon-button.js
  src/components/buttons/icon-button/icon-button.story.js
  src/components/buttons/icon-button/icon-button.styles.js
  src/components/buttons/icon-button/icon-button.visualroute.js
  src/components/buttons/secondary-button/README.md
  src/components/buttons/secondary-button/secondary-button.story.js
  src/components/buttons/secondary-button/secondary-button.styles.js
  src/components/buttons/secondary-button/secondary-button.visualroute.js
Labels: 🐛 Type: Bug

#943 fix(table): Leftovers of theme/color renaming in table sortable header
  src/components/table/sortable-header/sortable-header.js
Labels: 🐛 Type: Bug

#944 chore: update cl
  CHANGELOG.md
  package.json
Labels: Semver: UNRELATED, 🔮 Type: Chore

#951 chore: update deps
  package.json
  scripts/setup-test-framework.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#953 chore: update jest-runner-stylelint to v2
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#954 fix(date-inputs): placeholder i18n fixes
  i18n/data/de.json
  i18n/data/es.json
  i18n/data/fr-FR.json
  i18n/data/zh-CN.json
Labels: 🐛 Type: Bug

#955 [UKIT-85] fix: truncate select-input placeholder text is long
  src/components/inputs/select-input/select-input.visualroute.js
  src/components/internals/create-select-styles.js
Labels: Semver: FIX, 🐛 Type: Bug

#956 chore: update deps
  package.json
  yarn.lock
Labels: 🚀 Status: ship it

#960 refactor(time-input): use hooks
  src/components/inputs/time-input/time-input.js
  src/components/inputs/time-input/time-input.story.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#957 refactor: use hooks
  src/components/fields/password-field/password-field.js
  src/components/fields/password-field/password-field.story.js
  src/components/inputs/async-creatable-select-input/async-creatable-select-input.js
  src/components/inputs/async-select-input/async-select-input.js
  src/components/inputs/creatable-select-input/creatable-select-input.js
  src/components/inputs/localized-money-input/currency-control.js
  src/components/inputs/localized-multiline-text-input/languages-control.js
  src/components/inputs/localized-text-input/languages-button.js
  src/components/inputs/select-input/select-input.js
Labels: ⛑ Type: Refactoring

#962 chore: update react-intl to latest
  jest.bundle.config.js
  jest.test.config.js
  package.json
  vendors-to-transpile.js
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#967 chore: add eslint-plugin-react-hooks
  .eslintrc.yaml
  package.json
  src/components/inputs/time-input/time-input.js
  yarn.lock
Labels: 🔮 Type: Chore, 🖐 Status: On Hold

#972 chore: update deps
  package.json
  yarn.lock
Labels: Semver: UNRELATED, 🔮 Type: Chore

#958 refactor(localized-text-input): use hooks
  src/components/inputs/localized-text-input/localized-text-input.js
  src/components/inputs/localized-text-input/localized-text-input.story.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#963 refactor(date-input): use hooks
  src/components/inputs/date-input/date-input.js
  src/components/internals/calendar-header/calendar-header.js
Labels: ⛑ Type: Refactoring

#966 refactor(multiline-text-input): use hooks & expose `useCollapsible` hook
  src/components/collapsible/collapsible.js
  src/components/inputs/multiline-text-input/multiline-text-input.js
  src/hooks/use-toggle-state/index.js
  src/hooks/use-toggle-state/use-toggle-state.js
  src/hooks/use-toggle-state/use-toggle-state.spec.js
  src/index.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#965 refactor(primary-action-dropdown): use hooks
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.js
  src/components/dropdowns/primary-action-dropdown/primary-action-dropdown.spec.js
  src/hooks/index.js
  src/hooks/use-toggle-state/index.js
  src/hooks/use-toggle-state/use-toggle-state.spec.js
  src/index.js
Labels: ⛑ Type: Refactoring

#964 refactor(money-input): use hooks
  src/components/inputs/money-input/money-input.js
Labels: ⛑ Type: Refactoring

#977 refactor: refactor more components to functional components / hooks
  src/components/inputs/radio-input/radio-group.js
  src/components/inputs/toggle-input/toggle-input.js
Labels: ⛑ Type: Refactoring

#974 refactor(localized-money-input): use hooks
  src/components/inputs/localized-money-input/localized-money-input.js
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  src/components/inputs/localized-text-input/localized-text-input.js
Labels: ⛑ Type: Refactoring
