Repository commercetools/ui-kit, pull requests merged in 2019-12, with the labels that each got.

#1206 docs: update release process
  .eslintignore
  CONTRIBUTING.md
  jest.stylelint.config.js
  jest.test.config.js
  package.json
Labels: ✍️ Type: Documentation

#1207 chore: move to zeit now
  .gitignore
  .prettierignore
  .storybook/config.js
  .storybook/webpack.config.js
  jest.eslint.config.js
  netlify.toml
  now.json
  package.json
  packages/components/table/index.js
Labels: 🛠 Type: Tooling

#1211 fix(flat-button): icon size and position for multi-line anchors
  src/components/buttons/flat-button/flat-button.js
  src/components/buttons/flat-button/flat-button.spec.js
  src/components/buttons/flat-button/flat-button.story.js
  src/components/buttons/flat-button/flat-button.visualroute.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1214 fix(text-detail): proptypes warning when providing an empty string as…
  src/components/typography/text/text.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1213 feat: add min and max value props to date-input and field
  src/components/fields/date-field/README.md
  src/components/fields/date-field/date-field.js
  src/components/fields/date-field/date-field.story.js
  src/components/inputs/date-input/README.md
  src/components/inputs/date-input/date-input.js
  src/components/inputs/date-input/date-input.story.js
  src/components/internals/calendar-day/calendar-day.js
  src/utils/calendar.js
  src/utils/calendar.spec.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1216 chore: fix build i18n command
  package.json
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
  packages/i18n/data/fr-FR.json
  packages/i18n/data/ja.json
  packages/i18n/data/zh-CN.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1215 fix(select-input): make the ClearIndicator a button
  packages/components/inputs/select-utils/package.json
  packages/i18n/data/core.json
  packages/i18n/data/de.json
  packages/i18n/data/en.json
  packages/i18n/data/es.json
  packages/i18n/data/fr-FR.json
  packages/i18n/data/ja.json
  packages/i18n/data/zh-CN.json
  src/components/inputs/select-input/select-input.spec.js
  src/components/internals/clear-indicator/clear-indicator.js
  src/components/internals/clear-indicator/messages.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1218 chore: remove i18n and materials build output from preset/ui-kit
  .gitignore
  presets/ui-kit/i18n/data/core.json
  presets/ui-kit/i18n/data/de.json
  presets/ui-kit/i18n/data/en.json
  presets/ui-kit/i18n/data/es.json
  presets/ui-kit/i18n/data/fr-FR.json
  presets/ui-kit/i18n/data/ja.json
  presets/ui-kit/i18n/data/zh-CN.json
  presets/ui-kit/materials/custom-properties.css
  presets/ui-kit/materials/custom-properties.js
  presets/ui-kit/materials/custom-properties.json
  presets/ui-kit/materials/custom-properties.ts
  presets/ui-kit/materials/design-tokens.js
  presets/ui-kit/materials/internals/TOKENS.md
  presets/ui-kit/materials/internals/definition.yaml
  presets/ui-kit/materials/internals/tokens.story.js
Labels: 🔮 Type: Chore

#1219 chore: check npm authentication on prerelease
  package.json
Labels: 🔮 Type: Chore

#1220 chore: use babel.config.js file
  .storybook/webpack.config.js
  babel.config.js
  jest.bundle.config.js
  jest.test.config.js
  jest.visual.config.js
  package.json
  rollup.config.js
  scripts/extract-intl.js
  test/replace-module-paths.js
  test/transform-babel-jest.js
  visual-testing-app/webpack.config.js
  yarn.lock
Labels: 🔮 Type: Chore
