Repository commercetools/ui-kit, pull requests merged in 2020-11, with the labels that each got.

#1645 Allow NumberInput and NumberField to have the step prop set to "any"
  .changeset/poor-pens-sit.md
  packages/components/fields/number-field/README.md
  packages/components/fields/number-field/src/number-field.js
  packages/components/fields/number-field/src/number-field.story.js
  packages/components/inputs/checkbox-input/README.md
  packages/components/inputs/number-input/README.md
  packages/components/inputs/number-input/src/number-input.js
  packages/components/inputs/number-input/src/number-input.story.js
Labels: 🚀 Status: ship it

#1654 Update uikit presets
  .changeset/pretty-clocks-scream.md
  presets/fields/index.js
  presets/fields/package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1663 Enable defaultOptions in SearchSelectInput
  .changeset/shy-buckets-look.md
  packages/components/inputs/search-select-input/README.md
  packages/components/inputs/search-select-input/docs/additional-info.md
  packages/components/inputs/search-select-input/package.json
  packages/components/inputs/search-select-input/src/search-select-input.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1668 chore(utils): remove is variation
  .changeset/strange-windows-turn.md
  packages/utils/src/is-variation.js
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review, 🚀 Status: ship it

#1678 fix(constraints): package.json component pack for generators
  packages/components/constraints/README.md
  packages/components/constraints/package.json
  packages/components/fields/async-creatable-select-field/README.md
  packages/components/fields/async-select-field/README.md
  packages/components/fields/creatable-select-field/README.md
  packages/components/fields/date-field/README.md
  packages/components/fields/date-range-field/README.md
  packages/components/fields/date-time-field/README.md
  packages/components/fields/localized-multiline-text-field/README.md
  packages/components/fields/localized-text-field/README.md
  packages/components/fields/money-field/README.md
  packages/components/fields/multiline-text-field/README.md
  packages/components/fields/number-field/README.md
  packages/components/fields/password-field/README.md
  packages/components/fields/radio-field/README.md
  packages/components/fields/search-select-field/README.md
  packages/components/fields/select-field/README.md
  packages/components/fields/text-field/README.md
  packages/components/fields/time-field/README.md
  packages/components/inputs/async-creatable-select-input/README.md
  packages/components/inputs/async-select-input/README.md
  packages/components/inputs/creatable-select-input/README.md
  packages/components/inputs/date-input/README.md
  packages/components/inputs/date-range-input/README.md
  packages/components/inputs/date-time-input/README.md
  packages/components/inputs/localized-multiline-text-input/README.md
  packages/components/inputs/localized-text-input/README.md
  packages/components/inputs/money-input/README.md
  packages/components/inputs/multiline-text-input/README.md
  packages/components/inputs/number-input/README.md
  packages/components/inputs/password-input/README.md
  packages/components/inputs/search-select-input/README.md
  packages/components/inputs/select-input/README.md
  packages/components/inputs/text-input/README.md
  packages/components/inputs/time-input/README.md
  packages/components/tag/README.md
Labels: 🚀 Status: ship it
