Repository commercetools/ui-kit, pull requests merged in 2020-08, with the labels that each got.

#1462 chore(ui-kit): add changeset for updated dependencies
  .changeset/few-mice-notice.md
Labels: 🚀 Status: ship it

#1464 Expose hasWarning prop on select fields
  .changeset/slimy-windows-yell.md
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.form.story.js
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.js
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.story.js
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.visualroute.js
  packages/components/fields/async-select-field/src/async-select-field.form.story.js
  packages/components/fields/async-select-field/src/async-select-field.js
  packages/components/fields/async-select-field/src/async-select-field.story.js
  packages/components/fields/async-select-field/src/async-select-field.visualroute.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.form.story.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.story.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.visualroute.js
Labels: 🚀 Status: ship it

#1459 fix(data-table): increase click area of expand/collapse row button
  .changeset/rare-jars-smell.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1427 chore(table): update data-table 'beta' status and warn about table deprecating
  packages/components/data-table-manager/src/data-table-manager.story.js
  packages/components/data-table/README.md
  packages/components/data-table/src/data-table.story.js
  packages/components/table/README.md
  packages/components/table/src/table.story.js
Labels: 🚀 Status: ship it

#1466 fix(data-table):horizontal scrolling
  .changeset/slow-ligers-stare.md
  packages/components/data-table/src/data-table.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1470 chore(select fields): document hasWarning prop in select fields READMEs
  .changeset/unlucky-phones-refuse.md
  packages/components/fields/async-creatable-select-field/README.md
  packages/components/fields/async-select-field/README.md
  packages/components/fields/creatable-select-field/README.md
  packages/components/fields/select-field/README.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1469 feat(data-table): add prop onColumnResized
  .changeset/six-teachers-type.md
  packages/components/data-table/README.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/header-cell.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1465 feat(data-table): Add prop `disableSelfContainment`
  .changeset/hip-hairs-allow.md
  packages/components/data-table/README.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/data-table.visualroute.js
Labels: 👨‍🎨 Status: UI/UX Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1475 fix(data-table): pass column key to onRowClick callback
  .changeset/chilly-sheep-join.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.styles.js
Labels: 🚀 Status: ship it

#1493 fix(data-table): dragging column on Safari causing text selecting
  .changeset/eight-geese-learn.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
Labels: 👨‍🎨 Status: UI/UX Review, 🙏 Status: Dev Review, 🚀 Status: ship it

#1471 feat: add package to generate readme files
  .changeset/moody-hornets-explain.md
  .eslintignore
  .github/workflows/main.yml
  .prettierrc
  @types/rcfile/index.d.ts
  @types/remark-mdx/index.d.ts
  @types/to-vfile/index.d.ts
  @types/vfile-reporter/index.d.ts
  babel.config.js
  generators/readme/.gitignore
  generators/readme/README.md
  generators/readme/bin/generate-readme.ts
  generators/readme/bin/generate_readme.sh
  generators/readme/package.json
  generators/readme/src/index.ts
  generators/readme/src/types.ts
  generators/readme/src/utils/stringify-options.ts
  generators/readme/test/fixtures/avenger/docs/additional-info.md
  generators/readme/test/fixtures/avenger/docs/usage-example.js
  generators/readme/test/fixtures/avenger/package.json
  generators/readme/test/fixtures/avenger/src/avenger.js
  generators/readme/test/generate-readme.spec.ts
  generators/readme/tsconfig.json
  jest.ts-test.config.js
  package.json
  packages/components/avatar/README.md
  packages/components/avatar/docs/usage-example.js
  packages/components/avatar/package.json
  tsconfig.json
  yarn.lock
Labels: 🏕 Type: Technical Exploration

#1499 feat: add new ViewGridPlus icon
  .changeset/sharp-impalas-count.md
  packages/components/icons/src/components/view-grid-plus.js
  packages/components/icons/src/index.js
  packages/components/icons/src/raw-components/view-grid-plus.js
  packages/components/icons/src/svg/view-grid-plus.react.svg
  transforms/v10/icons/icon-names.js
Labels: 🚀 Status: ship it

#1501 chore: to wrap intlMessage in a div in ContentNotification
  .changeset/pretty-onions-punch.md
  packages/components/notifications/src/content-notification/README.md
  packages/components/notifications/src/content-notification/content-notification.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1423 chore: update pptr-testing-library
  .renovaterc.json
  package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1508 fix(data-table): check for columns prop on runtime
  .changeset/tricky-oranges-retire.md
  generators/readme/src/index.ts
  packages/components/data-table/README.md
  packages/components/data-table/docs/usage-example.js
  packages/components/data-table/package.json
  packages/components/data-table/src/data-table.js
Labels: 🚀 Status: ship it

#1496 fix(data-table): container not adjusting to table size when shrank
  .changeset/yellow-chicken-lay.md
  packages/components/data-table/package.json
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1513 fix(generators/readme): Escape the "|" character while join enum values
  generators/readme/src/index.ts
  generators/readme/test/generate-readme.spec.ts
  packages/components/avatar/README.md
  packages/components/card/README.md
  packages/components/data-table-manager/README.md
  packages/components/data-table/README.md
Labels: 🚀 Status: ship it

#1506 feat(data-table): pass sizes as array of {key, width} to onColumnResized
  .changeset/gold-bikes-enjoy.md
  packages/components/data-table/README.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/header-cell.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.spec.js
Labels: 🚀 Status: ship it

#1517 fix(data-table): last column not being clipped when resizing
  .changeset/unlucky-lions-dance.md
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/footer.js
Labels: 🚀 Status: ship it

#1528 fix(data-table): table column sizes not being properly reset
  .changeset/silver-cars-kiss.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
Labels: 🚀 Status: ship it

#1529 fix(data-table): Cell clickable area
  .changeset/seven-bananas-argue.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
Labels: 🚀 Status: ship it

#1532 fix(github): action to use recent puppeteer action
  .github/workflows/main.yml
Labels: 🚀 Status: ship it

#1527 Add generate readmes for stamp, loading spinner and tag.
  .changeset/clever-beds-mix.md
  packages/components/loading-spinner/README.md
  packages/components/loading-spinner/docs/usage-example.js
  packages/components/loading-spinner/package.json
  packages/components/loading-spinner/src/loading-spinner.js
  packages/components/stamp/README.md
  packages/components/stamp/docs/usage-example.js
  packages/components/stamp/package.json
  packages/components/stamp/src/stamp.js
  packages/components/tag/README.md
  packages/components/tag/docs/description.md
  packages/components/tag/docs/usage-example.js
  packages/components/tag/package.json
  packages/components/tag/src/tag-body.js
  packages/components/tag/src/tag.js
Labels: 🚀 Status: ship it

#1531 fix(data-table): header icon vertical placement
  .changeset/large-rivers-guess.md
  packages/components/data-table/src/data-table.visualroute.js
  packages/components/data-table/src/header-cell.styles.js
Labels: 🚀 Status: ship it

#1526 feat(select-input): add support for icons on the left of the input value and placeholder
  .changeset/tasty-trains-swim.md
  packages/components/fields/async-creatable-select-field/README.md
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.js
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.story.js
  packages/components/fields/async-select-field/README.md
  packages/components/fields/async-select-field/src/async-select-field.js
  packages/components/fields/async-select-field/src/async-select-field.story.js
  packages/components/fields/creatable-select-field/README.md
  packages/components/fields/creatable-select-field/src/creatable-select-field.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.story.js
  packages/components/fields/select-field/README.md
  packages/components/fields/select-field/src/select-field.js
  packages/components/fields/select-field/src/select-field.story.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.story.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.visualroute.js
  packages/components/inputs/async-select-input/README.md
  packages/components/inputs/async-select-input/src/async-select-input.js
  packages/components/inputs/async-select-input/src/async-select-input.story.js
  packages/components/inputs/async-select-input/src/async-select-input.visualroute.js
  packages/components/inputs/creatable-select-input/README.md
  packages/components/inputs/creatable-select-input/src/creatable-select-input.js
  packages/components/inputs/creatable-select-input/src/creatable-select-input.story.js
  packages/components/inputs/creatable-select-input/src/creatable-select-input.visualroute.js
  packages/components/inputs/select-input/README.md
  packages/components/inputs/select-input/src/select-input.js
  packages/components/inputs/select-input/src/select-input.story.js
  packages/components/inputs/select-input/src/select-input.visualroute.js
  packages/components/inputs/select-utils/index.js
  src/components/internals/create-select-styles.js
  src/components/internals/wrapper-with-icon/index.js
  src/components/internals/wrapper-with-icon/wrapper-with-icon.js
Labels: 🚀 Status: ship it

#1534 docs(collapsible): generate readmes for collapsible
  .changeset/moody-sheep-smile.md
  packages/components/collapsible-motion/README.md
  packages/components/collapsible-motion/docs/description.md
  packages/components/collapsible-motion/docs/usage-example.js
  packages/components/collapsible-motion/package.json
  packages/components/collapsible-motion/src/collapsible-motion.js
  packages/components/collapsible-panel/README.md
  packages/components/collapsible-panel/docs/additional-info.md
  packages/components/collapsible-panel/docs/description.md
  packages/components/collapsible-panel/docs/usage-example.js
  packages/components/collapsible-panel/package.json
  packages/components/collapsible-panel/src/collapsible-panel.js
Labels: 🚀 Status: ship it
