Repository commercetools/ui-kit, pull requests merged in 2020-01, with the labels that each got.

#1238 fix(select-input): multi select tag borders
  src/components/internals/create-select-styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1240 chore: update calendar-utils
  packages/calendar-utils/package.json
  packages/components/inputs/date-input/package.json
  packages/components/inputs/date-range-input/package.json
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1242 chore(tag): fix storybook example
  src/components/tag/tag.story.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1246 feat(contraints-horizontal): modify to pass down data props
  packages/components/constraints/package.json
  src/components/constraints/horizontal/horizontal.js
  src/components/constraints/horizontal/horizontal.spec.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1247 docs(changelog): for release v10.15.0 [skip ci]
  CHANGELOG.md
Labels: 🚀 Status: ship it

#1251 fix(secondary-button): to prop-type
  src/components/buttons/secondary-button/secondary-button.js
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review, 🚀 Status: ship it

#1252 docs(tokens): remove superfluous word
  design-system/materials/internals/TOKENS.md
Labels: 🚀 Status: ship it

#1253 [UKIT-97] fix(tag): on remove button hover when disabled
  src/components/tag/tag.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it
