Repository commercetools/ui-kit, pull requests merged in 2020-05, with the labels that each got.

#1338 chore: setup changesets, move to gh actions
  .circleci/config.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  lerna.json
  package.json
  scripts/changelog.js
  scripts/release_canary.sh
  scripts/run-percy.sh
  yarn.lock
Labels: 🛠 Type: Tooling

#1341 fix(data-table): contain table with horizontal scroll when maxWidth is set
  .changeset/violet-cougars-applaud.md
  packages/components/data-table/src/data-table.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1345 fix(data-table): Allow table to have scrollbar when too wide for its container
  .changeset/seven-adults-turn.md
  packages/components/data-table/src/data-table.styles.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1347 chore(text): fix wrong util fn causing warnings in dev
  src/components/typography/text/text.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1349 feat(src/components/icons): Add AngleUpDown icon to the icons set
  .changeset/odd-toys-hide.md
  src/components/icons/components/angle-up-down.js
  src/components/icons/index.js
  src/components/icons/raw-components/angle-up-down.js
  src/components/icons/svg/angle-up-down.react.svg
Labels: 🚀 Status: ship it

#1351 feat(data-table/cell): Improve data table's sortable columns
  .changeset/tidy-hounds-repeat.md
  packages/components/data-table/package.json
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  yarn.lock
Labels: 🚀 Status: ship it

#1354 feat(icons): Update available icons set
  .changeset/weak-jobs-laugh.md
  src/components/icons/components/right-triangle-filled.js
  src/components/icons/components/right-triangle-linear.js
  src/components/icons/index.js
  src/components/icons/raw-components/right-triangle-filled.js
  src/components/icons/raw-components/right-triangle-linear.js
  src/components/icons/svg/right-triangle-filled.react.svg
  src/components/icons/svg/right-triangle-linear.react.svg
Labels: 🚀 Status: ship it

#1355 docs: fixes to some documentation files
  README.md
  packages/components/primary-action-dropdown/README.md
  src/components/inputs/select-input/README.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1357 feat(label): add intlMessage prop
  .changeset/stupid-points-exist.md
  packages/components/label/README.md
  packages/components/label/package.json
  packages/components/label/src/label.js
  packages/components/label/src/label.spec.js
  packages/components/label/src/label.visualroute.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1360 Update utils README in order to trigger a new release of the utils package
  .changeset/breezy-berries-matter.md
  packages/localized-utils/index.js
  packages/localized-utils/src/index.js
  packages/localized-utils/src/version.js
  packages/utils/README.md
  packages/utils/package.json
Labels: 🐛 Type: Bug

#1364 chore(docs): to update spacings stack docs
  src/components/spacings/stack/README.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it
