Repository commercetools/ui-kit, pull requests merged in 2020-07, with the labels that each got.

#1403 fix(data-table): clip cells when table is resized
  .changeset/young-jeans-grow.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1405 fix(data-table): cast getHasTableBeenResized to a boolean
  .changeset/few-bananas-explode.md
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1406 Adding isRowCollapsed to call of column renderItem and table itemRenderer
  .changeset/eleven-humans-argue.md
  packages/components/data-table/README.md
  packages/components/data-table/src/data-row.js
Labels: 🚀 Status: ship it

#1402 refactor: rename now.json to vercel.json
  vercel.json
Labels: 🚀 Status: ship it

#1411 refactor(data-table): extract header and footer components to their own modules
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/footer.js
  packages/components/data-table/src/footer.styles.js
  packages/components/data-table/src/header-cell.js
  packages/components/data-table/src/header-cell.styles.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1419 chore(packages/text): move typography to packages
  .changeset/tasty-schools-wave.md
  packages/components/icons/src/icon.story.js
  packages/components/stamp/src/stamp.story.js
  packages/components/text/README.md
  packages/components/text/index.js
  packages/components/text/src/index.js
  packages/components/text/src/text.js
  packages/components/text/src/text.spec.js
  packages/components/text/src/text.story.js
  packages/components/text/src/text.styles.js
  packages/components/text/src/text.visualroute.js
  packages/components/text/src/text.visualspec.js
  packages/components/text/src/version.js
  src/components/spacings/inline/inline.story.js
  src/components/typography/text/index.js
Labels: 🚀 Status: ship it

#1420 feat(data-table): add column prop "headerIcon"
  .changeset/light-donkeys-begin.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.visualroute.js
  packages/components/data-table/src/header-cell.js
  packages/components/data-table/src/header-cell.styles.js
Labels: 👨‍🎨 Status: UI/UX Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1425 fix(data-table): Row collapsing behaviour
  .changeset/angry-carrots-accept.md
  packages/components/data-table/src/data-row.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1430 packages/select-field: Enable hasWarning prop on SelectField
  .changeset/flat-squids-decide.md
  packages/components/fields/select-field/src/select-field.form.story.js
  packages/components/fields/select-field/src/select-field.js
  packages/components/fields/select-field/src/select-field.story.js
  packages/components/fields/select-field/src/select-field.visualroute.js
Labels: 🚀 Status: ship it

#1434 feat(link): add intlMessage prop to Link in ui-kit
  .changeset/ten-suns-count.md
  packages/components/link/README.md
  packages/components/link/package.json
  packages/components/link/src/link.js
  packages/components/link/src/link.spec.js
  packages/components/link/src/link.visualroute.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1426 fix(data-table): footer horizontal scroll
  .changeset/yellow-wolves-hunt.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/footer.js
  packages/components/data-table/src/footer.styles.js
Labels: 🚀 Status: ship it

#1445 chore(actions): use personal access token to allow triggering multiple workflows
  .github/workflows/release.yml
Labels: 🚀 Status: ship it

#1451 chore(packages/notifications): move notifications to packages
  .changeset/two-masks-shop.md
  packages/components/notifications/index.js
  packages/components/notifications/src/content-notification/README.md
  packages/components/notifications/src/content-notification/content-notification.js
  packages/components/notifications/src/content-notification/content-notification.spec.js
  packages/components/notifications/src/content-notification/content-notification.story.js
  packages/components/notifications/src/content-notification/content-notification.visualroute.js
  packages/components/notifications/src/content-notification/content-notification.visualspec.js
  packages/components/notifications/src/content-notification/index.js
  packages/components/notifications/src/index.js
  packages/components/notifications/src/version.js
Labels: 🚀 Status: ship it

#1450 chore(packages/spacings): move spacings to packages
  .changeset/fluffy-horses-attack.md
  packages/components/spacings/inline/README.md
  packages/components/spacings/inline/index.js
  packages/components/spacings/inline/src/index.js
  packages/components/spacings/inline/src/inline.js
  packages/components/spacings/inline/src/inline.spec.js
  packages/components/spacings/inline/src/inline.story.js
  packages/components/spacings/inline/src/inline.styles.js
  packages/components/spacings/inline/src/version.js
  packages/components/spacings/inset-squish/README.md
  packages/components/spacings/inset-squish/index.js
  packages/components/spacings/inset-squish/src/index.js
  packages/components/spacings/inset-squish/src/inset-squish.js
  packages/components/spacings/inset-squish/src/inset-squish.spec.js
  packages/components/spacings/inset-squish/src/inset-squish.story.js
  packages/components/spacings/inset-squish/src/version.js
  packages/components/spacings/inset/README.md
  packages/components/spacings/inset/index.js
  packages/components/spacings/inset/src/index.js
  packages/components/spacings/inset/src/inset.js
  packages/components/spacings/inset/src/inset.spec.js
  packages/components/spacings/inset/src/inset.story.js
  packages/components/spacings/inset/src/version.js
  packages/components/spacings/spacings.visualroute.js
  packages/components/spacings/spacings.visualspec.js
  packages/components/spacings/stack/README.md
  packages/components/spacings/stack/index.js
  packages/components/spacings/stack/src/index.js
  packages/components/spacings/stack/src/stack.js
  packages/components/spacings/stack/src/stack.spec.js
  packages/components/spacings/stack/src/stack.story.js
  packages/components/spacings/stack/src/stack.styles.js
  packages/components/spacings/stack/src/version.js
  packages/components/stamp/src/stamp.story.js
  src/components/spacings/index.js
  src/components/spacings/inline/index.js
  src/components/spacings/inset-squish/index.js
  src/components/spacings/inset/index.js
  src/components/spacings/stack/index.js
Labels: 🚀 Status: ship it

#1454 chore(data-table-manager): Documentation and prop-type validation fixes
  packages/components/data-table-manager/README.md
  packages/components/data-table-manager/src/data-table-manager.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1455 feat(data-table): allow css value strings for maxHeight and maxWidth
  .changeset/ninety-flowers-attend.md
  packages/components/data-table/README.md
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/data-table.visualroute.js
  packages/components/data-table/src/utils/convert-numeric-dimension-to-pixel-value.js
  packages/components/data-table/src/utils/convert-numeric-dimension-to-pixel-value.spec.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1457 fix: ui-kit preset export and version bump for data-table-manager
  .changeset/cyan-beers-promise.md
  .changeset/real-jars-appear.md
  bundlesize.config.json
  packages/components/data-table-manager/package.json
  packages/components/data-table-manager/src/data-table-settings/column-manager/column-manager.js
  presets/ui-kit/index.js
  presets/ui-kit/package.json
  rollup.config.js
Labels: 🚀 Status: ship it
