Repository commercetools/ui-kit, pull requests merged in 2020-06, with the labels that each got.

#1353 feat(data-table): Enable rows to expand and collapse in case they have truncated columns
  .changeset/little-tomatoes-brush.md
  packages/components/data-table/package.json
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.styles.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1368 feat(components/icons): Update grid icon
  .changeset/giant-parrots-play.md
  src/components/icons/raw-components/grid.js
  src/components/icons/svg/grid.react.svg
Labels: 🚀 Status: ship it

#1376 fix(select-fields): Fix RTL tests
  .changeset/fair-icons-talk.md
  src/components/fields/async-creatable-select-field/async-creatable-select-field.spec.js
  src/components/fields/async-select-field/async-select-field.spec.js
  src/components/fields/creatable-select-field/creatable-select-field.spec.js
  src/components/fields/select-field/select-field.spec.js
Labels: 🚀 Status: ship it

#1378 docs: add updated codesandbox example
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: ✍️ Type: Documentation, 🚀 Status: ship it

#1379 fix(data-table): add data-testid attributes to headers and cells
  .changeset/fair-rabbits-tell.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.spec.js
Labels: 👨‍⚕️ Type: Tests, 🔮 Type: Chore, 🚀 Status: ship it

#1369 fix(tooltip): Hide tooltip on mouseleave event for disabled inputs/buttons
  .changeset/gorgeous-weeks-sparkle.md
  packages/components/tooltip/src/tooltip.js
  packages/components/tooltip/src/tooltip.story.js
  packages/components/tooltip/src/tooltip.styles.js
Labels: 🚀 Status: ship it

#1380 fix(data-table): Improve DataTable row's expand/collapse accessibility
  .changeset/strong-foxes-attend.md
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.styles.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1363 feat(data-table): enable column resizing by user mouse drag
  .changeset/chilly-chefs-press.md
  packages/calendar-time-utils/CHANGELOG.md
  packages/calendar-utils/CHANGELOG.md
  packages/components/avatar/CHANGELOG.md
  packages/components/buttons/accessible-button/CHANGELOG.md
  packages/components/buttons/flat-button/CHANGELOG.md
  packages/components/buttons/icon-button/CHANGELOG.md
  packages/components/buttons/link-button/CHANGELOG.md
  packages/components/buttons/primary-button/CHANGELOG.md
  packages/components/buttons/secondary-button/CHANGELOG.md
  packages/components/buttons/secondary-icon-button/CHANGELOG.md
  packages/components/card/CHANGELOG.md
  packages/components/collapsible-motion/CHANGELOG.md
  packages/components/collapsible/CHANGELOG.md
  packages/components/constraints/CHANGELOG.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/column-resizer.js
  packages/components/data-table/src/column-resizing-context.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/use-manual-column-resizing-reducer.js
  packages/components/field-errors/CHANGELOG.md
  packages/components/inputs/number-input/CHANGELOG.md
  packages/components/inputs/password-input/CHANGELOG.md
  packages/components/inputs/radio-input/CHANGELOG.md
  packages/components/inputs/text-input/CHANGELOG.md
  packages/components/inputs/toggle-input/CHANGELOG.md
  packages/components/label/CHANGELOG.md
  packages/components/link/CHANGELOG.md
  packages/components/loading-spinner/CHANGELOG.md
  packages/components/messages/CHANGELOG.md
  packages/components/spacings/inline/CHANGELOG.md
  packages/components/spacings/inset-squish/CHANGELOG.md
  packages/components/spacings/inset/CHANGELOG.md
  packages/components/spacings/stack/CHANGELOG.md
  packages/components/stamp/CHANGELOG.md
  packages/components/text/CHANGELOG.md
  packages/components/tooltip/CHANGELOG.md
  packages/hooks/CHANGELOG.md
  packages/localized-utils/CHANGELOG.md
  packages/utils/CHANGELOG.md
  presets/buttons/CHANGELOG.md
  presets/spacings/CHANGELOG.md
  rollup.config.js
  src/components/spacings/stack/README.md
Labels: 👨‍🎨 Status: UI/UX Review, 🚀 Status: ship it, 🚀 Type: New Feature

#1387 fix(data-table): column resizer taking extra space
  .changeset/metal-bees-mix.md
  packages/components/data-table/src/column-resizer.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1390 chore: to use node.js v14 through .nvmrc
  .nvmrc
Labels: 🙏 Status: Dev Review

#1389 fix: to add `eslint-plugin-jest-dom`
  .eslintrc.yaml
  package.json
  packages/components/buttons/accessible-button/src/accessible-button.spec.js
  packages/components/buttons/flat-button/src/flat-button.spec.js
  packages/components/buttons/icon-button/src/icon-button.spec.js
  packages/components/buttons/link-button/src/link-button.spec.js
  packages/components/buttons/primary-button/src/primary-button.spec.js
  packages/components/buttons/secondary-button/src/secondary-button.spec.js
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.spec.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/primary-action-dropdown/src/primary-action-dropdown.spec.js
  packages/components/table/src/base-table.spec.js
  packages/components/table/src/table.spec.js
  scripts/setup-test-framework.js
  src/components/fields/async-creatable-select-field/async-creatable-select-field.spec.js
  src/components/fields/async-select-field/async-select-field.spec.js
  src/components/fields/creatable-select-field/creatable-select-field.spec.js
  src/components/fields/date-field/date-field.spec.js
  src/components/fields/date-range-field/date-range-field.spec.js
  src/components/fields/date-time-field/date-time-field.spec.js
  src/components/fields/localized-multiline-text-field/localized-multiline-text-field.spec.js
  src/components/fields/localized-text-field/localized-text-field.spec.js
  src/components/fields/money-field/money-field.spec.js
  src/components/fields/multiline-text-field/multiline-text-field.spec.js
  src/components/fields/number-field/number-field.spec.js
  src/components/fields/password-field/password-field.spec.js
  src/components/fields/radio-field/radio-field.spec.js
  src/components/fields/select-field/select-field.spec.js
  src/components/fields/text-field/text-field.spec.js
  src/components/fields/time-field/time-field.spec.js
  src/components/inputs/checkbox-input/checkbox-input.spec.js
  src/components/inputs/date-input/date-input.spec.js
  src/components/inputs/date-range-input/date-range-input.spec.js
  src/components/inputs/date-time-input/date-time-input.spec.js
  src/components/inputs/localized-money-input/localized-money-input.spec.js
  src/components/inputs/localized-multiline-text-input/localized-multiline-text-input.spec.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.spec.js
  src/components/inputs/localized-text-input/localized-text-input.spec.js
  src/components/inputs/money-input/money-input.spec.js
  src/components/inputs/multiline-text-input/multiline-text-input.spec.js
  src/components/inputs/password-input/password-input.spec.js
  src/components/inputs/toggle-input/toggle-input.spec.js
  yarn.lock
Labels: 🙏 Status: Dev Review

#1386 feat(data-table): Sticky footer 🩹
  .changeset/big-onions-lie.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1394 refactor: tests to use `screen` where possible
  packages/components/accessible-hidden/src/accessible-hidden.spec.js
  packages/components/buttons/accessible-button/src/accessible-button.spec.js
  packages/components/buttons/flat-button/src/flat-button.spec.js
  packages/components/buttons/icon-button/src/icon-button.spec.js
  packages/components/buttons/link-button/src/link-button.spec.js
  packages/components/buttons/primary-button/src/primary-button.spec.js
  packages/components/buttons/secondary-button/src/secondary-button.spec.js
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.spec.js
  packages/components/card/src/card.spec.js
  packages/components/collapsible-motion/src/collapsible-motion.spec.js
  packages/components/collapsible-panel/src/collapsible-panel.spec.js
  packages/components/collapsible/src/collapsible.spec.js
  packages/components/constraints/src/horizontal/horizontal.spec.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/field-errors/src/field-errors.spec.js
  packages/components/field-label/src/field-label.spec.js
  packages/components/label/src/label.spec.js
  packages/components/label/src/required-indicator.spec.js
  packages/components/link/src/link.spec.js
  packages/components/loading-spinner/src/loading-spinner.spec.js
  packages/components/messages/src/error-message/error-message.spec.js
  packages/components/messages/src/warning-message/warning-message.spec.js
  packages/components/primary-action-dropdown/src/primary-action-dropdown.spec.js
  packages/components/stamp/src/stamp.spec.js
  packages/components/tag/src/tag.spec.js
  packages/components/tooltip/src/tooltip.spec.js
  packages/hooks/src/use-field-id/use-field-id.spec.js
  packages/hooks/src/use-previous/use-previous.spec.js
  packages/hooks/src/use-row-selection/use-row-selection.spec.js
  packages/hooks/src/use-toggle-state/use-toggle-state.spec.js
  src/components/inputs/checkbox-input/checkbox-input.spec.js
  src/components/inputs/localized-rich-text-input/localized-rich-text-input.spec.js
  src/components/inputs/money-input/money-input.spec.js
  src/components/inputs/multiline-text-input/multiline-text-input.spec.js
  src/components/inputs/radio-input/radio-input.spec.js
  src/components/inputs/rich-text-input/rich-text-input.spec.js
  src/components/inputs/toggle-input/toggle-input.spec.js
  src/components/spacings/inline/inline.spec.js
  src/components/spacings/inset-squish/inset-squish.spec.js
  src/components/spacings/inset/inset.spec.js
  src/components/spacings/stack/stack.spec.js
  src/components/typography/text/text.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1393 feat: add intlMessage to notification
  .changeset/lovely-planets-tell.md
  packages/components/notifications/package.json
  src/components/notifications/content-notification/README.md
  src/components/notifications/content-notification/content-notification.js
  src/components/notifications/content-notification/content-notification.spec.js
  src/components/notifications/content-notification/content-notification.visualroute.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1391 rich-text-inputs: Fix not-allowed cursor rendering on disabled rich text inputs
  .changeset/sixty-islands-poke.md
  src/components/inputs/localized-rich-text-input/editor.js
  src/components/inputs/localized-rich-text-input/editor.styles.js
  src/components/inputs/rich-text-input/editor.js
  src/components/inputs/rich-text-input/editor.styles.js
Labels: 🚀 Status: ship it

#1396 fix: storybook data-table example
  packages/components/data-table/src/data-table.story.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1388 feat(data-table): add new prop verticalCellAlignment
  .changeset/warm-grapes-dream.md
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-row.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.visualroute.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1401 fix(kodiak): to use blocking wording not blacklist
  .kodiak.toml
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it
