Repository commercetools/ui-kit, pull requests merged in 2020-04, with the labels that each got.

#1309 fix(data-table): move wrapHeaderLabel to become a table prop
  packages/components/data-table/README.md
  packages/components/data-table/index.js
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1308 chore(deps): lock file maintenance all dependencies
  .circleci/config.yml
  package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🚀 Status: ship it, 🤖 Type: Dependencies

#1310 fix(data-table): change background on hover only for clickable rows
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1312 fix(data-table): add footer prop
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
Labels: 🚀 Status: ship it

#1314 fix(data-table): remove onClick from column options
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.story.js
Labels: 🚀 Status: ship it

#1318 refactor(stamp): to support theme styles
  packages/components/stamp/src/stamp.js
Labels: ⛑ Type: Refactoring

#1319 fix(data-table): column cells not wrapping
  packages/components/data-table/src/cell.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1322 fix(data-table): add prop to disable header stickiness
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.story.js
Labels: 💅 Type: Enhancement, 🚀 Status: ship it

#1321 fix(data-table): add missing background color
  packages/components/data-table/src/data-table.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1328 chore(data-table): add visual regression tests
  packages/components/data-table/src/data-table.visualroute.js
  packages/components/data-table/src/data-table.visualspec.js
Labels: 👨‍⚕️ Type: Tests, 🚀 Status: ship it
