Repository commercetools/ui-kit, pull requests merged in 2020-03, with the labels that each got.

#1267 chore(storybook): sort stories alphabetically
  .storybook/config.js
  design-system/materials/internals/tokens.story.js
Labels: 🚀 Status: ship it

#1271 feat: add accessible-hidden component
  packages/components/accessible-hidden/LICENSE
  packages/components/accessible-hidden/README.md
  packages/components/accessible-hidden/index.js
  packages/components/accessible-hidden/package.json
  packages/components/accessible-hidden/src/accessible-hidden.js
  packages/components/accessible-hidden/src/accessible-hidden.spec.js
  packages/components/accessible-hidden/src/index.js
  packages/components/accessible-hidden/src/version.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1272 fix(collapsible-panel): improve accessibility
  packages/components/buttons/accessible-button/package.json
  packages/components/buttons/accessible-button/src/accessible-button.js
  packages/components/buttons/accessible-button/src/accessible-button.styles.js
  packages/components/buttons/accessible-button/src/index.js
  packages/components/collapsible-panel/README.md
  packages/components/collapsible-panel/package.json
  packages/components/collapsible-panel/src/collapsible-panel.js
  packages/components/collapsible-panel/src/collapsible-panel.spec.js
  packages/components/collapsible-panel/src/collapsible-panel.styles.js
  rollup.config.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1233 [UKIT-96] feat(table): add new component DataTable
  package.json
  packages/components/data-table/LICENSE
  packages/components/data-table/README.md
  packages/components/data-table/index.js
  packages/components/data-table/package.json
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
  packages/components/data-table/src/data-table.spec.js
  packages/components/data-table/src/data-table.story.js
  packages/components/data-table/src/data-table.styles.js
  packages/components/data-table/src/index.js
  packages/components/data-table/src/version.js
  packages/hooks/package.json
  src/hooks/index.js
  src/hooks/use-row-selection/index.js
  src/hooks/use-row-selection/use-row-selection.js
  src/hooks/use-row-selection/use-row-selection.spec.js
  src/hooks/use-sorting/index.js
  src/hooks/use-sorting/use-sorting.js
  src/hooks/use-sorting/use-sorting.spec.js
  yarn.lock
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1278 chore(card): fix documentation and small refactor
  packages/components/card/README.md
  packages/components/card/src/card.js
Labels: ⛑ Type: Refactoring, 🔮 Type: Chore, 🚀 Status: ship it

#1283 fix(collapsible-panel): Accessible panel Header element
  packages/components/buttons/accessible-button/src/accessible-button.js
  packages/components/buttons/accessible-button/src/accessible-button.spec.js
  packages/components/collapsible-panel/src/collapsible-panel.js
  packages/components/collapsible-panel/src/collapsible-panel.spec.js
  packages/components/collapsible-panel/src/collapsible-panel.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1285 fix(collapsible-panel): to forward data-attributes
  packages/components/collapsible-panel/src/collapsible-panel.js
  packages/components/collapsible-panel/src/collapsible-panel.spec.js
Labels: 🐛 Type: Bug

#1287 fix(accessible-button): fix no-outline rule for button elements
  packages/components/buttons/accessible-button/src/accessible-button.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1288 chore(presets/ui-kit): add new components and hooks to ui-kit preset
  presets/ui-kit/index.js
  presets/ui-kit/package.json
  yarn.lock
Labels: 🚀 Status: ship it

#1289 docs(changelog): for release v10.18.2 [skip ci]
  CHANGELOG.md
Labels: 🚀 Status: ship it

#1290 fix(presets): data-table export in presets/ui-kit
  presets/ui-kit/index.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1291 fix(presets): hooks export
  presets/ui-kit/index.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1292 [UKIT-110] fix(field-label): adjust hint text and icon alignment
  src/components/field-label/field-label.js
Labels: 🚀 Status: ship it

#1293 fix(data-table): only clip cells with isTruncated option
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1294 docs(changelog): for release v10.18.3 [skip ci]
  CHANGELOG.md
Labels: 🔮 Type: Chore

#1298 chore(deps): lock file maintenance all dependencies
  package.json
  packages/components/buttons/accessible-button/package.json
  packages/components/data-table/package.json
  packages/components/inputs/async-creatable-select-input/package.json
  packages/components/inputs/async-select-input/package.json
  packages/components/inputs/creatable-select-input/package.json
  packages/components/inputs/date-input/package.json
  packages/components/inputs/date-range-input/package.json
  packages/components/inputs/date-time-input/package.json
  packages/components/inputs/localized-money-input/package.json
  packages/components/inputs/localized-multiline-text-input/package.json
  packages/components/inputs/localized-rich-text-input/package.json
  packages/components/inputs/money-input/package.json
  packages/components/inputs/multiline-text-input/package.json
  packages/components/inputs/radio-input/package.json
  packages/components/inputs/rich-text-input/package.json
  packages/components/inputs/select-input/package.json
  packages/components/inputs/select-utils/package.json
  packages/components/inputs/time-input/package.json
  packages/components/tooltip/package.json
  packages/utils/package.json
  visual-testing-app/package.json
  yarn.lock
Labels: 🤖 Type: Dependencies

#1299 [UKIT-110] fix(password-field): show password button alignment
  src/components/fields/password-field/password-field.js
  src/components/fields/password-field/password-field.visualroute.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1301 fix(data-table): return sortDirection in onSortChange
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1304 fix(data-table): normalize z-index
  packages/components/data-table/src/data-table.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1305 fix(data-table): allow disabling text wrap for column header label
  packages/components/data-table/README.md
  packages/components/data-table/src/cell.js
  packages/components/data-table/src/cell.styles.js
  packages/components/data-table/src/data-table.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature
