Repository commercetools/ui-kit, pull requests merged in 2020-10, with the labels that each got.

#1590 fix: localized inputs to avoid re-mounts when localization control is toggled
  .changeset/chilly-maps-knock.md
  .changeset/tall-apples-explain.md
  packages/components/inputs/localized-money-input/src/currency-control.js
  packages/components/inputs/localized-money-input/src/localized-money-input.js
  packages/components/inputs/localized-multiline-text-input/src/languages-control.js
  packages/components/inputs/localized-multiline-text-input/src/localized-multiline-text-input.js
  packages/components/inputs/localized-multiline-text-input/src/translation-input.js
  packages/components/inputs/localized-multiline-text-input/src/translation-input.styles.js
  packages/components/inputs/localized-rich-text-input/src/editor.js
  packages/components/inputs/localized-rich-text-input/src/editor.styles.js
  packages/components/inputs/localized-rich-text-input/src/languages-control.js
  packages/components/inputs/localized-rich-text-input/src/localized-rich-text-input.js
  packages/components/inputs/localized-rich-text-input/src/rich-text-input.js
  packages/components/inputs/localized-text-input/src/languages-button.js
  packages/components/inputs/localized-text-input/src/localized-text-input.js
  src/components/internals/localized-input-toggle/index.js
  src/components/internals/localized-input-toggle/localized-input-toggle.js
  src/components/internals/localized-input-toggle/localized-input-toggle.spec.js
Labels: 🚀 Status: ship it

#1608 fix(collapsible-motion): make content effectively invisible when collapsed
  .changeset/plenty-pianos-bow.md
  packages/components/collapsible-motion/src/collapsible-motion.js
  packages/components/collapsible-motion/src/collapsible-motion.spec.js
Labels: 🚀 Status: ship it

#1612 fix(search-select-input): fix isDisabled and isReadOnly states
  .changeset/witty-experts-hide.md
  packages/components/inputs/search-select-input/src/search-select-input.js
  packages/components/inputs/search-select-input/src/search-select-input.styles.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1604 Introduce SearchSelectField to the field components
  .changeset/config.json
  .changeset/nervous-moose-pump.md
  packages/components/fields/search-select-field/LICENSE
  packages/components/fields/search-select-field/README.md
  packages/components/fields/search-select-field/docs/additional-info.md
  packages/components/fields/search-select-field/docs/usage-example.js
  packages/components/fields/search-select-field/index.js
  packages/components/fields/search-select-field/package.json
  packages/components/fields/search-select-field/src/index.js
  packages/components/fields/search-select-field/src/search-select-field.form.story.js
  packages/components/fields/search-select-field/src/search-select-field.js
  packages/components/fields/search-select-field/src/search-select-field.spec.js
  packages/components/fields/search-select-field/src/search-select-field.story.js
  packages/components/fields/search-select-field/src/search-select-field.visualroute.js
  packages/components/fields/search-select-field/src/search-select-field.visualspec.js
  packages/components/fields/search-select-field/src/version.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1615 Improve readmes
  .changeset/healthy-onions-lick.md
  .changeset/nine-emus-yawn.md
  .changeset/ninety-eyes-bow.md
  .eslintrc.yaml
  package.json
  packages/components/avatar/README.md
  packages/components/avatar/src/avatar.js
  packages/components/stamp/README.md
  packages/components/stamp/docs/usage-example.js
  packages/components/stamp/src/stamp.js
  packages/components/tooltip/README.md
  packages/components/tooltip/docs/usage-example.js
  packages/components/tooltip/package.json
  packages/components/tooltip/src/tooltip.js
Labels: ✍️ Type: Documentation

#1619 Mw fix search select field option type
  .changeset/cuddly-beers-sit.md
  packages/components/fields/search-select-field/src/search-select-field.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1605 fix(date-inputs): to not open date picker as the input gets focused by the keyboard
  .changeset/spotty-eyes-pay.md
  packages/components/fields/date-field/src/date-field.spec.js
  packages/components/fields/date-range-field/src/date-range-field.spec.js
  packages/components/fields/date-time-field/src/date-time-field.spec.js
  packages/components/inputs/date-input/src/date-input.js
  packages/components/inputs/date-input/src/date-input.spec.js
  packages/components/inputs/date-input/src/date-input.story.js
  packages/components/inputs/date-range-input/src/date-range-input.js
  packages/components/inputs/date-range-input/src/date-range-input.spec.js
  packages/components/inputs/date-time-input/src/date-time-input.js
  packages/components/inputs/date-time-input/src/date-time-input.spec.js
Labels: 🚀 Status: ship it

#1622 chore(storybook): add google-analytics to Storybook
  .storybook/addons.js
  .storybook/manager-head.html
  package.json
  yarn.lock
Labels: 🚀 Status: ship it

#1633 feat(icons): add new ClockWithArrow icon
  .changeset/wet-knives-help.md
  packages/components/icons/src/components/clock-with-arrow.js
  packages/components/icons/src/index.js
  packages/components/icons/src/raw-components/clock-with-arrow.js
  packages/components/icons/src/svg/clock-with-arrow.react.svg
  transforms/v10/icons/icon-names.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1638 Add isCondensed prop to the Stamp component
  .changeset/stale-guests-rhyme.md
  packages/components/fields/search-select-field/README.md
  packages/components/stamp/README.md
  packages/components/stamp/package.json
  packages/components/stamp/src/stamp.js
  packages/components/stamp/src/stamp.story.js
  packages/components/stamp/src/stamp.visualroute.js
Labels: 🚀 Status: ship it, 🚀 Type: New Feature
