Repository commercetools/ui-kit, pull requests merged in 2020-09, with the labels that each got.

#1541 Chore: Group select inputs and fields in the storybook
  .changeset/bright-ants-grow.md
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.form.story.js
  packages/components/fields/async-creatable-select-field/src/async-creatable-select-field.story.js
  packages/components/fields/async-select-field/src/async-select-field.form.story.js
  packages/components/fields/async-select-field/src/async-select-field.story.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.form.story.js
  packages/components/fields/creatable-select-field/src/creatable-select-field.story.js
  packages/components/fields/select-field/src/select-field.form.story.js
  packages/components/fields/select-field/src/select-field.story.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.form.story.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.story.js
  packages/components/inputs/async-select-input/src/async-select-input.form.story.js
  packages/components/inputs/async-select-input/src/async-select-input.story.js
  packages/components/inputs/creatable-select-input/src/creatable-select-input.form.story.js
  packages/components/inputs/creatable-select-input/src/creatable-select-input.story.js
  packages/components/inputs/select-input/src/select-input.form.story.js
  packages/components/inputs/select-input/src/select-input.story.js
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1549 feat: to add table icon to data-table-manager dropdown
  .changeset/gorgeous-poets-cry.md
  packages/components/data-table-manager/src/data-table-settings/data-table-settings.js
Labels: 🚀 Status: ship it

#1550 style: fix typo on `authorized`
  .changeset/strong-dots-refuse.md
  packages/components/fields/date-field/README.md
  packages/components/fields/date-field/src/date-field.js
  packages/components/fields/date-range-field/README.md
  packages/components/fields/date-range-field/src/date-range-field.js
  packages/components/fields/date-time-field/README.md
  packages/components/fields/date-time-field/src/date-time-field.js
  packages/components/fields/localized-multiline-text-field/README.md
  packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.js
  packages/components/fields/localized-text-field/README.md
  packages/components/fields/localized-text-field/src/localized-text-field.js
  packages/components/fields/money-field/README.md
  packages/components/fields/money-field/src/money-field.js
  packages/components/fields/multiline-text-field/README.md
  packages/components/fields/multiline-text-field/src/multiline-text-field.js
  packages/components/fields/number-field/README.md
  packages/components/fields/number-field/src/number-field.js
  packages/components/fields/password-field/README.md
  packages/components/fields/password-field/src/password-field.js
  packages/components/fields/radio-field/README.md
  packages/components/fields/radio-field/src/radio-field.js
  packages/components/fields/text-field/README.md
  packages/components/fields/text-field/src/text-field.js
  packages/components/fields/time-field/README.md
  packages/components/fields/time-field/src/time-field.js
  packages/components/inputs/date-input/README.md
  packages/components/inputs/money-input/README.md
  packages/components/inputs/money-input/src/money-input.js
  packages/components/inputs/multiline-text-input/README.md
  packages/components/inputs/multiline-text-input/src/multiline-text-input.js
  packages/components/inputs/number-input/README.md
  packages/components/inputs/number-input/src/number-input.js
  packages/components/inputs/text-input/README.md
  packages/components/inputs/text-input/src/text-input.js
  packages/components/inputs/time-input/README.md
  packages/components/inputs/time-input/src/time-input.js
Labels: 🚀 Status: ship it

#1551 fix(number-input): restore xs as a possible value for horizontalConstraint
  .changeset/moody-guests-compete.md
  packages/components/inputs/number-input/README.md
  packages/components/inputs/number-input/src/number-input.js
Labels: 🚀 Status: ship it

#1553 fix: restore horizontal constraint
  .changeset/seven-vans-destroy.md
  packages/components/fields/date-field/README.md
  packages/components/fields/date-field/src/date-field.js
  packages/components/fields/date-range-field/README.md
  packages/components/fields/date-range-field/src/date-range-field.js
  packages/components/fields/date-time-field/README.md
  packages/components/fields/date-time-field/src/date-time-field.js
  packages/components/fields/localized-multiline-text-field/README.md
  packages/components/fields/localized-multiline-text-field/src/localized-multiline-text-field.js
  packages/components/fields/localized-text-field/README.md
  packages/components/fields/localized-text-field/src/localized-text-field.js
  packages/components/fields/multiline-text-field/README.md
  packages/components/fields/multiline-text-field/src/multiline-text-field.js
  packages/components/inputs/localized-text-input/README.md
  packages/components/inputs/localized-text-input/src/localized-text-input.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1556 fix(select-field): restore 'touched' prop-type validation for isMulti
  .changeset/beige-spies-joke.md
  packages/components/fields/select-field/README.md
  packages/components/fields/select-field/src/select-field.js
Labels: 🚀 Status: ship it

#1555 select-utils: add SearchIconDropdownIndicator and custom select option types
  .changeset/thick-kids-clean.md
  packages/components/inputs/select-utils/index.js
  packages/components/inputs/select-utils/package.json
  src/components/internals/custom-styled-select-options/constants.js
  src/components/internals/custom-styled-select-options/custom-styled-select-options.js
  src/components/internals/custom-styled-select-options/index.js
  src/components/internals/search-icon-dropdown-indicator/index.js
  src/components/internals/search-icon-dropdown-indicator/search-icon-dropdown-indicator.js
Labels: 🚀 Status: ship it

#1554 Add loadingMessage prop to asyc-select input and field components
  .changeset/weak-yaks-cover.md
  packages/components/fields/async-select-field/README.md
  packages/components/fields/async-select-field/src/async-select-field.js
  packages/components/fields/async-select-field/src/async-select-field.story.js
  packages/components/inputs/async-select-input/README.md
  packages/components/inputs/async-select-input/src/async-select-input.js
  packages/components/inputs/async-select-input/src/async-select-input.story.js
  src/components/internals/messages/select/messages.js
Labels: 🚀 Status: ship it

#1558 fix(icon): to prevent icon from shrinking inside of flex container
  .changeset/little-items-press.md
  src/components/internals/icons/create-styled-icon.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1539 fix(inputs): hover and accessible focus styles
  .changeset/weak-teachers-greet.md
  packages/calendar-utils/package.json
  packages/components/fields/money-field/src/money-field.spec.js
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.js
  packages/components/inputs/async-select-input/src/async-select-input.js
  packages/components/inputs/checkbox-input/src/checkbox-input.js
  packages/components/inputs/checkbox-input/src/checkbox-input.styles.js
  packages/components/inputs/creatable-select-input/src/creatable-select-input.js
  packages/components/inputs/date-input/package.json
  packages/components/inputs/date-range-input/package.json
  packages/components/inputs/date-time-input/package.json
  packages/components/inputs/localized-rich-text-input/src/editor.js
  packages/components/inputs/money-input/src/money-input.js
  packages/components/inputs/money-input/src/money-input.spec.js
  packages/components/inputs/radio-input/src/radio-input.visualroute.js
  packages/components/inputs/radio-input/src/radio-option.js
  packages/components/inputs/radio-input/src/radio-option.styles.js
  packages/components/inputs/rich-text-input/src/editor.js
  packages/components/inputs/rich-text-input/src/editor.styles.js
  packages/components/inputs/select-input/src/select-input.js
  packages/components/inputs/styles.js
  packages/components/inputs/time-input/package.json
  packages/components/inputs/time-input/src/time-input-body.js
  packages/components/inputs/time-input/src/time-input-body.styles.js
  packages/components/inputs/toggle-input/src/toggle-input.js
  src/components/internals/calendar-body/calendar-body.js
  src/components/internals/calendar-body/calendar-body.styles.js
  src/components/internals/clear-indicator/clear-indicator.js
  src/components/internals/create-select-styles.js
  src/components/internals/rich-text-body/hidden-input.js
  src/components/internals/rich-text-body/rich-text-body.styles.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1569 chore: ignore storybook updates
  .renovaterc.json
Labels: 🚀 Status: ship it

#1570 chore: add focus/hover changeset to missing inputs and fields
  .changeset/mean-hornets-explode.md
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1566 feat(data-table-manager): add prop `managerTheme`
  .changeset/spotty-dancers-lie.md
  packages/components/data-table-manager/README.md
  packages/components/data-table-manager/package.json
  packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.js
  packages/components/data-table-manager/src/data-table-manager.js
  packages/components/data-table-manager/src/data-table-manager.story.js
  packages/components/data-table-manager/src/data-table-settings/data-table-settings.js
  packages/components/data-table-manager/src/display-settings-manager/display-settings-manager.js
  packages/components/data-table-manager/src/settings-container/settings-container.js
Labels: 🚀 Status: ship it

#1565 fix(select-input): focusing on remove button for options when isMulti enabled
  .changeset/purple-clocks-study.md
  packages/components/inputs/async-creatable-select-input/src/async-creatable-select-input.js
  packages/components/inputs/select-utils/package.json
  src/components/internals/create-select-styles.js
  src/components/internals/tag-remove/tag-remove.js
Labels: 🚀 Status: ship it

#1586 Rename select input option types
  .changeset/sharp-garlics-explode.md
  src/components/internals/custom-styled-select-options/constants.js
  src/components/internals/custom-styled-select-options/custom-styled-select-options.js
Labels: 🚀 Status: ship it

#1589 test(data-table-manager): improve tests
  packages/components/data-table-manager/src/column-settings-manager/column-settings-manager.js
  packages/components/data-table-manager/src/data-table-manager.spec.js
Labels: 🚀 Status: ship it

#1591 chore(data-table-manager): update docs to be consistent with translated copy
  packages/components/data-table-manager/README.md
  packages/components/data-table-manager/docs/description.md
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1592 chore(time-input): add documentation for toLocaleTime
  packages/components/inputs/time-input/README.md
  packages/components/inputs/time-input/docs/additional-info.md
  packages/components/inputs/time-input/src/time-input.js
Labels: 🚀 Status: ship it

#1576 fix: date picker keyboard arrow navigation
  .changeset/rotten-hairs-accept.md
  packages/calendar-time-utils/src/calendar-time.js
  packages/calendar-utils/src/calendar.js
  packages/components/inputs/date-input/src/date-input.js
  packages/components/inputs/date-input/src/date-input.spec.js
  packages/components/inputs/date-range-input/src/date-range-input.js
  packages/components/inputs/date-range-input/src/date-range-input.spec.js
  packages/components/inputs/date-time-input/src/date-time-input.js
  packages/components/inputs/date-time-input/src/date-time-input.spec.js
  src/components/internals/calendar-body/calendar-body.js
Labels: 🚀 Status: ship it

#1594 fix(time-input): to add proper hover style and remove leftovers
  .changeset/spotty-ads-smash.md
  packages/components/inputs/time-input/src/time-input-body.styles.js
Labels: 🚀 Status: ship it

#1564 Feat: Add SearchSelectInput component
  .changeset/kind-bottles-check.md
  packages/components/inputs/search-select-input/LICENSE
  packages/components/inputs/search-select-input/README.md
  packages/components/inputs/search-select-input/docs/additional-info.md
  packages/components/inputs/search-select-input/docs/usage-example.js
  packages/components/inputs/search-select-input/index.js
  packages/components/inputs/search-select-input/package.json
  packages/components/inputs/search-select-input/src/index.js
  packages/components/inputs/search-select-input/src/messages.js
  packages/components/inputs/search-select-input/src/search-select-input-open.visualroute.js
  packages/components/inputs/search-select-input/src/search-select-input.form.story.js
  packages/components/inputs/search-select-input/src/search-select-input.js
  packages/components/inputs/search-select-input/src/search-select-input.spec.js
  packages/components/inputs/search-select-input/src/search-select-input.story.js
  packages/components/inputs/search-select-input/src/search-select-input.styles.js
  packages/components/inputs/search-select-input/src/search-select-input.visualroute.js
  packages/components/inputs/search-select-input/src/search-select-input.visualspec.js
  packages/components/inputs/search-select-input/src/version.js
  packages/i18n/data/core.json
Labels: 🚀 Status: ship it, 🚀 Type: New Feature

#1598 fix(text): text-body not applying theme when rendered as "span"
  .changeset/late-days-drum.md
  packages/components/text/src/text.js
  packages/components/text/src/text.visualroute.js
Labels: 🚀 Status: ship it

#1597 fix(checkbox-input): type of label element to allow more nesting
  .changeset/lucky-teachers-listen.md
  packages/components/inputs/checkbox-input/README.md
  packages/components/inputs/checkbox-input/docs/additional-info.md
  packages/components/inputs/checkbox-input/docs/usage-example.js
  packages/components/inputs/checkbox-input/package.json
  packages/components/inputs/checkbox-input/src/checkbox-input.js
  packages/components/inputs/checkbox-input/src/checkbox.js
Labels: 🚀 Status: ship it

#1600 Add SearchSelectInput to the input presets list
  .changeset/config.json
  .changeset/sweet-pants-tell.md
  presets/inputs/index.js
  presets/inputs/package.json
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1602 Fix prop-types validation for optionType prop of SearchSelectInput
  .changeset/light-jokes-mate.md
  packages/components/inputs/search-select-input/README.md
  packages/components/inputs/search-select-input/src/search-select-input.js
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1603 fix(data-table-manager): remove width constraint
  .changeset/thick-tools-protect.md
  packages/components/data-table-manager/package.json
  packages/components/data-table-manager/src/settings-container/settings-container.js
Labels: 🚀 Status: ship it
