Repository commercetools/ui-kit, pull requests merged in 2021-05, with the labels that each got.

#1885 fix(buttons): use `ComponentType` on `as` prop
  .changeset/giant-candles-sneeze.md
  packages/components/buttons/flat-button/README.md
  packages/components/buttons/flat-button/src/flat-button.tsx
  packages/components/buttons/icon-button/README.md
  packages/components/buttons/icon-button/src/icon-button.tsx
  packages/components/buttons/primary-button/README.md
  packages/components/buttons/primary-button/src/primary-button.tsx
  packages/components/buttons/secondary-button/src/secondary-button.tsx
  packages/components/buttons/secondary-icon-button/README.md
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.tsx
Labels: 🐛 Type: Bug

#1887 fix(components): set text-input.onChange option, update to prop to use Location
  .changeset/great-pumpkins-fry.md
  .changeset/wild-elephants-hug.md
  packages/components/buttons/secondary-button/src/secondary-button.tsx
  packages/components/inputs/text-input/src/text-input.tsx
Labels: 🐛 Type: Bug

#1890 fix: primary-button, onClick is required when `as` is `undefined`
  .changeset/orange-numbers-deny.md
  packages/components/buttons/primary-button/src/primary-button.tsx
Labels: 🐛 Type: Bug

#1892 export component prop-types
  .changeset/loud-boats-speak.md
  .changeset/short-apes-work.md
  .changeset/silent-onions-deliver.md
  .changeset/yellow-chefs-wash.md
  packages/components/inputs/input-utils/src/localized-input-toggle/index.ts
  packages/components/inputs/input-utils/src/localized-input-toggle/localized-input-toggle.tsx
  packages/components/inputs/input-utils/src/multiline-input/index.ts
  packages/components/inputs/multiline-text-input/src/index.ts
  packages/components/inputs/multiline-text-input/src/multiline-text-input.tsx
  packages/components/inputs/number-input/src/index.ts
  packages/components/inputs/number-input/src/number-input.tsx
  packages/components/inputs/password-input/src/index.ts
  packages/components/inputs/password-input/src/password-input.tsx
  packages/components/inputs/text-input/README.md
  packages/components/inputs/text-input/src/index.ts
  packages/components/inputs/text-input/src/text-input.tsx
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1888 Migrate Tag component to Typescript
  .changeset/sharp-pens-dance.md
  packages/components/tag/README.md
  packages/components/tag/index.ts
  packages/components/tag/src/index.js
  packages/components/tag/src/index.ts
  packages/components/tag/src/tag-body.tsx
  packages/components/tag/src/tag.tsx
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1903 refactor(avatar): convert to `TypeScript`
  .changeset/thick-ties-carry.md
  packages/components/avatar/index.ts
  packages/components/avatar/package.json
  packages/components/avatar/src/avatar.tsx
  packages/components/avatar/src/index.js
  packages/components/avatar/src/index.ts
  packages/components/avatar/src/version.ts
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it

#1909 refactor(collapsible): migrate to TypeScript
  .changeset/cool-jeans-enjoy.md
  packages/components/collapsible/README.md
  packages/components/collapsible/index.ts
  packages/components/collapsible/src/collapsible.spec.tsx
  packages/components/collapsible/src/collapsible.tsx
  packages/components/collapsible/src/index.ts
  packages/components/collapsible/src/version.ts
  packages/components/field-label/README.md
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#1869 refactor(toggle-input): use TypeScript
  .changeset/twelve-boats-rush.md
  jest.test.config.js
  packages/components/inputs/toggle-input/README.md
  packages/components/inputs/toggle-input/docs/additional-info.md
  packages/components/inputs/toggle-input/docs/usage-example.js
  packages/components/inputs/toggle-input/index.ts
  packages/components/inputs/toggle-input/package.json
  packages/components/inputs/toggle-input/src/index.ts
  packages/components/inputs/toggle-input/src/toggle-input.spec.tsx
  packages/components/inputs/toggle-input/src/toggle-input.tsx
  packages/components/inputs/toggle-input/src/version.ts
Labels: ⛑ Type: Refactoring, 🖐 Status: On Hold, 🙏 Status: Dev Review

#1871 refactor(checkbox-input): migrate to TypeScript
  .changeset/tame-boats-leave.md
  packages/components/inputs/checkbox-input/README.md
  packages/components/inputs/checkbox-input/index.ts
  packages/components/inputs/checkbox-input/src/checkbox-input.spec.tsx
  packages/components/inputs/checkbox-input/src/checkbox-input.styles.ts
  packages/components/inputs/checkbox-input/src/checkbox-input.tsx
  packages/components/inputs/checkbox-input/src/checkbox.tsx
  packages/components/inputs/checkbox-input/src/index.ts
  packages/components/inputs/checkbox-input/src/version.ts
Labels: ⛑ Type: Refactoring, 🖐 Status: On Hold, 🙏 Status: Dev Review
