Repository commercetools/ui-kit, pull requests merged in 2021-03, with the labels that each got.

#1804 refactor(packages/card): migrate Card to typescript
  .changeset/proud-forks-relax.md
  packages/components/card/README.md
  packages/components/card/src/card.spec.tsx
  packages/components/card/src/card.tsx
  packages/components/card/src/index.ts
  packages/components/card/src/version.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1810 chore(docs): add prism@1.23.0 as peer
  docs/package.json
  docs/yarn.lock
Labels: 🔮 Type: Chore

#1809 refactor: to remove lerna and only use manypkg
  .gitignore
  jest-puppeteer.config.js
  lerna.json
  package.json
  yarn.lock
Labels: 🙏 Status: Dev Review

#1811 feat: to add a `primary` and `inverted` tone to the `link` component
  .changeset/tall-ladybugs-tan.md
  packages/components/link/README.md
  packages/components/link/src/link.js
  packages/components/link/src/link.story.js
  packages/components/link/src/link.visualroute.js
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review

#1786 refactor(accessible-button): to typescript
  .changeset/dry-schools-heal.md
  generators/readme/src/index.ts
  generators/readme/test/generate-readme.spec.ts
  packages/components/buttons/accessible-button/README.md
  packages/components/buttons/accessible-button/docs_disabled/additional-info.md
  packages/components/buttons/accessible-button/docs_disabled/usage-example.js
  packages/components/buttons/accessible-button/index.ts
  packages/components/buttons/accessible-button/package.json
  packages/components/buttons/accessible-button/src/accessible-button.js
  packages/components/buttons/accessible-button/src/accessible-button.styles.ts
  packages/components/buttons/accessible-button/src/accessible-button.tsx
  packages/components/buttons/accessible-button/src/index.ts
  packages/components/buttons/accessible-button/src/version.ts
  packages/localized-utils/src/localized.spec.ts
  packages/localized-utils/src/localized.ts
  packages/utils/src/warning.ts
  yarn.lock
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1814 feat(Card): make inset spacing configurable
  .changeset/strong-bugs-tickle.md
  packages/components/card/README.md
  packages/components/card/package.json
  packages/components/card/src/card.story.js
  packages/components/card/src/card.tsx
  packages/components/card/src/card.visualroute.js
  packages/components/card/src/card.visualspec.js
Labels: 👨‍🎨 Status: UI/UX Review, 🙏 Status: Dev Review, 🚀 Status: ship it

#1773 refactor(components/loading-spinner): use typescript
  .changeset/violet-dolphins-carry.md
  packages/components/loading-spinner/README.md
  packages/components/loading-spinner/index.ts
  packages/components/loading-spinner/src/index.ts
  packages/components/loading-spinner/src/loading-spinner.tsx
  packages/components/loading-spinner/src/version.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1827 refactor(components): remove `Table`
  .changeset/great-cameras-sell.md
  packages/components/table/CHANGELOG.md
  packages/components/table/LICENSE
  packages/components/table/README.md
  packages/components/table/index.js
  packages/components/table/package.json
  packages/components/table/src/base-table.js
  packages/components/table/src/cell-range-renderer.js
  packages/components/table/src/cell.js
  packages/components/table/src/index.js
  packages/components/table/src/sortable-header.js
  packages/components/table/src/table.js
  packages/components/table/src/table.story.js
  packages/components/table/src/version.js
  presets/ui-kit/src/index.js
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1826 refactor(link): remove `hasUnderline`
  .changeset/two-months-obey.md
  packages/components/link/README.md
  packages/components/link/src/link.js
  packages/components/link/src/link.story.js
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1824 refactor(text): remove deprecated props
  .changeset/smooth-spoons-walk.md
  packages/components/text/README.md
  packages/components/text/src/text.styles.ts
  packages/components/text/src/text.tsx
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1825 docs(rich-text): remove beta
  .changeset/eleven-meals-remain.md
  packages/components/inputs/localized-rich-text-input/README.md
  packages/components/inputs/rich-text-input/README.md
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1830 refactor(secondary-button): remove `linkTo` from component
  .changeset/eleven-meals-remain.md
  .changeset/great-cameras-sell.md
  .changeset/mean-tools-travel.md
  .changeset/smooth-spoons-walk.md
  .changeset/two-months-obey.md
  packages/components/buttons/secondary-button/README.md
  packages/components/buttons/secondary-button/src/secondary-button.js
  packages/components/buttons/secondary-button/src/secondary-button.spec.js
  packages/components/buttons/secondary-button/src/secondary-button.story.js
  packages/components/buttons/secondary-button/src/secondary-button.visualroute.js
  packages/components/inputs/localized-rich-text-input/README.md
  packages/components/inputs/rich-text-input/README.md
  packages/components/link/README.md
  packages/components/link/src/link.js
  packages/components/link/src/link.story.js
  packages/components/table/CHANGELOG.md
  packages/components/table/LICENSE
  packages/components/table/README.md
  packages/components/table/index.js
  packages/components/table/package.json
  packages/components/table/src/base-table.js
  packages/components/table/src/cell-range-renderer.js
  packages/components/table/src/cell.js
  packages/components/table/src/index.js
  packages/components/table/src/sortable-header.js
  packages/components/table/src/table.js
  packages/components/table/src/table.story.js
  packages/components/table/src/version.js
  packages/components/tag/README.md
  packages/components/tag/docs/usage-example.js
  packages/components/tag/src/tag.js
  packages/components/tag/src/tag.spec.js
  packages/components/tag/src/tag.story.js
  packages/components/tag/src/tag.visualroute.js
  packages/components/text/README.md
  packages/components/text/src/text.styles.ts
  packages/components/text/src/text.tsx
  presets/ui-kit/src/index.js
Labels: ⛑ Type: Refactoring, 💥 Type: Breaking Change

#1836 add Changesets for dependency updates
  .changeset/loud-geese-share.md
Labels: 🔮 Type: Chore

#1840 refactor(page-navigator): use formik state
  .changeset/unlucky-mirrors-argue.md
  package.json
  packages/components/data-table-manager/package.json
  packages/components/data-table/package.json
  packages/components/pagination/package.json
  packages/components/pagination/src/page-navigator/page-navigator.js
  packages/components/pagination/src/pagination.spec.js
  yarn.lock
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1842 Add pagination and table sorting state
  .changeset/slow-grapes-hope.md
  packages/hooks/package.json
  packages/hooks/src/index.js
  packages/hooks/src/use-data-table-sorting-state/index.js
  packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.js
  packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.spec.js
  packages/hooks/src/use-pagination-state/index.js
  packages/hooks/src/use-pagination-state/use-pagination-state.js
  packages/hooks/src/use-pagination-state/use-pagination-state.spec.js
Labels: 🙏 Status: Dev Review, 🚀 Status: ship it, 🚀 Type: New Feature
