Repository commercetools/ui-kit, pull requests merged in 2021-02, with the labels that each got.

#1762 fix(text): add `inverted` as accepted prop for Text.Body
  .changeset/flat-experts-matter.md
  packages/components/text/src/text.tsx
Labels: 🌊 Resolution: Wont Fix, 🚀 Status: ship it

#1770 feat(pagination-story): add range selector and derive a minimum page size
  .changeset/sixty-jobs-decide.md
  packages/components/pagination/src/pagination.story.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1774 feat(icons): add new list with search icon
  .changeset/wet-snails-flash.md
  packages/components/icons/src/generated/ListWithSearch.tsx
  packages/components/icons/src/generated/index.tsx
  packages/components/icons/src/icons.visualroute.js
  packages/components/icons/src/svg/list-with-search.svg
  transforms/v10/icons/icon-names.js
Labels: 🚀 Type: New Feature

#1775 fix(text): use internal invariant, do not throw on production
  .changeset/rich-pandas-collect.md
  packages/components/text/package.json
  packages/components/text/src/text.spec.js
  packages/components/text/src/text.tsx
  packages/utils/src/index.ts
  packages/utils/src/invariant.ts
Labels: 🐛 Type: Bug, 🚀 Status: ship it

#1772 refactor(components/messages): migrate to typescript
  .changeset/fifty-dragons-tie.md
  packages/components/messages/index.ts
  packages/components/messages/package.json
  packages/components/messages/src/error-message/error-message.js
  packages/components/messages/src/error-message/error-message.tsx
  packages/components/messages/src/error-message/index.ts
  packages/components/messages/src/index.ts
  packages/components/messages/src/version.ts
  packages/components/messages/src/warning-message/index.ts
  packages/components/messages/src/warning-message/warning-message.js
  packages/components/messages/src/warning-message/warning-message.tsx
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1771 refactor(components/label): migrate to typescript
  .changeset/chatty-hats-unite.md
  packages/components/label/index.ts
  packages/components/label/package.json
  packages/components/label/src/index.ts
  packages/components/label/src/label.js
  packages/components/label/src/label.spec.js
  packages/components/label/src/label.tsx
  packages/components/label/src/required-indicator.tsx
  packages/components/label/src/version.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1791 fix(icons): list with search export
  .changeset/hip-foxes-switch.md
  packages/components/icons/src/generated/ListWithSearchReact.tsx
  packages/components/icons/src/generated/index.tsx
  packages/components/icons/src/svg/list-with-search.react.svg
Labels: 🐛 Type: Bug, 🙏 Status: Dev Review

#1794 pagination revert prop naming
  .changeset/neat-experts-admire.md
  packages/components/pagination/README.md
  packages/components/pagination/docs/usage-example.js
  packages/components/pagination/src/page-navigator/page-navigator.js
  packages/components/pagination/src/page-size-selector/page-size-selector.js
  packages/components/pagination/src/pagination.js
  packages/components/pagination/src/pagination.spec.js
  packages/components/pagination/src/pagination.story.js
  packages/components/pagination/src/pagination.visualroute.js
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1796 fix(icons): filter and list svg
  .changeset/strong-mails-sin.md
  packages/components/icons/src/generated/FilterAndListReact.tsx
  packages/components/icons/src/svg/filter-and-list.react.svg
Labels: 💅 Type: Enhancement, 🙏 Status: Dev Review
