Repository commercetools/ui-kit, pull requests merged in 2021-04, with the labels that each got.

#1849 fix(husky-command): set `yarn lint-staged`
  .husky/pre-commit
Labels: 🔮 Type: Chore

#1852 chore: bump all packages to v12
  .changeset/calm-lizards-think.md
Labels: 🔮 Type: Chore

#1854 refactor(text): accept `as` prop for inline render of `Text.Detail`
  packages/components/text/README.md
  packages/components/text/src/text.spec.js
  packages/components/text/src/text.story.js
  packages/components/text/src/text.styles.ts
  packages/components/text/src/text.tsx
Labels: ⛑ Type: Refactoring

#1851 docs(spacings-inline): flex-wrap alternative
  .changeset/violet-beans-perform.md
  packages/components/spacings/spacings-inline/README.md
Labels: ✍️ Type: Documentation, 🖐 Status: On Hold

#1843 refactor(link): use typescript
  .changeset/angry-beds-remain.md
  package.json
  packages/components/link/README.md
  packages/components/link/docs/usage-example.js
  packages/components/link/index.ts
  packages/components/link/package.json
  packages/components/link/src/index.ts
  packages/components/link/src/link.js
  packages/components/link/src/link.tsx
  packages/components/link/src/version.ts
  yarn.lock
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review

#1859 docs(readme): fix link to `custom-properties`
  README.md
Labels: ✍️ Type: Documentation, 🙏 Status: Dev Review

#1861 chore(preset): export pagination and sorting hooks
  .changeset/loud-feet-remain.md
  presets/ui-kit/src/index.js
Labels: 🔮 Type: Chore, 🙏 Status: Dev Review

#1863 fix(hooks): apply a value if available
  .changeset/lemon-eagles-sip.md
  packages/hooks/src/use-data-table-sorting-state/use-data-table-sorting-state.js
  packages/hooks/src/use-pagination-state/use-pagination-state.js
Labels: ⛑ Type: Refactoring, 🐛 Type: Bug

#1856 refactor(buttons): use TypeScript
  .changeset/five-impalas-impress.md
  .changeset/sour-pillows-build.md
  packages/components/buttons/accessible-button/src/accessible-button.tsx
  packages/components/buttons/flat-button/README.md
  packages/components/buttons/flat-button/docs/additional-info.md
  packages/components/buttons/flat-button/docs/usage-example.js
  packages/components/buttons/flat-button/index.ts
  packages/components/buttons/flat-button/package.json
  packages/components/buttons/flat-button/src/flat-button.styles.ts
  packages/components/buttons/flat-button/src/flat-button.tsx
  packages/components/buttons/flat-button/src/index.ts
  packages/components/buttons/flat-button/src/version.ts
  packages/components/buttons/icon-button/README.md
  packages/components/buttons/icon-button/docs/additional-info.md
  packages/components/buttons/icon-button/docs/usage-example.js
  packages/components/buttons/icon-button/index.ts
  packages/components/buttons/icon-button/package.json
  packages/components/buttons/icon-button/src/icon-button.js
  packages/components/buttons/icon-button/src/icon-button.story.js
  packages/components/buttons/icon-button/src/icon-button.styles.ts
  packages/components/buttons/icon-button/src/icon-button.tsx
  packages/components/buttons/icon-button/src/index.ts
  packages/components/buttons/icon-button/src/version.ts
  packages/components/buttons/link-button/package.json
  packages/components/buttons/primary-button/README.md
  packages/components/buttons/primary-button/docs/additional-info.md
  packages/components/buttons/primary-button/docs/usage-example.js
  packages/components/buttons/primary-button/index.ts
  packages/components/buttons/primary-button/package.json
  packages/components/buttons/primary-button/src/index.ts
  packages/components/buttons/primary-button/src/primary-button.js
  packages/components/buttons/primary-button/src/primary-button.styles.ts
  packages/components/buttons/primary-button/src/primary-button.tsx
  packages/components/buttons/primary-button/src/version.ts
  packages/components/buttons/secondary-button/index.ts
  packages/components/buttons/secondary-button/package.json
  packages/components/buttons/secondary-button/src/index.ts
  packages/components/buttons/secondary-button/src/secondary-button.js
  packages/components/buttons/secondary-button/src/secondary-button.spec.js
  packages/components/buttons/secondary-button/src/secondary-button.tsx
  packages/components/buttons/secondary-button/src/version.ts
  packages/components/buttons/secondary-icon-button/README.md
  packages/components/buttons/secondary-icon-button/docs/additional-info.md
  packages/components/buttons/secondary-icon-button/docs/usage-example.js
  packages/components/buttons/secondary-icon-button/index.ts
  packages/components/buttons/secondary-icon-button/package.json
  packages/components/buttons/secondary-icon-button/src/index.ts
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.js
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.styles.ts
  packages/components/buttons/secondary-icon-button/src/secondary-icon-button.tsx
  packages/components/buttons/secondary-icon-button/src/version.ts
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Status: ship it

#1874 refactor(components/field-errors): migrate to TypeScript
  .changeset/nasty-hats-fold.md
  packages/components/field-errors/README.md
  packages/components/field-errors/index.ts
  packages/components/field-errors/src/field-errors.tsx
  packages/components/field-errors/src/index.ts
  packages/components/field-errors/src/messages.ts
  packages/components/field-errors/src/version.ts
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Status: ship it

#1873 refactor(calendar-time-utils): use Moment types
  .changeset/chilly-bugs-invent.md
  packages/calendar-time-utils/index.ts
  packages/calendar-time-utils/src/calendar-time.ts
  packages/calendar-time-utils/src/index.ts
  packages/calendar-time-utils/src/version.ts
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review, 🚀 Status: ship it

#1876 refactor(multiline-text-input): migrate to TypeScript
  .changeset/real-squids-mix.md
  packages/components/inputs/multiline-text-input/README.md
  packages/components/inputs/multiline-text-input/index.ts
  packages/components/inputs/multiline-text-input/src/index.ts
  packages/components/inputs/multiline-text-input/src/multiline-text-input.tsx
  packages/components/inputs/multiline-text-input/src/version.ts
Labels: ⛑ Type: Refactoring, 🙏 Status: Dev Review
