Repository commercetools/ui-kit, pull requests merged in 2021-01, with the labels that each got.

#1726 refactor(filter and list icon): updated icon content per UX request
  .changeset/funny-socks-pretend.md
  packages/components/icons/src/generated/FilterAndListReact.js
  packages/components/icons/src/svg/filter-and-list.react.svg
Labels: ⛑ Type: Refactoring

#1732 refactor(utils): migrate to typescript
  .changeset/nervous-hairs-design.md
  packages/utils/index.ts
  packages/utils/package.json
  packages/utils/src/add-static-fields.js
  packages/utils/src/add-static-fields.ts
  packages/utils/src/create-sequential-id.spec.ts
  packages/utils/src/create-sequential-id.ts
  packages/utils/src/filter-aria-attributes.js
  packages/utils/src/filter-aria-attributes.spec.ts
  packages/utils/src/filter-aria-attributes.ts
  packages/utils/src/filter-data-attributes.js
  packages/utils/src/filter-data-attributes.spec.ts
  packages/utils/src/filter-data-attributes.ts
  packages/utils/src/filter-invalid-attributes.js
  packages/utils/src/filter-invalid-attributes.spec.ts
  packages/utils/src/filter-invalid-attributes.ts
  packages/utils/src/get-field-id.js
  packages/utils/src/get-field-id.ts
  packages/utils/src/helpers/exenv.ts
  packages/utils/src/helpers/safeHTMLElement.js
  packages/utils/src/helpers/safeHTMLElement.ts
  packages/utils/src/index.ts
  packages/utils/src/is-numberish.spec.ts
  packages/utils/src/is-numberish.ts
  packages/utils/src/parse-time.spec.ts
  packages/utils/src/parse-time.ts
  packages/utils/src/version.ts
  packages/utils/src/warn-deprecated-component.ts
  packages/utils/src/warn-deprecated-prop.ts
  yarn.lock
Labels: ⛑ Type: Refactoring

#1734 refactor(localized-utils): use typescript
  .changeset/witty-sheep-hear.md
  packages/localized-utils/index.ts
  packages/localized-utils/src/index.ts
  packages/localized-utils/src/localized.js
  packages/localized-utils/src/localized.spec.ts
  packages/localized-utils/src/localized.ts
  packages/localized-utils/src/version.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1735 refactor(horizontal-constraint): use typescript
  .changeset/sixty-paws-allow.md
  packages/components/constraints/README.md
  packages/components/constraints/package.json
  packages/components/constraints/src/helpers.ts
  packages/components/constraints/src/horizontal/horizontal.spec.tsx
  packages/components/constraints/src/horizontal/horizontal.tsx
  packages/components/constraints/src/horizontal/index.ts
  packages/components/constraints/src/index.ts
  packages/components/constraints/src/version.ts
Labels: ⛑ Type: Refactoring, 🚀 Status: ship it

#1736 refactor(spacings): to typescript
  .changeset/yellow-rats-heal.md
  packages/components/spacings/spacings-inline/index.ts
  packages/components/spacings/spacings-inline/src/index.ts
  packages/components/spacings/spacings-inline/src/inline.js
  packages/components/spacings/spacings-inline/src/inline.spec.tsx
  packages/components/spacings/spacings-inline/src/inline.styles.ts
  packages/components/spacings/spacings-inline/src/inline.tsx
  packages/components/spacings/spacings-inline/src/version.ts
  packages/components/spacings/spacings-inset-squish/index.ts
  packages/components/spacings/spacings-inset-squish/src/index.ts
  packages/components/spacings/spacings-inset-squish/src/inset-squish.spec.tsx
  packages/components/spacings/spacings-inset-squish/src/inset-squish.tsx
  packages/components/spacings/spacings-inset-squish/src/version.ts
  packages/components/spacings/spacings-inset/index.ts
  packages/components/spacings/spacings-inset/src/index.ts
  packages/components/spacings/spacings-inset/src/inset.spec.tsx
  packages/components/spacings/spacings-inset/src/inset.tsx
  packages/components/spacings/spacings-inset/src/version.ts
  packages/components/spacings/spacings-stack/index.ts
  packages/components/spacings/spacings-stack/src/index.ts
  packages/components/spacings/spacings-stack/src/stack.js
  packages/components/spacings/spacings-stack/src/stack.spec.tsx
  packages/components/spacings/spacings-stack/src/stack.styles.ts
  packages/components/spacings/spacings-stack/src/stack.tsx
  packages/components/spacings/spacings-stack/src/version.ts
Labels: ⛑ Type: Refactoring

#1738 chore: regenerate README
  packages/components/avatar/README.md
  packages/components/card/README.md
  packages/components/collapsible-panel/README.md
  packages/components/data-table-manager/README.md
  packages/components/data-table/README.md
  packages/components/fields/async-creatable-select-field/README.md
  packages/components/fields/async-select-field/README.md
  packages/components/fields/creatable-select-field/README.md
  packages/components/fields/date-field/README.md
  packages/components/fields/date-range-field/README.md
  packages/components/fields/date-time-field/README.md
  packages/components/fields/localized-multiline-text-field/README.md
  packages/components/fields/localized-text-field/README.md
  packages/components/fields/money-field/README.md
  packages/components/fields/multiline-text-field/README.md
  packages/components/fields/number-field/README.md
  packages/components/fields/password-field/README.md
  packages/components/fields/radio-field/README.md
  packages/components/fields/search-select-field/README.md
  packages/components/fields/select-field/README.md
  packages/components/fields/text-field/README.md
  packages/components/fields/time-field/README.md
  packages/components/inputs/async-creatable-select-input/README.md
  packages/components/inputs/async-select-input/README.md
  packages/components/inputs/creatable-select-input/README.md
  packages/components/inputs/date-input/README.md
  packages/components/inputs/date-range-input/README.md
  packages/components/inputs/date-time-input/README.md
  packages/components/inputs/localized-multiline-text-input/README.md
  packages/components/inputs/localized-text-input/README.md
  packages/components/inputs/money-input/README.md
  packages/components/inputs/multiline-text-input/README.md
  packages/components/inputs/number-input/README.md
  packages/components/inputs/password-input/README.md
  packages/components/inputs/search-select-input/README.md
  packages/components/inputs/select-input/README.md
  packages/components/inputs/text-input/README.md
  packages/components/inputs/time-input/README.md
  packages/components/loading-spinner/README.md
  packages/components/stamp/README.md
  packages/components/tag/README.md
  packages/components/tooltip/README.md
Labels: 🔮 Type: Chore, 🚀 Status: ship it

#1746 refactor(components/text): to typescript
  .changeset/large-wolves-kneel.md
  packages/components/text/package.json
  packages/components/text/src/index.ts
  packages/components/text/src/text.js
  packages/components/text/src/text.spec.js
  packages/components/text/src/text.styles.ts
  packages/components/text/src/text.tsx
  packages/components/text/src/version.ts
Labels: 🚀 Status: ship it

#1718 feat(pagination): add new pagination component
  .changeset/friendly-planets-glow.md
  .gitignore
  packages/components/pagination/LICENSE
  packages/components/pagination/README.md
  packages/components/pagination/docs/usage-example.js
  packages/components/pagination/index.js
  packages/components/pagination/package.json
  packages/components/pagination/src/index.js
  packages/components/pagination/src/page-navigator/index.js
  packages/components/pagination/src/page-navigator/messages.js
  packages/components/pagination/src/page-navigator/page-navigator.js
  packages/components/pagination/src/page-navigator/utils.ts
  packages/components/pagination/src/page-size-selector/index.js
  packages/components/pagination/src/page-size-selector/messages.js
  packages/components/pagination/src/page-size-selector/page-size-selector.js
  packages/components/pagination/src/pagination.js
  packages/components/pagination/src/pagination.spec.js
  packages/components/pagination/src/pagination.story.js
  packages/components/pagination/src/pagination.visualroute.js
  packages/components/pagination/src/pagination.visualspec.js
  packages/components/pagination/src/version.js
  presets/ui-kit/package.json
  presets/ui-kit/src/index.js
Labels: 🚀 Type: New Feature
